### ISSUE TITLE
Railcraft boilers crash the server

### ISSUE THREAD

**Issue by Erik3003** [FTBTeam/FTB-Ultimate-Reloaded#1]
* **Modpack Version**: 1.0.0

* **Issue**: Railcraft boilers crash the game, this is a known issue (https://minecraft.curseforge.com/projects/railcraft/files/2657610) which has not been resolved in the newest buildcraft release. I suggest you disable the recipes for now.

* **Link to Log or Crash File Paste**: Irrelevant, known RC issue.

* **Is it Repeatable?**: Yes, just place a boiler.

* **Mod/s Affected**: Railcraft

* **Known Fix**: Not using RC-boilers.

**Comment by liach** [comment]
Railcraft will have beta 5 soon, which fixes this issue.

**Comment by tfox83** [comment]
I am currently testing B5 of railcraft now and if stable will make it in next update of the pack which fixes this issue

**Comment by tfox83** [comment]
Update 1.0.1 released
