### ISSUE TITLE
1.0.1 is not yet on the Twitch launcher

### ISSUE THREAD

**Issue by Time6628** [FTBTeam/FTB-Ultimate-Reloaded#10]
* **Modpack Version**: 1.0.1

* **Issue**: The newest version of the pack is not yet available on the Twitch launcher.

* **Is it Repeatable?**: I have had at least 10 reports and have experienced myself that it's not there and there's no other version than 1.0.0.
![image](https://user-images.githubusercontent.com/9041033/52722764-4ca66680-2f7a-11e9-9565-66f185283f7d.png)
![image](https://user-images.githubusercontent.com/9041033/52722799-5d56dc80-2f7a-11e9-9c8e-0a0cd5be5370.png)

**Comment by tfox83** [comment]
I have no control on what shows up there, you will have to report issues with the twitch launcher to twitch support

**Comment by Time6628** [comment]
It's showing up now.
