### ISSUE TITLE
FTBUtilities'  home commands not working on server

### ISSUE THREAD

**Issue by bernie-sandler** [FTBTeam/FTB-Ultimate-Reloaded#101]
* **Modpack Version**: 1.0.1

* **Issue**: Homes from FTB Utilities is not working. Returns Unknown command for player and op.

* **Link to Log or Crash File Paste**: No crash nor log, simply returns unknown command.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: FTB Utilities

* **Known Fix**: !!! Not sure why I didn't notice this earlier !!!

**Navigate to:**
_[SERVER FOLDER]/config/ftbutilities.cfg_ <--edit this, scroll down to 'commands {' section and look for 'B:home', change its value to true. **For some reason its default value is false.**

**Comment by ChosenArchitect** [comment]
We are having the same issue on our server. It's just leaving the server hanging. No crash log.

**Comment by bernie-sandler** [comment]
Fix edited into original post. After restarting the server home commands started working!

**Comment by alexsch01** [comment]
I think it is disabled by default
