### ISSUE TITLE
BuildCraft Factory Auto Workbench duplication

### ISSUE THREAD

**Issue by WhosyVox** [FTBTeam/FTB-Ultimate-Reloaded#102]
* **Modpack Version**: 1.2.0

* **Issue**:
Using a _Retro Exchange_ Transmutation Stone with less than full durability in a _BuildCraft Factory_ Auto workbench will, on completing the first craft attempt, eject the stone to the ground while simultaneously moving a copy of the stone into the next storage slot. Once the second crafting attempt is complete, the copy will be ejected and the machine will halt.
This may affect other items with charge/durability, but it has yet to be tested or observed.

* **Steps to reproduce**:
1) Obtain a Transmutation Stone with fewer than 1500 charges, and 2 Ender Pearls
2) Set up an auto-workbench with a recipe to transmute 1 Ender Pearl into 4 Iron Ingots
3) Insert both Ender Pearls and Transmutation Stone into the input slots of the machine

    **Expected output**:
    8x Iron Ingot
    1x Transmutation Stone with 2 fewer charges

    **Actual result**:
    8x Iron Ingot
    1x Transmutation Stone with 2 fewer charges remaining
    1x Transmutation Stone with 1 fewer charges remaining

**Comment by tfox83** [comment]
Known issue with any damaged items.  Hopefully BC will get a fix in soon

**Comment by AlexIIL** [comment]
Just FYI this was never reported to BC directly - so I've opened https://github.com/BuildCraft/BuildCraft/issues/4385 to track it's progress.

**Comment by AlexIIL** [comment]
*Finally* released in [7.99.24.8](https://mod-buildcraft.com/buildcraft-799248.html). Sorry for the delay, 1.16.x has been quite distracting :p
