### ISSUE TITLE
game crashes when crafting when inventory is full

### ISSUE THREAD

**Issue by powerbuilder0** [FTBTeam/FTB-Ultimate-Reloaded#103]
* **FTB Ultimate Reloaded 1.0.1**
* **game crashes when crafting when inventory is full**
* **Yes Is it Repeatable?**
* **FTB Ultimate Reloaded 1.0.1**
* **UnKnown if a Fix exists**

game crashes when crafting when inventory is full using the crafting table on a stick, shift left clicking to make a stack of items seems to be the cause

**Comment by LemADEC** [comment]
no logs provided, hence not a problem

**Comment by powerbuilder0** [comment]
it was not responding and crashed to desktop is there a way to log that?

**Comment by powerbuilder0** [comment]
![image](https://user-images.githubusercontent.com/48012202/53479706-55904f80-3ac5-11e9-94f4-b839cd8f8175.png)

**Comment by powerbuilder0** [comment]
here is a screenshot of my inventory, as you can see it is completely full with only enough space left to craft a pickaxe with the portable crafting table (crafting table on a stick). I have gone to shift click to place it in the first available spot in my inventory and the game hangs and never recovers and crashes to desktop if i do anything making a crash log is impossible like this.

This bug is repeatable in both single player and multiplayer.
![image](https://user-images.githubusercontent.com/48012202/53595967-5cfd4900-3bea-11e9-8c0b-19cb7c1edb82.png)
