### ISSUE TITLE
Tin, copper and other ores missing on IF mining laser

### ISSUE THREAD

**Issue by Dinip** [FTBTeam/FTB-Ultimate-Reloaded#104]
* **Modpack Version**: 1.1.1

* **Issue**: There are several ores missing on industrial foregoing laser miner, like copper and tin.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Foregoing

**Comment by Dinip** [comment]
It also doesn't get certus quartz. On jei it says that gets but after 3 days mining not even a certus ore, only charged certus 
![image](https://user-images.githubusercontent.com/8941012/53516204-a30bbd00-3ac3-11e9-8de0-34ff5ceec1a8.png)
![image](https://user-images.githubusercontent.com/8941012/53516136-81aad100-3ac3-11e9-8f38-78e4707da05a.png)

**Comment by tfox83** [comment]
-Overhauled IF mining laser output to match older MFR output which was found in Ultimate, levels/biomes/dims no longer matter.  (Lens however do still influence production)

**Comment by tfox83** [comment]
in 1.2.1 beta
