### ISSUE TITLE
Add RC quarried stone to Chisel in order to get Marble

### ISSUE THREAD

**Issue by garlicinyoureye** [FTBTeam/FTB-Ultimate-Reloaded#105]
* **Modpack Version**:  1.2.0 Beta

* **Issue**: Marble isn't obtainable

* **Link to Log or Crash File Paste**: No crashes to report

* **Is it Repeatable?**: Yep, repeatably can't get marble

* **Mod/s Affected**: Chisel, Railcraft, Projectred

**Comment by Delzuar** [comment]
You said Railcraft is affected so i assume you are talking about Quarried stone. If its the case you can get some with cobblestone and bonemeal.

C = Cobblestone
B = Bonemeal

CCC
CBC
CCC

**Comment by garlicinyoureye** [comment]
Correct but thst stone can't be chiseled to Marble. That's the goal here
rather than adding a separate recipe for Marble.

**Comment by Delzuar** [comment]
Why are you talking about railcraft then.. There no marble with railcraft

**Comment by garlicinyoureye** [comment]
Quarried stone is from railcraft, that mod is impacted by adding quarries
stone to chisel config to get marble since they share the same table.

**Comment by Delzuar** [comment]
Oh i see, my mistake i missread the issue title

**Comment by tfox83** [comment]
-Changed quarried stone recipe output to stone version (can be chisled into marble)

**Comment by tfox83** [comment]
in 1.2.1 beta
