### ISSUE TITLE
Modded Server Wont Work

### ISSUE THREAD

**Issue by Zemanwhoscool** [FTBTeam/FTB-Ultimate-Reloaded#106]
When playing the mod with my friends, all of the mod UI's are there but we cannot place modded blocks, craft modded items, or get modded biomes. I have tried replacing configs and scripts but nothing is working, please help.

**Comment by phit** [comment]
stop starting the vanilla server and use the provided `ServerStart.bat` (Windows) or `ServerStart.sh` (linux/mac)

**Comment by Zemanwhoscool** [comment]
https://gyazo.com/ba97afb862b46c1eecaec6d6fe1edd24. Once i originally launch this file it stops working, and to progress through install i have to use normal minecraft launcher which seems to break everything? So how am i supposed to launch through that client

**Comment by phit** [comment]
install 64bit java 8, client has nothing to do with server

**Comment by Zemanwhoscool** [comment]
https://gyazo.com/ba97afb862b46c1eecaec6d6fe1edd24. Once i originally launch this file it stops working, and to progress through install i have to use normal minecraft launcher which seems to break everything? So how am i supposed to launch through that client
