### ISSUE TITLE
Custom world type not working properly

### ISSUE THREAD

**Issue by gokrow** [FTBTeam/FTB-Ultimate-Reloaded#107]
Modpack Version: 1.2.0

Issue: Vanilla ores are not affected by settings that should change their rarity or size of the ore veins. Diamonds appear to not generate properly and changing any settings seems to keep them from generating at all.

Link to Log or Crash File Paste: Did not crash

Is it Repeatable?: Yes

Mod/s Affected: Unknown

Known Fix: Unknown

**Comment by tfox83** [comment]
Sorry I cannot support custom world types
