### ISSUE TITLE
Tech Reborn Auto Crafting Table not working correctly multiple issues

### ISSUE THREAD

**Issue by ranmas** [FTBTeam/FTB-Ultimate-Reloaded#109]
* **Modpack Version**:
1.2.1
* **Issue**: 
Crafting table is not pulling from chests next to it.  Engines have to be used to both put item into the table and pull items out.  

Using the lock in the table gui does not lock the recipe.  If for instance your making Bone meal in the table once the stack has reached 64 it will start a new stack breaking production of the bone meal. this can be done while using the engines to pump items in or with hoppers. using the exact setup they have in the tutorials does not work.

When breaking the table with a pickaxe you only get back a basic machine casing. The auto Crafting table for instance does not take a basic machine casing to make it.  This issue effects multiple blocks from this mod.  Macerator and MFE at least, have not tested others

Will not accept items from itemducts even though the itemduct looks to connect to it.

**Comment by modmuss50** [comment]
humm, make sure you are using the slot config settings.

I will test this anyway.

**Comment by ranmas** [comment]
I was incorrect about the breaking of the block it seems that is what it should do according to the items page on the tech reborn wiki.  But that wiki has nothing else on this block. 
https://wiki.techreborn.ovh/doku.php?id=blocks:autocrafting

I also must have had something else stuck in the pipes when I was working with it before, as I was able to get those to work.

What slot config settings?  I put in the recipe for the item I want created and it should make them according to the ftb wiki.
https://ftb-wiki.com/wiki/Automatic_Crafting_Table

What the machine is doing when you try to make at least a single item recipe is putting the incoming items into the top left slot.  No matter where the item is in the recipe grid.  

OK so move the item to the top left slot.  Items are now flowing into the correct spot, and the recipe is being made.  Then the system overflows the item stack limit and puts the overflow into the next slot, and breaks production.

Producing stone slabs:

Putting the three stones in the top row it begins filling them from the top right then moves to the left placing each 'pull' of items into another slot correctly.  When it eventually reaches overflow it then places the next stone into the middle left grid slot and breaks the crafting.

When producing stairs.  

It fills the recipe slots up like it should, but once again if your capable of transferring items quicker than what it can keep up with then when it overflows it flows into the top left grid slot breaking crafting.

**Comment by ranmas** [comment]
I was incorrect about the breaking of the block it seems that is what it should do according to the items page on the tech reborn wiki.  But that wiki has nothing else on this block. 
https://wiki.techreborn.ovh/doku.php?id=blocks:autocrafting

I also must have had something else stuck in the pipes when I was working with it before, as I was able to get those to work.

What slot config settings?  I put in the recipe for the item I want created and it should make them according to the ftb wiki.
https://ftb-wiki.com/wiki/Automatic_Crafting_Table

What the machine is doing when you try to make at least a single item recipe is putting the incoming items into the top left slot.  No matter where the item is in the recipe grid.  

OK so move the item to the top left slot.  Items are now flowing into the correct spot, and the recipe is being made.  Then the system overflows the item stack limit and puts the overflow into the next slot, and breaks production.

Producing stone slabs:

Putting the three stones in the top row it begins filling them from the top right then moves to the left placing each 'pull' of items into another slot correctly.  When it eventually reaches overflow it then places the next stone into the middle left grid slot and breaks the crafting.

When producing stairs.  

It fills the recipe slots up like it should, but once again if your capable of transferring items quicker than what it can keep up with then when it overflows it flows into the top left grid slot breaking crafting.

**Comment by modmuss50** [comment]
Should be fixed in the next version, I changed a bunch of code that should make it a bit better.

**Comment by tfox83** [comment]
included in 1.4.0 beta releasing later today
