### ISSUE TITLE
Laserdrill: Forestry resources have weight of 55

### ISSUE THREAD

**Issue by dermalikmann** [FTBTeam/FTB-Ultimate-Reloaded#110]
There is probalby a typo in the config, where the weight of forestry resources have a weight of 55.
We don't need this much apatite... 😅 

* **Modpack Version**: 1.2.1

* **Issue**: Laserdrill Forestry resources way to high weight

* **Is it Repeatable?**: Yews

* **Mod/s Affected**: Forestry + IndustrialForgoing

* **Known Fix**: Change weight

**Comment by tfox83** [comment]
Thanks, fixed in next update
