### ISSUE TITLE
Impossible to craft Advanced Lappack

### ISSUE THREAD

**Issue by gambiting** [FTBTeam/FTB-Ultimate-Reloaded#111]
Hi,

It's impossible to craft the Advanced Lappack - the recipe requires the Energypack, but it doesn't exist in this mod(it can't even be spawned using creative mode). The lappack(which is meant to be worse than the Advanced Lappack) is actually completely wrong - it stores 20 MEU and can only be charged using MFSU, so it behaves like the Ultimate Lappack. It can however be crafted.

**Comment by toothstone** [comment]
I can craft the Advanced Lappack from Lappack + Adv. Circuit + Energy Crystal, however it only stores 3MEU and is thus worse than the Lappack (20MEU). I can confirm that the Energypack is not craftable.

Tested with 1.2.1 via MultiMC on Linux.

**Comment by tfox83** [comment]
Use the second recipe that is available :)
