### ISSUE TITLE
Spent Fuel Rod has no uses, cannot craft Re-Enriched Uranium and therefore Nukes

### ISSUE THREAD

**Issue by gambiting** [FTBTeam/FTB-Ultimate-Reloaded#112]
Hi,

Like the title says - I can craft Fuel Rods for the nuclear reactor, but after they are spent they have no uses - it's not possible to create Re-Enriched Uranium out of them, and those are required to build the IC2 nuke.

**Comment by tfox83** [comment]
Changed the nuke recipe to obtainable items in next update
