### ISSUE TITLE
Double Stone Slab: duplicates other blocks.

### ISSUE THREAD

**Issue by shiftyshadow** [FTBTeam/FTB-Ultimate-Reloaded#113]
* **Modpack Version**:  1.1.0

* **Issue**:  Issue occurs with Stone Slab (#4263, advanced_solar_panels:double_stone_slab), crafted by placing 2 Stone Slabs (#0044/0, minecraft:stone_slab) on top of each other in your inventory or in a crafting table.  When you place this Double Stone Slab into the world it becomes a copy of whatever block you place it onto.  When you break the block it remains the copied type.  In this way you can duplicate almost any block in the game.

This works for every normal Minecraft block that I tried it on, including chests (though it doesn't copy the inventory).  Also if you place the Double Stone Slab onto non-vanilla blocks is will sometimes disappear, removing the block from your inventory, but not placing anything into the world.

* **Is it Repeatable?**:  Yes.

* **Mod/s Affected**:  Advanced Solar Panels (specifically the "Stone Slab")

* **Known Fix**:  Remove the crafting recipe, you can place the slabs on top of each other in game to have the same visual effect.  There is no need to craft the block first (that I know of).

**Comment by tfox83** [comment]
Fixed in 1.4.0 update releasing later today
