### ISSUE TITLE
ic2 recipes uncraftable in Arcane Workbench

### ISSUE THREAD

**Issue by ThwartAbyss54** [FTBTeam/FTB-Ultimate-Reloaded#114]
* **Modpack Version**: 1.2.1

* **Issue**: Cant craft IC2 tree taps,, machine block, copper cables in an arcane workbench.

* **Is it Repeatable?**: Yes, trying to craft any of them in an arcane workbench doesnt give an output but a regular crafting table does.

I suppose its not a big issue but was doing a mostly magic base and now have to have 2 crafting tables XD I only tried those 3 items but im sensing a trend. Havent gotten into Tech Reborn yet but we shall see.

**Comment by tfox83** [comment]
That is due to NBT, sorry it is only supported with crafting tables
