### ISSUE TITLE
Tech Reborn cell removes all liquid from buildcraft tank

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Ultimate-Reloaded#115]
* **v1.2.1**

* **When taking liquid out of Buildcraft tanks (I have a tall multiblock form) using Tech Reborn Cells, it takes all of the liquid out of the tank, even though the cell only holds 1 buckets worth. The rest of the liquid is wasted. The liquid I am storing is creosote oil. **

* **No crash log**

* **Yes, is repeatable**

* **Tech Reborn and Buildcraft**

**Comment by modmuss50** [comment]
Ill take a look, this should not be the case

**Comment by modmuss50** [comment]
Im struggling to track this one done, I think it could be an issue with build craft as far as I know our cells work with everything else.
