### ISSUE TITLE
Applied Energistics Controller

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Ultimate-Reloaded#116]
* **Modpack Version**: 1.2.1

* **Issue**: I updated our server from 1.1.0 to 1.2.1. During the work on the server (We're still working toward the release) we noticed that AE2 is in the pack, but the controller of AE2 is not which makes the entire pack useless. I wonder if this is intended, and if so, why not delete the entire mod as it is useless without?

![ae2](https://user-images.githubusercontent.com/42154364/53701072-a4a5ef80-3df9-11e9-835d-bf2479490fb3.png)

* **Link to Log or Crash File Paste**: I don't think this is needed

* **Is it Repeatable?**: Yes, even after server restarts the Controller won't appear

* **Mod/s Affected**: Applied Energistics 2, AE2 Stuff

* **Known Fix**: Not sure where it got disabled but I guess either removing the pack if it was intended, or add the controller?

**Comment by phit** [comment]
channels are disabled in this pack, you dont need the controller, you just use the energy acceptor

**Comment by NLBlacky** [comment]
Thanks alot for your reaction. I was quite confused in the beginning
