### ISSUE TITLE
Techreborn Interdimensional SU incorrect max input rate

### ISSUE THREAD

**Issue by kleinig** [FTBTeam/FTB-Ultimate-Reloaded#117]
* **Modpack Version**: 1.2.1

* **Issue**: Techreborn Interdimensional SU incorrect max input rate. Says on tool tip that it should be able to handle 8.192K EU/t. It is destroyed when going above 2K EU/t. Not sure if this intentional behavior or not as you can put an Adjustable SU next to a Fusion Control Computer and have it draw power just fine without it being destroyed.
* **Is it Repeatable?**: Yes

**Comment by modmuss50** [comment]
Humm, ill take a look. My guess is its an issue caused by the classic mode in ic2

**Comment by modmuss50** [comment]
I have upped the AESU max power to accommodate for this.

**Comment by tfox83** [comment]
included in 1.4.0 beta releasing later today
