### ISSUE TITLE
Autocrafting Generator is not working

### ISSUE THREAD

**Issue by Daddelion** [FTBTeam/FTB-Ultimate-Reloaded#118]
* **Modpack Version**: 1.1.1

* **Issue**: I crafted the pattern for the IC2 Generator with a RE-Battery, refined Iron and an iron Furnace.
When I want to use it, every item gets pulled into the ME crafting Storage, but the Generator is not crafted. I tested it in creative mode with infinite Energy and it's not working.

* **Link to Log or Crash File Paste**: No crash 

* **Is it Repeatable?**: yes of course, everytime u want to autocraft a generator!

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Please make sure you are actually using the items that you craft, not shift clicking the recipe in.  I tested this and it works fine for me crafting the individual items and make the pattern with those items.

**Comment by Daddelion** [comment]
No tit doesn't it has to do sth. with the battery I#m guessing everytime i wnat to craft a generator, it wants to make a ne battery. AND I didnt use shift- clicking for anything. I don't know what is happening but it's weird that it works for you I actually redid all pattern for the generator(iron furnace etc.) but still no success. So please dont just close it ^^ u can come onto my server and test it yourself if u dont believe me.

**Comment by DarkSiroga** [comment]
hello i have the same problem did you find a way how to fix it?
