### ISSUE TITLE
Futura Block not Craftable

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#119]
* **Modpack Version**: 1.1.1

* **Issue**: Futura Block not Craftable

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: ///

![futura1](https://user-images.githubusercontent.com/47696358/53750348-d37b9e80-3ea9-11e9-9e8a-7a6746fa602c.png)
![futura2](https://user-images.githubusercontent.com/47696358/53750352-d4accb80-3ea9-11e9-94a5-9dcab2711ca4.png)

**Comment by tfox83** [comment]
thanks, changed modem to require some iron, so future blocks can be crafted as intended in next update
