### ISSUE TITLE
Redstone Engines (BC) don't reorient their direction

### ISSUE THREAD

**Issue by MrJackmanB** [FTBTeam/FTB-Ultimate-Reloaded#12]
* **Modpack Version**: 1.0.1

* **Issue**: Redstone Engines (Buildcraft) do not properly reorient themselves to machines—at least not to the Mining Well (as far as I've tested). Instead, they only point up. This is not an issue for the Combustion Engine, which do reorient themselves to face machines—I have not tested others.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Buildcraft 7.99.21

* **Known Fix**:

**Comment by tfox83** [comment]
Redstone engines can only output to wooden transport pipes in this pack.  The do not produce power.

**Comment by AlexIIL** [comment]
Just to note: this isn't a config option in buildcraft, so that's all they ever do in any pack.
