### ISSUE TITLE
Block Placer: Not working in servers.

### ISSUE THREAD

**Issue by JeNaiKe** [FTBTeam/FTB-Ultimate-Reloaded#120]
Modpack Version: 1.2.1

**Block Placer**, from projectRed Expansion's mod not working in server.
- Give it any block(wood), when giving redstone signal (Lever and button) it **does the animation** but **doesn't** place any block.

* **Is it Repeatable?**: Totally. Have tried in **server** and **singleplayer**.
 - Server: **DOESN'T work* , also 1.2.1
 - SingleP: **WORKS!*

**Comment by tfox83** [comment]
Not able to reproduce this, please make sure you are not near spawn or in a claimed area.  Even your own claimed area.  You may have to set your team settings to allow fake players

**Comment by JeNaiKe** [comment]
Had to set it up as "Fake Players Status : Member" since I had The required for block editing as Member.

Sorry for bother, and thank you.
