### ISSUE TITLE
Nanosuit Night Vision 

### ISSUE THREAD

**Issue by Rexinator50** [FTBTeam/FTB-Ultimate-Reloaded#121]
* **Modpack Version**: 1.1.1
* **Issue**: Nanosuit Helmet still has its night vision capabilities like it would when using the post MC 1.6 recipe. There is no point in crafting the night vision goggles if this works.

* **Link to Log or Crash File Paste**: NULL

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Industrial Craft 2

* **Known Fix**: none

![2019-03-04_22 09 21](https://user-images.githubusercontent.com/48232946/53780492-64fb0880-3eca-11e9-8280-450f02ef277f.png)
Night vision is enabled during the day so I get blindness and as you can tell I do not have the night vision goggles equipped.

**Comment by tfox83** [comment]
I have been testing with the helm and have no night vision with the nano helm.
