### ISSUE TITLE
There is no way to move as much power [TechReborn]

### ISSUE THREAD

**Issue by Dinip** [FTBTeam/FTB-Ultimate-Reloaded#122]
* **Modpack Version**: 1.2.1

* **Issue**: I was planning to do a fusion reactor on my survival server but seems to be a problem it that... there is no way to move as much power as it generates, so there is no use for that reactor since even the lowest tier generates around 32k EU/t.

![image](https://user-images.githubusercontent.com/8941012/53848124-0e193000-3fab-11e9-8445-6ef8a6953d2d.png)

* **Mod/s Affected**: TechReborn?

* **Known Fix**: I think the only way to solve this problem is to enable the RF support for TechReborn, since there is no machines or cables that can handle more than 8192EU/t.

**Comment by modmuss50** [comment]
Can you not just put an AESU directly on it? Enabling RF isnt an option.

**Comment by Dinip** [comment]
Adjustable SU only supports 8kEU/t input

**Comment by modmuss50** [comment]
I have increased it in the next version.

**Comment by mdgrein** [comment]
I've plonked down an EV Energy Consumer on the reactor and then convert it to RF.
Tried to find out if the Energy Converters have any limits but as far as I can tell, there is none.

You can also place an AE2 EU P2P thingy on the reactor and then have as many outputs as you would like to distribute the power.

**Comment by tfox83** [comment]
I reenabled the EV energy consumer a few versions ago to fix this.

**Comment by gdm413229** [comment]
Try waiting for the possible superconductor cable update in Tech Reborn.
