### ISSUE TITLE
Some "Grains" from Binnie's extra bees has no uses

### ISSUE THREAD

**Issue by Langsig94** [FTBTeam/FTB-Ultimate-Reloaded#123]
* **Modpack Version**: Minecraft 1.12.2

* **Issue**: Platinum, Nickel and Iron Grains has no uses

* **Is it Repeatable?**: Yes check your JEI. It's only those 3 that can't be made into pulverized

* **Mod/s Affected**: Binnie's Extra Bees and perhaps Thermal Foundation

* **Known Fix**: If this isn't intended, the 3 grains should just be able to get made into pulverized metals from Thermal Foundation.

**Comment by tfox83** [comment]
Fixed in 1.4.0 beta being released today
