### ISSUE TITLE
Inventory bugging out

### ISSUE THREAD

**Issue by fosq** [FTBTeam/FTB-Ultimate-Reloaded#124]
* **Modpack Version**: 1.2.0

* **Issue**: Inventory items becoming unmovable, moving on their own to other slots like armor slots.
![yvydi](https://user-images.githubusercontent.com/17831723/54033604-6d4e8e80-41bd-11e9-956a-2161c87b101c.png)

* **Is it Repeatable?**: Right click an iron tank

* **Mod/s Affected**: Railcraft

* **Known Fix**: Relog and don't touch any iron tanks again

**Comment by tfox83** [comment]
Know issue atm with RC.  relogging fixes the issue.
