### ISSUE TITLE
Applied Energistics autocrafting doesn't like RE-Batteries

### ISSUE THREAD

**Issue by HelloMen01** [FTBTeam/FTB-Ultimate-Reloaded#125]
Modpack Version: 1.3.0

Issue: Applied Energistics 2's autocrafting can't craft recipes which include RE-Batteries from Industrialcraft2.

I tried crafting a Generator and BatBox. Both use one or more RE-Batteries.

![screenshot_3](https://user-images.githubusercontent.com/48142779/54045408-d9d38880-41d1-11e9-92cb-01a4fa9c67de.png)

Workarounds like using an ME Interface onto an Auto Workbench by Buildcraft also didn't work.

Is it Repeatable?: Yes.

Mod/s Affected: Applied Energistics 2; IndustrialCraft 2

Known Fix: ///

**Comment by mdgrein** [comment]
It also does not like Energy Crystals/Lapotron Crystals or just about any item that can hold power.

The workaround I use is to craft with the projectred tables.
The setup is quite a bit of hassle though as each table needs power, an interface and an import bus.
In addition to the fact that you also must set up the projectred recepie template thingy for the table itself meaning one table can only craft one thing.

My setup looks like this:
![image](https://user-images.githubusercontent.com/2192227/54065473-c51ee100-4221-11e9-8c0f-09a41c594d99.png)

**Comment by tfox83** [comment]
Any thing with damage/nbt has always been an issue with AE crafting, its nothing I can fix sadly.  mdgreins work around is a good one.
