### ISSUE TITLE
Suggestion: VeinMiner / Ore Excavation

### ISSUE THREAD

**Issue by NLBlacky** [FTBTeam/FTB-Ultimate-Reloaded#126]
* **Modpack Version**: 1.3.0

* **Issue**: We've had a few players on our server who would really appreciate it if VeinMiner or Ore Excavation was added to the modpack. This would allow them to mine a little bit easier since they are used to have Tinkers Construct or one of those mods in the modpack. 

* **Known Fix**: Adding VeinMiner or Ore Excavation to the modpack.

**Comment by tfox83** [comment]
no
