### ISSUE TITLE
Missing Blocks for Metal Press

### ISSUE THREAD

**Issue by NeariX67** [FTBTeam/FTB-Ultimate-Reloaded#128]
* **Modpack Version**: 1.2.0

* **Issue**: Missing redstone engineering block and engineer's manual, i dont know how to build the metal press in 1.12.2 (version 0.12-89)

* **Is it Repeatable?**: i guess

* **Mod/s Affected**: immersive engineering

**Comment by tfox83** [comment]
They have been removed in this pack to keep in line with 1.4 Ultimate
