### ISSUE TITLE
[Request] Railcraft Update! 

### ISSUE THREAD

**Issue by TheLittleCube** [FTBTeam/FTB-Ultimate-Reloaded#129]
* **Modpack Version**: All, (Originally noticed in 1.0.1)

* **Issue**: Railcraft Loading/saving issue (trains being save constantly if left unchecked can start hurting the server.) We caught ours up to 4k trains being saved every minute. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Server side (only a player can "load" additional chunks.)

* **Mod/s Affected**: RailCraft

* **Known Fix**: https://github.com/Railcraft/Railcraft/issues/1724 

Can we get an update to railcraft? They are waiting for confirmation to see if the bug is resolved. #

**Comment by tfox83** [comment]
there is no update available at this time publicly.  As soon as its available it will be in next version of the pack

**Comment by tfox83** [comment]
still awaiting the update to be public, so will not be in 1.4.0 of the pack, as beta 5 is all that is avail still.

**Comment by tfox83** [comment]
in 1.5.0 beta going live later today
