### ISSUE TITLE
Tin Can Recipe overly Expensive?

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Ultimate-Reloaded#13]
* **Modpack Version**: 1.0.1

* **Issue**: The tin can recipe seems too expensive for it's yield

* **Mod/s Affected**: Industrial Craft 2

* **Known Fix**: Increase the ammount of tin cans you recieve from the recipe OR change the recipe to take tin nuggets instead.

**Comment by modmuss50** [comment]
The old recipe was 4 I believe, this seems to be a bug on ic2's part. changing it with CT will be easier though.

**Comment by monkeybug34** [comment]
Yeah, 4 sounds familiarly correct.

**Comment by tfox83** [comment]
changed to 4 in next update
