### ISSUE TITLE
Blizz Powder recipe is missing from Fluid Transposer / Does not work

### ISSUE THREAD

**Issue by capnflummox** [FTBTeam/FTB-Ultimate-Reloaded#131]
* **Modpack Version**: 1.2.0
* **Issue**: Blizz powder cannot be made in the fluid transposer.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: There is also the issue that other recipes do not show up for this machine like normal (clicking on the graphic that shows machine operation progress).

* **Known Fix**: 

I could not find anything specifically about the recipe, TE material, or machine listed in any of the script files.

**Comment by tfox83** [comment]
the recipe does work, however there is a bug currenlty that is blocking the recipes in JEI.  Once a fix is provided or found it will be in
