### ISSUE TITLE
FTB Utilities backup won't run

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Ultimate-Reloaded#132]
* **Modpack Version**: 1.3.0

* **Issue**: Automatic FTB Utilities backups not running, also cannot run the /ftb backup command (says command not found)

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: FTB Utilities, FTBLib

**Comment by tfox83** [comment]
Will need logs from your server, its working fine in all our testing.

**Comment by MacChuck** [comment]
Which log do you need? latest.log, debug.log or both?
Also, what IS the FTB Utilities manual backup command, just be to sure i'm not totally mis-typing it.

**Comment by ByteRaper** [comment]
I have the same problem. When I type "/backup start xxx" in the server it says  "Unknown command. Try /help for a list of commands". Also the server isnt doing any backups.

**Comment by tfox83** [comment]
Ok that is becuase the mod has been broken into modules without me knowing, FTBU:backups mod will be included in next update later today.

**Comment by tfox83** [comment]
#blame @LatvianModder

**Comment by tfox83** [comment]
included in 1.4.0 beta releasing later today
