### ISSUE TITLE
advancements not granting - null pointer exception

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Ultimate-Reloaded#133]
* **Modpack Version**: 1.3.0

* **Issue**: Advancements intermittently not granting. This affects all of them from what I can tell (get a lava bucket, breed animals, kill the naga in the twilight forest, etc)

* **Link to Log or Crash File Paste**: I saw this come up in the console while I had it open, and I copy and pasted it, but can't find it in the logs. 
https://paste.feed-the-beast.com/view/30dee0b8

* **Is it Repeatable?**: Yes. Fire up the server, have people play over the course of a few hours, eventually it'll come up.

* **Mod/s Affected**: n/a

* **Known Fix**: disconnecting & reconnecting to the game, or restarting the server sometimes fixes it.

**Comment by tfox83** [comment]
ITs a known issue atm that a fix will be included as soon as the dev can fix it, if they can.  Its nothing major as its not crashing or causing issues

**Comment by MacChuck** [comment]
Might want to disable twilight forest forced progression, as advancements not granting properly will cause TF impossible to progress through.
