### ISSUE TITLE
ae2 autocraft(with pattern) does not work ic2 items.

### ISSUE THREAD

**Issue by HyoungYong** [FTBTeam/FTB-Ultimate-Reloaded#136]
version: FTBUltimateReloaded-1.2.1-1.12.2 (uploaded Mar 1, 2019)

crafting ic2 solar panel(tier 1), it just shows "Scheduled", and not craft..

Yellow highlight is Scheduled items(ic2 generator, ic2 solar panel)
![craft](https://user-images.githubusercontent.com/23513821/54173827-d9cfd300-44c6-11e9-91bf-fdbef47ad7c7.PNG)

**Comment by MysticalHeat** [comment]
I think it is not craft because of re-battery and same items such as energy and lapotron crystals (allow ore-dic doesn't help). FTB team, need fix! :D

**Comment by tfox83** [comment]
This is not a fix on my part sorry.  Wish I could, its a know issue.
