### ISSUE TITLE
SoulShard Cage crashing the server

### ISSUE THREAD

**Issue by JeNaiKe** [FTBTeam/FTB-Ultimate-Reloaded#138]
* **Modpack Version**: 1.2.1

* **Issue**: SoulShard Cage 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d50ceeb3

* **Is it Repeatable?**: As my friend said: "I placed the spawner and right-clicked it probably too fast with the shard'. Spawner was also 1 block above a open trapdoor.

* **Mod/s Affected**: soulsShardRespawn

* **Known Fix**: Removing the mod "soulShardRespawn" and lauching the server, clearing everything (placed a block in spawner location) fixed the server.

Edit 1:
[link](https://paste.feed-the-beast.com/view/21dbbe40) to the server log (see the end) in the session when it crashed. Thanks.

[link](https://paste.feed-the-beast.com/view/5c2089cf) to the server _crash log_ when trying to Initiate again.

**Comment by tfox83** [comment]
This seems to be a one off with the trap door being located below.  I tried to replicate this issue and could not.  If you have anymore issues please let me know.  If you encounter a block crash like this in the future you can enable a config in forge.cfg to remove erroring blocks.  Will save you from having to remove mod to fix a startup crash.
