### ISSUE TITLE
Cannot craft wiring from Modular Power Armor

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Ultimate-Reloaded#14]
* **Modpack Version**: 1.0.1

* **Issue**: You cannot craft wiring from the power armor mod because the copper cable in the recipe is unobtainable.

* **Mod/s Affected**: Machinemuse's Modular PowerArmor

* **Known Fix**: make the recipe use IC2 cables.

**Comment by EthernalVoid** [comment]
fix in my recipe changes comment ;3

**Comment by tfox83** [comment]
switched to IC2 copper cable in next update
