### ISSUE TITLE
Nukes Still Uncraftable

### ISSUE THREAD

**Issue by bearsdotzone** [FTBTeam/FTB-Ultimate-Reloaded#140]
* **Modpack Version**: 1.3.0

* **Issue**: Nukes are still uncraftable, specifically as a consequence of the tech reborn advanced electronic circuit being uncraftable.

* **Is it Repeatable?**: Yes

* **Known Fix**: In scripts/ic2.zs line 78, change ``techreborn:part:30`` to ``ic2:crafting:2`` to use the IC2 advanced circuit.

**Comment by tfox83** [comment]
fixed in dev, will be in next version after 1.4.0 beta as that was just pushed live.

**Comment by tfox83** [comment]
in 1.5.0 beta going live later today
