### ISSUE TITLE
Crash at Start

### ISSUE THREAD

**Issue by Yelikhan** [FTBTeam/FTB-Ultimate-Reloaded#141]
* **Modpack Version**: 1.3.0

* **Issue**: Crash at Start 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2f2eb088

* **Is it Repeatable?**: Everytime I launch the game It loads for a while and then crashes

* **Mod/s Affected**: I disabled many mods because In the crash reports It said that they were causing the crash

* **Known Fix**: None

**Comment by tfox83** [comment]
Please try a fresh install of the pack, we are not able to reproduce this.  Sounds like the pack didnt download all the files when you installed
