### ISSUE TITLE
Alchemical Brass Plate (unification)

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Ultimate-Reloaded#142]
* **Modpack Version**: 1.4.0

* **Issue**: IC2 compressor won't accept alchemical brass ingots to make plates

* **Is it Repeatable?**: yes

* **Mod/s Affected**: thaumcraft

* **Known Fix**: Couple of workarounds.
A: Use a rolling machine (4:4).
B: Use a thermal expansion compressor.
C: use a grindstone to turn the alchemical brass ingot into dust then re-smelt it into the tech reborn ingot to be compressed in the compressor.

* **Change Request**: Add a recipe to the ic2 compressor for alchemical brass?

**Comment by tfox83** [comment]
Fixed in 1.5.0 beta releasing later today
