### ISSUE TITLE
Game not Launching at all from twitch launcher

### ISSUE THREAD

**Issue by murawski21** [FTBTeam/FTB-Ultimate-Reloaded#145]
* **Modpack Version**: 1.3.0

* **Issue**: After downloading the game and clicking play it starts to launch then just stops.

* **Link to Log or Crash File Paste**: N/a

* **Is it Repeatable?**: Happens everytime I try to start it up.

* **Mod/s Affected**: n/a
* **Known Fix**: n/a

**Comment by tfox83** [comment]
Please try a fresh install, we are not able to reproduce this.
