### ISSUE TITLE
Quarry no longer works

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Ultimate-Reloaded#146]
* **Modpack Version**: 
1.0.1 and later. 
* **Issue**: 
Quarry accepts no power from any source
* **Link to Log or Crash File Paste**: 
There is no crash file, it just does not accept any kind of power
* **Is it Repeatable?**: 
Try connecting any power that is not creative mode power
* **Mod/s Affected**: 

* **Known Fix**: 
here is a perfect fix. QUIT CHANGING OTHER PEOPLES MODS TO SUIT YOUR WANTS AND LEAVE OTHER PEOPLES ORIGINAL CONTENT AS THEY CREATED IT.

**Comment by torey0** [comment]
Works fine with BuildCraft power on 1.0.1. 

![2019-03-15_17 06 48](https://user-images.githubusercontent.com/47702093/54464464-ccc01780-4744-11e9-95ce-79bf81cc5d33.png)

**Comment by Zarkazm** [comment]
I'm running a FTB Ultimate Reloaded server, currently pack version 1.4.0, and can confirm Quarry is accepting BuildCraft power as it should.  I'm using a Combustion Engine setup with Kinesis Pipes, and another player is using the Energy Converters mod with an MJ Energy Producer directly against their Quarry; both are working fine.

**Comment by tfox83** [comment]
Works fine on my end.

**Comment by tfox83** [comment]
And we can change anything we want to, thats the whole point of a mod pack :) If you dont like changes in a pack I suggest making your own pack to suit your needs as a player.  But FYI the quarry was not changed by me in this pack.  Tech Reborn changes the recipe slightly as GT did in the original FTB Ultimate modpack.  The quarry uses MJ which is a power added by BC.  This has been a thing in all of 1.12 Buildcraft versions.
