### ISSUE TITLE
Sunnarium uncraftable

### ISSUE THREAD

**Issue by SaanMcC** [FTBTeam/FTB-Ultimate-Reloaded#147]
* **Modpack Version**: 1.3.0

* **Issue**: Sunnarium is uncraftable due to no UU Matter, means no Hybrid Solar Helmets

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Advanced Solar Panels

* **Known Fix**: Enable Molecular Transformer, which can convert glowstone at a cost of 9m EU?

**Comment by MacChuck** [comment]
Both the Mass fab and Matter fab in my single player test world in 1.4.0 create UU-matter.

**Comment by SaanMcC** [comment]
Yep, confirmed works in 1.4.0

**Comment by tfox83** [comment]
I see you sorted the Issue, I just tested as well and works fine in latest versions of the pack
