### ISSUE TITLE
Map Mod causes crash

### ISSUE THREAD

**Issue by Hpgamer11** [FTBTeam/FTB-Ultimate-Reloaded#148]

**Comment by Hpgamer11** [comment]
Xaero's World Map to be exact

**Comment by tfox83** [comment]
need more info.  A crash report to start at least.

**Comment by simchanu29** [comment]
Version of FTB Ultimate Reloaded : `1.3.0`
Version of minecraft : `1.12.2`

I had a similar crash. I can provide this one. I'm not sure this is exactly Xaero map but the stacktrace seems to indicate it. It only happened on 1 PC out of 5.
[hs_err_pid16288](https://pastebin.com/JgQSNu13)

Hosted on pastebin for 1 month.

**Comment by tfox83** [comment]
with pid errors that is local to your system, usually a graphics driver issue.  It is not a mod/modpack issue sorry I am not able to support it.

**Comment by LemADEC** [comment]
Use the jar launcher and update your nVidia graphic driver
