### ISSUE TITLE
Arcane Assembler Missing/Bugged

### ISSUE THREAD

**Issue by RedStoner** [FTBTeam/FTB-Ultimate-Reloaded#150]
* **Modpack Version**:  
1.3.0

* **Issue**: 
Thaumic Energistic's Arcane assembler seems to be missing/bugged. There is a block tied to the mod in JEI "[ERROR] Report to mod dev" i beleive to be the assembler. Without the assembler, auto crafting with Thaumcraft is very difficult. 

* **Link to Log or Crash File Paste**: 
Not a crash.

* **Is it Repeatable?**: Yes. All others I asked on server see same thing.

* **Mod/s Affected**: 
Thaumic Energistics

* **Known Fix**:

**Comment by tfox83** [comment]
This is an issue with the mod and until the mod sorts it my hands are tied.  I will have the fix in as soon as its available.
