### ISSUE TITLE
Thaumcraft and Thaumic Tinker Completion Bug

### ISSUE THREAD

**Issue by Zodsmar** [FTBTeam/FTB-Ultimate-Reloaded#151]
* **Modpack Version**:  1.3.0

* **Issue**: In the Thauminomicon, completing everything has been fine.  I just realized on the right-hand side of the book is Thaumic Tinkerers. I am trying to complete Tome of Knowledge, Transvector Interface and Smokey Quartz. I hit complete and it just says completing. I hear the sound effect of it completing but it just stays at completing. Closes the book and re opening it did nothing still have the complete button for all 3 of them. Weird part is the Essential Funnel completed fine... So I don't know whats going on but I can't complete these 3. Everything else in the book has been completing fine.

* **Link to Log or Crash File Paste**: None
* **Is it Repeatable?**: Has been for me so I would say yes

* **Mod/s Affected**: Thaumcraft and Thaumic Tinkerer

* **Known Fix**:

**Comment by Mirarara** [comment]
Thaumic TInker is in alpha version and those are can't be completed right from the start.

**Comment by JeNaiKe** [comment]
Sadly, it's an unfinishied mod. It changes nothing saying that "it's completed".
Also, you can only get 86% on Arcane Infusion, the two missing features can't be unlockable duo to not being there a world for that purpose.
