### ISSUE TITLE
minecraft

### ISSUE THREAD

**Issue by nuknuk5** [FTBTeam/FTB-Ultimate-Reloaded#153]
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Error details: Attempting to move successful download to C:\Users\hhhhhh\Documents\Curse\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar Cannot create a file when that file already exists. 
Filename on disk: 3e4f-5aa6-fdd6-2320
Path: C:\Users\hhhhhh\AppData\Local\Temp\3e4f-5aa6-fdd6-2320
Exists: false

**Comment by tfox83** [comment]
no idea what your issue is here that you are trying to describe
