### ISSUE TITLE
Enable capacitor from IE to prevent IE coil from stop working

### ISSUE THREAD

**Issue by Mirarara** [FTBTeam/FTB-Ultimate-Reloaded#154]
* **Modpack Version**: 1.4.0
* **Issue**: LV/MV coil from Immersive Engineering sometimes stopped transferring RF to machine or fluxduct from other modpack after a server restart. I need to break a coil and reconnect it for it to work again.

* **Is it Repeatable?**: Sometimes restarting server caused the bug

* **Known Fix**: Connecting the coil to capacitor from IE, then connect it to machine from other modpack is the workaround to this issue. The capacitor is disabled in this modpack though.

**Comment by tfox83** [comment]
Just connect right to a machine or a energy cell, works fine in our testing.  Connecting to a flux duct is not the correct method.

**Comment by tfox83** [comment]
Also to add, you put the connector right on a energy cell on the input side, or a machine, not on a flux duct.  This is due to the FE - RF conversion between the two mods.
