### ISSUE TITLE
[Request] Add a modern alternative to Misc Peripherals.

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#155]
* **Modpack Version**: 1.4.0

* **Issue**: Original FTB Ultimate had Misc Peripherals which is a mod that extended the functionality of ComputerCraft and there's no alternative currently in the pack.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: ComputerCraft

* **Known Fix**: Adding PeripheralsPlusOne and Plethora as they are the modern alternative to Misc Peripherals.

**Comment by NiallDoherty** [comment]
Just a heads up if you add this, the nano bot swarm from peripheralsplusone has the same recipe as iron compound from projectred by default.

**Comment by tfox83** [comment]
Added both and changed nano bot swarm to use refined iron, this will be in 1.6.0
