### ISSUE TITLE
[Request] Adding an item magnet block

### ISSUE THREAD

**Issue by SammyTeee** [FTBTeam/FTB-Ultimate-Reloaded#157]
* **Modpack Version**: 1.4.0 currently, not sure about upgrading my map to the newest version due to problems in the past

* **Issue**: The mod pack lacks a block which can attract item entities in a certain radius.

* **Known Fix**: There is a mod already made called the Better Magnets mod (https://minecraft.curseforge.com/projects/better-magnets) supporting 1.12.2 although, it isn't the exact feature required as its an item which is brought straight to the inventory. 
There is Attractor (https://minecraft.curseforge.com/projects/attractor?gameCategorySlug=mc-mods&projectID=278064) which is a mod which attracts mob entities. Could the code be changed to work for item entities?

**Comment by MacChuck** [comment]
A item pulling block? There's two, the reliquary coin of fortune + pedestal, or the thermal expansion vacuumulator.

**Comment by SammyTeee** [comment]
> A item pulling block? There's two, the reliquary coin of fortune + pedestal, or the thermal expansion vacuumulator.

Wow, not sure how I missed that. Thanks buddy. 
Another question, will I run into problems with upgrading my 1.4.0 map to the current version?
