### ISSUE TITLE
Cant update to 1.4

### ISSUE THREAD

**Issue by Swordlord319** [FTBTeam/FTB-Ultimate-Reloaded#159]
* **Modpack Version**: FTBUltimateReloaded-1.4.0-1.12.2.zip release version

* **Issue**:  When I try to download files to update to 1.4, it says: Cannot find addon dependency 285183, then stops the download

* **Link to Log or Crash File Paste**:  Idk how as this happened on the twitch launcher. 

* **Is it Repeatable?**: Yes ive tried multiple things and times.

**Comment by tfox83** [comment]
Sorry I cannot offer support for the twitch client.  I would suggest a fresh install.
