### ISSUE TITLE
Forestry tubes give incorrect power when in engines

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#16]
* **Modpack Version**: 1.0.1
* **Issue**: 
[Forestry] upgrade tubes for engine have incorrect tooltips, all values are 50% of what they state.
Steps to reproduce:
1) using a soldering iron to add 4 tin tubes to a intricate circuit board (tooltips states +20rf/tic output per tin tube)
>expected 100rf/tic
> actual value stated on electrical engine (from forestry) 60rf/tic
that's up from the base value of 20 rf/tic (exactly half of the expected additional 80rf/tic)

* **Is it Repeatable?**:  yes
* **Mod/s Affected**: Forestry
* **Known Fix**: fix tooltip / change configs?

**Comment by EthernalVoid** [comment]
![2019-02-14_17 38 39](https://user-images.githubusercontent.com/45131452/52802087-7dbc8f00-307f-11e9-8d85-597ac16df3bf.png)

**Comment by tfox83** [comment]
THis will need to be reported to Forestry
