### ISSUE TITLE
Pulverizing ender pearls does not work the same as macerating

### ISSUE THREAD

**Issue by Jessassin** [FTBTeam/FTB-Ultimate-Reloaded#161]
* **Modpack Version**: 1.3.0, however likely affects later releases

* **Issue**: Pulverizing an ender pearl returns ""Ender Pearl Dust" which has an or dictionary entry of "dustEnderPearl" - however macerating an ender pearl creates "Ender Dust" ordict "dustEnder" 
Most crafting recipes appear to accept both items, however it is not possible to craft "void powder" without "dustEnderPearl" 

* **Known Fix**: ensure all recipes will accept both "dustEnder" and "dustEnderPearl" - or ensure both macerator and pulverizer will output the same item "dustEnder" or "dustEnderPearl"

**Comment by tfox83** [comment]
All recipes now accept dustEnder or dustEnderPearl in 1.6.0
