### ISSUE TITLE
Pulverizing obsidian gives four obsidian dust - macerating gives one

### ISSUE THREAD

**Issue by Jessassin** [FTBTeam/FTB-Ultimate-Reloaded#162]
* **Modpack Version**: 1.3.0, future versions likely affected

* **Issue**: 1 block of obsidian becomes 4 obsidian dust in a pulverizer. 1 block only becomes 1 obsidian dust in a macerator. This also affects quartz grindstone, however that may be intended.

* **Is it Repeatable?**: yes

* **Known Fix**: Update macerator recipe to output 4 obsidian dust. Possibly update quartz grindstone to be the same?

**Comment by tfox83** [comment]
At this time adjusting the output of obsidian dust in the macerator causing broken recipes and crashes.  For now please use Pulverizer for max output
