### ISSUE TITLE
Game Crashes On Loading World on Server.

### ISSUE THREAD

**Issue by DocXan** [FTBTeam/FTB-Ultimate-Reloaded#164]
1.4.0 

This started when I was climbing a ladder with my Gravity Gun out, and then my game randomly crashed. This on a server. I tried many times to rejoin the server, and get rid of the item in my hand after reading the crash report, but I can't load in. I have re-installed my pack multiple times as well as updating all my drivers. I can't find a way to fix this. I have even tried it on a different computer but to the same result. 

https://paste.feed-the-beast.com/view/581eed9c : 

I can't get the same issue to occur on anything else, but the crashes persist. 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Looks like something server side, will have to have an admin reset your player file or remove it via a NBT editor.
