### ISSUE TITLE
[AE2] RE-batteries and crafting CPU

### ISSUE THREAD

**Issue by simchanu29** [FTBTeam/FTB-Ultimate-Reloaded#165]
* **Modpack Version**: 1.4.0

* **Issue**: Machines crafted with RE-Batteries such as a Generator can't be crafted with the Crafting CPU from Applied Energistics 2. The crafting CPU stay stuck with the RE-Battery shown as `available`. I did again the pattern several times to be sure I had the right item : each time the pattern was created with a freshly created RE-Battery. Right now it seems i'm not the only one with this [issue](https://www.reddit.com/r/feedthebeast/comments/b2dhci/cannot_get_ae2_autocrafting_to_use_rebatteries_in/).

* **Link to Log or Crash File Paste**: no crash. If there is somewhere some logs I would be interested to know where.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Craft 2, Applied Energistics 2

* **Known Fix**: some people [here](https://www.reddit.com/r/feedthebeast/comments/av0ov3/help_ic2ae2_has_anyone_been_able_to_craft_a/) talk about some bypass methods. I haven't tested that yet.

**Last word** : I know this issue has already been closed (#136 ), but I would like to know if this issue needs to be posted on Applied Energistics 2 repository or Industrial Craft 2 repository.

**Comment by tfox83** [comment]
Feel free to post on both

**Comment by Jessassin** [comment]
I have a workaround for this. It is not ideal, and it does not resolve the source of the issue, but it may get you by in the interim.

Steps:
1. Create 2 crafting recipes. 1 as a "crafting" pattern, and 1 as a "processing" pattern.
2. Place the crafting pattern into an interface, attached only to a single molecular assembler
3. Place the "processing" pattern into the pattern slot of the molecular assembler

Do this for each recipe which uses RE batteries. You will need one interface, one assembler, and two patterns per recipe.

FYI, I have observed the same behavior with other IC2 items - energy crystals behave the same, and I recollect drills do not fill as expected.  I think the same issue may exist for the AE2 cutting knives, but I cannot confirm at this time.

*edit* I wanted to mention a couple workarounds that I have tried - but do not work as others have suggested:

Using JEI to autofill does not resolve the issue
Manually crafting the recipe without JEI does not resolve the issue
Using "ore-dict substitutions" does not work
Using "fully charged" batteries does not work

**Comment by simchanu29** [comment]
Thanks for the workaround, I'm going to try that soon.

For the record, I opened an issue on the AE2 repository :  [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3974](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3974)

And on the IC2 part, I'm still trying to figure out how to post on issue on their bug tracker.

**Comment by simchanu29** [comment]
I think It might be interesting to leave this issue open while this is not solved one way or another. It could prevent creation of other duplicates and inform people coming here to get some information on this issue.

**Comment by Zarkazm** [comment]
I need to try Jessassin's workaround, that sounds a lot more intuitive than the one i've been doing.  My work around has been to create a processing pattern and use it in an interface on an Auto-Crafting Bench from ProjectRed.  The only downside i've come across is with larger crafting jobs, such as something that needs 20+ Lapotron Crystal.  The completed crystals fill up the auto-crafting bench before the Import Bus can remove them, and it locks up the crafting job.  I've been theory crafting some kind of "load balancer" chest system to handle it, but Jessassin's work around sounds better.

**Comment by simchanu29** [comment]
@Jessassin I've tested the workaround, the molecular assembler in `1.4.0` doesn't accept processing pattern, only crafting pattern. The inverse (processing pattern in interface and crafting pattern inside molecular assembler) doesn't seem to work with me : the molecular assembler stay stuck at 0% and doesn't produce the generator.

**Comment by simchanu29** [comment]
Sorry a misclick on close issue.

**Comment by Jessassin** [comment]
Sorry, I may have had that reversed. Processing pattern in interface, crafting pattern in assembler.


I will test and post more descriptive definitions of the workaround. ETA ~1d

**Comment by simchanu29** [comment]
For my solution : I have set up a working setup using an auto workbench from buildcraft (replacing effectively the molecular assembler) with an interface and an import bus.

**Comment by simchanu29** [comment]
@yueh [answered me on the AE2 repository](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3974#issuecomment-477674363). They say they can't reproduce the bug, hence it must be a bug on the modpack. It seems people here have been able to reproduce it so i'm inclined to think he's right.

**Comment by NeariX67** [comment]
> 
> 
> I have a workaround for this. It is not ideal, and it does not resolve the source of the issue, but it may get you by in the interim.
> 
> Steps:
> 
>     1. Create 2 crafting recipes. 1 as a "crafting" pattern, and 1 as a "processing" pattern.
> 
>     2. Place the crafting pattern into an interface, attached only to a single molecular assembler
> 
>     3. Place the "processing" pattern into the pattern slot of the molecular assembler
> 
> 
> Do this for each recipe which uses RE batteries. You will need one interface, one assembler, and two patterns per recipe.
> 
> FYI, I have observed the same behavior with other IC2 items - energy crystals behave the same, and I recollect drills do not fill as expected. I think the same issue may exist for the AE2 cutting knives, but I cannot confirm at this time.
> 
> _edit_ I wanted to mention a couple workarounds that I have tried - but do not work as others have suggested:
> 
> Using JEI to autofill does not resolve the issue
> Manually crafting the recipe without JEI does not resolve the issue
> Using "ore-dict substitutions" does not work
> Using "fully charged" batteries does not work

you got the wrong direction. The crafting pattern has to be in the Molecular Assembler, and the processing pattern in the interface port

**Comment by maxtraxv3** [comment]
it only happend because they stack, if not stacked they can be used, maybe there a config option in ic2 to diable battary stacking? also cant be use in filter if they stack, but out of stacks can be use in filters.

**Comment by Joly0** [comment]
Btw, that also applies to other Items aswell, like the Lapotron Crystal and the Energy Crystal. 
Also, AE2 says, its a Problem within Ic2 and other Mods (Magical Crops doesnt work either, Autocrafting with Infusion Stone or EE2/EE3 whatever, crafting with the Philosophers Stone)
Although, other Mods like Thermal Expansion/Dynamics found a way around, by enabling/disabling NBT or Metadata for their Servos, Retrievers, Filters and other stuff, without that Option, Re-Batteries and other Items of that kind wouldnt work there too.

**Comment by mattiaskagstrom** [comment]
Can confirm that the steps:
1. Create 2 crafting recipes. 1 as a "crafting" pattern, and 1 as a "processing" pattern.

2. Place the "processing" pattern into an interface, attached only to a single molecular assembler

3. Place the  crafting pattern into the pattern slot of the molecular assembler

do work!

**Comment by tfox83** [comment]
Closing due to no fix from the mods as its becoming a finger pointing contest.

**Comment by 34486** [comment]
Sorry its closed, but I have some information instead of it being finger pointing. In IC2 experimetnal 2.8.111 ex112, the problem does not exist, but in 2.8.188-ex112, the problem exists. I am currnelty trying to find out which version it started to happen in. Might take a looong time. I tried with ae2 6.6 and ic2 188 and ae2 6.7, same problem, so its not ae2 that is causing the issue. My evidence says its Applied Energistics, so I am not just going around saying "Oh well they do it this way, so its them!". 

If others would like to help search which ic2 build this issue started in, go ahead, just get a 1.12.2 latest forge version with the latest build of ae2 and start going up from 2.8.111-ex112.

**Comment by gerasimus95** [comment]
> Sorry its closed, but I have some information instead of it being finger pointing. In IC2 experimetnal 2.8.111 ex112, the problem does not exist, but in 2.8.188-ex112, the problem exists. I am currnelty trying to find out which version it started to happen in. Might take a looong time. I tried with ae2 6.6 and ic2 188 and ae2 6.7, same problem, so its not ae2 that is causing the issue. My evidence says its Applied Energistics, so I am not just going around saying "Oh well they do it this way, so its them!".
> 
> If others would like to help search which ic2 build this issue started in, go ahead, just get a 1.12.2 latest forge version with the latest build of ae2 and start going up from 2.8.111-ex112.

have you found the solution?

**Comment by 34486** [comment]
> 
> 
> > Sorry its closed, but I have some information instead of it being finger pointing. In IC2 experimetnal 2.8.111 ex112, the problem does not exist, but in 2.8.188-ex112, the problem exists. I am currnelty trying to find out which version it started to happen in. Might take a looong time. I tried with ae2 6.6 and ic2 188 and ae2 6.7, same problem, so its not ae2 that is causing the issue. My evidence says its Applied Energistics, so I am not just going around saying "Oh well they do it this way, so its them!".
> > If others would like to help search which ic2 build this issue started in, go ahead, just get a 1.12.2 latest forge version with the latest build of ae2 and start going up from 2.8.111-ex112.
> 
> have you found the solution?



There is no solution to it, accept for making individual molecular assemblers, with its own interface on them and having the 2 seperate patterns to craft stuff using those types of items. Unless all these mods come to 1.15.2, or possibly 1.16.x if that would be the next update, (or whatever the hell the new 1.12.2 will be) then this issue will probably continue to exist for a couple years.

**Comment by nt4f04uNd** [comment]
is this only related to RE-batteries and not any other kind of energy capaciting items?

upd: i tested and this is also related to:
* energy crystals
* lapotrons 

but not to advanced re-batteries

**Comment by fxshlein** [comment]
I'm not aware of the particular situation in the modpack, but while playing another pack I just encountered the same issue.

The solution for me was to not use JEI to create the patterns; the Items in the IC2 recipes in JEI all have 1 durability, while the Items that are actually crafted will have 0 durability. After crafting the Item once and updating the patterns with the Item from my inventory instead of JEI everything worked.

Maybe this is the solution here too?

The Items cheated with JEI or obtained in creative mode also have 1 durability btw, which could be a reason this didn't work when the workaround without JEI was tested.
