### ISSUE TITLE
Furnace crash whenever opening furnace?

### ISSUE THREAD

**Issue by leemccormack1** [FTBTeam/FTB-Ultimate-Reloaded#166]
* **Modpack Version**: 1.5.0

* **Issue**: Any time I open a furnace and take something out the game crashes and corrupts the world. I've had this on several modpacks and not just ultimate.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/77dae920

* **Is it Repeatable?**: yes as many times as I want

* **Mod/s Affected**:  N/A

* **Known Fix**:  N/A

**Comment by tfox83** [comment]
This is an incomplete report.  I am not able to assist
