### ISSUE TITLE
Request to add Steam Consumer/Producer

### ISSUE THREAD

**Issue by mcMFG** [FTBTeam/FTB-Ultimate-Reloaded#167]
Modpack version: 1.5.0
 
Issue: Hi, may i request that the Steam Consumer/Produces from Power Converters (or what ever its called in this pack) be added to the modpack?

**Comment by tfox83** [comment]
That is not available in the Energy Converters mod, sorry.

**Comment by mcMFG** [comment]
Will it ever be added? It was in the original pack so yea...

**Comment by tfox83** [comment]
It isn't available in 1.12.2, sorry.  If you would like to make the mod in 1.12.2 and release then I can look at adding it, but at this time it does not exist.
