### ISSUE TITLE
[AE2] No pattern for crystal growth accelerator

### ISSUE THREAD

**Issue by simchanu29** [FTBTeam/FTB-Ultimate-Reloaded#169]
* **Modpack Version**: `1.5.0` (same in `1.4.0`) (on a multiplayer server)

* **Issue**: I can't craft the [Crystal Growth Accelerator](https://ftbwiki.org/Crystal_Growth_Accelerator), the pattern gives nothing in a crafting table
![image](https://user-images.githubusercontent.com/10176249/55183910-2be44a00-5191-11e9-8efd-64590ae05281.png)

* **Link to Log or Crash File Paste**: no crash nor log accessible (as far as I know).

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Applied Energistics 2

* **Known Fix**: None

**Comment by cstalker** [comment]
If i am not mistaken, it is disabled in this pack. since we have no seeds, there is no need.

**Comment by simchanu29** [comment]
Ok, thanks. Is there any way other to generate certus quartz then ?

**Comment by cstalker** [comment]
I use the Laser drills from Industrial Foregoing.

**Comment by tfox83** [comment]
That is disabled from this pack.

**Comment by oligraphics** [comment]
Just in case someone happens to visit this thread I have posted a step by step guide to enable the missing contents manually:
https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/352
