### ISSUE TITLE
Dungeon loot still gives ic2 ingot versions instead of TE ingots

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#17]
* **Modpack Version**: 1.0.1

* **Issue**: dungeon loot still gives other 
![2019-02-14_17 47 43](https://user-images.githubusercontent.com/45131452/52802657-ab560800-3080-11e9-91b9-32e4465e1fd7.png)
![2019-02-14_17 47 33](https://user-images.githubusercontent.com/45131452/52802664-aee98f00-3080-11e9-873f-77ade3719d5d.png)

ingot versions instead of TE ingots

* **Is it Repeatable?**: yes, find any mineshaft cart

* **Mod/s Affected**: modpack

* **Known Fix**: one of the tweakers to change the loot table

**Comment by tfox83** [comment]
That is fine, its OreDict
