### ISSUE TITLE
Compact Solar Arrays ruins pack balance.

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#170]
* **Modpack Version**: 1.5.0

* **Issue**: The pack shouldn't contain Compact Solar Arrays as well as Advanced Solar Panels. They both provide the same functionality yet the panels in Compact Solars are significantly cheaper, thus ruining the balance of the pack. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: Remove Compact Solar Arrays.

**Comment by tfox83** [comment]
The compact solars only out put EU during the day thus balancing them vs the Adv Solars.

**Comment by tfox83** [comment]
And they were in Ultimate which this pack is built after

**Comment by NiallDoherty** [comment]
They weren't, at least not in the latest version. Edit: Just verified, was never in Ultimate...
