### ISSUE TITLE
Incorrect recipes for some items.

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#171]
* **Modpack Version**: 1.5.0

* **Issue**: The Fusion Control Computer and Adjustable SU should be using Tech Reborn Computer Cubes in place of Energy Crystal's in their respective recipes.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: Adjust the recipes accordingly.

**Comment by tfox83** [comment]
Going to leave as is for now
