### ISSUE TITLE
Recipes errors

### ISSUE THREAD

**Issue by KilljackTv** [FTBTeam/FTB-Ultimate-Reloaded#172]
* **Modpack Version**: Version 1.5.0 for server

* **Issue**: 
In the pic you see some of recipes showing a error when i log in this comes up in chat window

* **Link to Log or Crash File Paste**:N/A

* **Is it Repeatable?**:N/A

* **Mod/s Affected**: extrautils2, Tropicraft cocktail and Pineapple, pvj Cracked_coconut, Crafttweaker

* **Known Fix**: 

![Minecraft 1 12 2 ServerVersion 1 5 0](https://user-images.githubusercontent.com/18148661/55282571-9a094800-531c-11e9-89b9-e10adfd5f4f0.PNG)

**Comment by tfox83** [comment]
This modpack does not contain those mods nor a recipes.zs file.  Sorry I am not able to support a user edited version of the pack
