### ISSUE TITLE
Pocket Crafter yeilds Tech Reborn Reinforced Glass; can't be used for Night Vision Goggles

### ISSUE THREAD

**Issue by hitchfred** [FTBTeam/FTB-Ultimate-Reloaded#174]
* **Modpack Version**: 1.50 

* **Issue**: Pocket Crafter from Charset mod yields the Reinforced Glass from Tech Reborn instead of IC2, causing problems when the glass is required in other recipes like the Night Vision Goggles, which only accepts the IC2 glass. Vanilla crafting bench and AE2 terminal give the correct IC2 glass. 

![crafter](https://user-images.githubusercontent.com/31452417/55291947-c5d70d00-53b2-11e9-8f1a-971ed6969aa3.png)
![ic2glass](https://user-images.githubusercontent.com/31452417/55291895-11d58200-53b2-11e9-83f8-f09964108bfd.png)
![techglass](https://user-images.githubusercontent.com/31452417/55291900-1a2dbd00-53b2-11e9-8a8e-6af06d956209.png)

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Charset 

* **Known Fix**:

**Comment by tfox83** [comment]
Please use the vanilla crafting table at this time, its a known issue
