### ISSUE TITLE
Persistent pig sound

### ISSUE THREAD

**Issue by leagris** [FTBTeam/FTB-Ultimate-Reloaded#175]
* **Modpack Version**: 1.5.0

* **Issue**: There is a persistent repeated pig sound even when no pig is around

* **Is it Repeatable?**: Issue still there after restarting the pack

**Comment by DrKrieger1999** [comment]
Hey,

This is caused by the 1st April XD

It will go away until we have the 2nd April ;)

Not a bug^^

**Comment by leagris** [comment]
:fish:
