### ISSUE TITLE
Need for pure fluix crystal in AE2 stuff crafts

### ISSUE THREAD

**Issue by Riki-SZF** [FTBTeam/FTB-Ultimate-Reloaded#176]
* **Modpack Version**: 1.5.0
* **Issue**: Can't craft the wireless connector and the wireless setup kit from AE2 Stuff without pure fluix crystals and I believe those are disabled in this pack.  
* **Mod/s Affected**: AE2 Stuff

**Comment by tfox83** [comment]
That is intended, I just forgot to hide the wireless stuff from AE2 stuff as we decided it felt to OP for this pack.  Will hide those items next update

**Comment by tfox83** [comment]
This is sorted in the next update
