### ISSUE TITLE
Tech Reborn Brass vs Thermal Foundation Brass

### ISSUE THREAD

**Issue by trini** [FTBTeam/FTB-Ultimate-Reloaded#178]
* **Modpack Version**: 1.5

* **Issue**: MachineMuse's Modular Powersuits recipes only accept the anyCopper + Zinc Brass and not the Thermal Foundations anyTin + anyCopper Brass

* **Is it Repeatable?**: Yes

As a work-around at least once you have Zinc the Thermal Foundations Induction Smelter can create the required Brass so further machine duplication isn't required.

**Comment by watlok** [comment]
Lots of compat issues between block types. The easiest workaround is to use chisel to switch it between the two.

**Comment by tfox83** [comment]
Fixed in 1.6.0
