### ISSUE TITLE
Duplicated UU-Matter Recipe

### ISSUE THREAD

**Issue by Hegik** [FTBTeam/FTB-Ultimate-Reloaded#179]
* **Modpack Version**: 1.5.0

* **Issue**: Same IC2 UU-Recipe for more than one item 

* **Link to Log or Crash File Paste**: not relevant

* **Is it Repeatable?**: look for the crafting recipe for Thermal Foundation Copper Ore, and the recipe for Thermal Foundation Tin Ore. It is the same recipe. Only Tin Ore is Craftable, Copper Not. In the Tooltips it says "Recipe by: UniDict" I tried tracking down the config, that does those recipes, but didn't find them. (Also repeatable in 1.4.0)

* **Mod/s Affected**: Thermal Foundation, IC2, Unidict, 

* **Known Fix**: If you find the Config, where the recipes are configured, just move the the first row of UU Matter in the second for one of the two ores. The recipe is not used anywhere else.

**Comment by simchanu29** [comment]
I confirm this bug. There is the same bug for gold ore and iron ore.

**Comment by NiallDoherty** [comment]
Mass fabricator should be disabled in favour of the matter fabricator, as it was in Ultimate 1.4.7.

**Comment by tfox83** [comment]
Mass Fab has been disabled to bring it more in line with Ultimate from 1.4

**Comment by Gamer1120** [comment]
This bug is also present in version 1.7.1. Should I make a new issue for it, or can this one be re-opened?
