### ISSUE TITLE
Kinetic Generators

### ISSUE THREAD

**Issue by itsNeutron** [FTBTeam/FTB-Ultimate-Reloaded#18]
* **Modpack Version**: 1.0.1
* **Issue**: I can't craft the kinetic generator of Immersive Engineering because the recipe, copper coils are uncraftable

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Immersive Engineering/Project Red

* **Known Fix**:  None atm

**Comment by EthernalVoid** [comment]
Kinetic dynamo's are craftable.

**Comment by itsNeutron** [comment]
I can't, I see the cooper coils which need a draw plate

**Comment by EthernalVoid** [comment]
You can make them using a diamond saw from forge microblocks even if the recipe doesn't show in JEI.
placing the saw above a diamond block, same for the iron.
That should either be added as a recipe at least..... @FTB

**Comment by itsNeutron** [comment]
I just tryied doing the process with the diamond saw and a block of iron and one of diamond, nothing happens.
http://prntscr.com/ml5178

**Comment by EthernalVoid** [comment]
saw needs to be above the block

**Comment by EthernalVoid** [comment]
Expensive as hell for an early game item.......

**Comment by itsNeutron** [comment]
Thanks, It should be added in recipes btw...
