### ISSUE TITLE
Engines Duplicate Redstone Torches

### ISSUE THREAD

**Issue by SammyTeee** [FTBTeam/FTB-Ultimate-Reloaded#180]
* **Modpack Version**: 1.4.0 

* **Issue**: When placing an engine (in my case, the Electrical Engine and the Fluix Transformer and powering it with a redstone torch, you can shift click the engine to duplicate the redstone torch. 

* **Is it Repeatable?**: Yes

**Comment by tfox83** [comment]
Fixed in 1.6.0
