### ISSUE TITLE
Pocket Crafting Table will crash game upon shift-clicking crafted items

### ISSUE THREAD

**Issue by SuperStarSam** [FTBTeam/FTB-Ultimate-Reloaded#182]
* **Modpack Version**: Version 1.5

* **Issue**: Using the Pocket Crafting Table works when single clicking but will crash upon crafting through shift clicking or right clicking.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in latest update
