### ISSUE TITLE
Plant Interactor isn't working properly

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#183]
* **Modpack Version**: 1.5
* **Issue**: The Plant Interactor won't harvest the plant with the rightklick function like a Player would do and it's supposed to do. Instead it will harvest the plant infinite.

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: Just place a Plant interactor and put a grown wheat plant infornt of it and let it do it's thing

* **Mod/s Affected**: Industrial Foregoing

* **Known Fix**: ///

**Comment by tfox83** [comment]
Fixed in latest udpate
