### ISSUE TITLE
EVERY item dupe and Mining Laser griefing.

### ISSUE THREAD

**Issue by JeNaiKe** [FTBTeam/FTB-Ultimate-Reloaded#185]
* **Modpack Version**: 1.5.0

* **Issue**: 

1. Item Duplication
2. Mining Laser Griefing

* **Link to Log or Crash File Paste**: none.

* **Is it Repeatable?**: yes.
1. 
Get atleast 2 Black Hole Unit's and 1 Black Hole Controler. Place the Black Hole Units inside of it, then in the second slot of the first row place the item, and it will be duplicated to the down slot.

2.
Someone without any permission in that claimed area can destroy with the mining laser.

* **Mod/s Affected**:
1. Industrial Foregoing
2. IndustrialCraft 2

* **Known Fix**: none.

I can make a video if requested.

**Comment by tfox83** [comment]
Fixed in 1.6.0
