### ISSUE TITLE
GraviTool wrench mode doesn't work with Tech Reborn

### ISSUE THREAD

**Issue by trini** [FTBTeam/FTB-Ultimate-Reloaded#186]
* **Modpack Version**: 1.5

* **Issue**: In wrench mode the GraviTool doesn't work (doens't rotate / pick-up) Tech Reborn items like the Charge-o-mat and other IC2 items like the Quantum Tank

* **Is it Repeatable?**: Yes

**Comment by tfox83** [comment]
@modmuss50 Would you mind taking a look when you can, if this is something you can fix, thanks

**Comment by modmuss50** [comment]
Yes, this should be possible to add.
