### ISSUE TITLE
MPS Resetting Thermal Suite Dynamos to Steam Dynamos when broken with Power Fist AOE

### ISSUE THREAD

**Issue by BURN447** [FTBTeam/FTB-Ultimate-Reloaded#187]
* **Modpack Version**: 
1.5.0-1.12.2
* **Issue**: 
When breaking blocks with the Modular Powersuits Power Fist in Area of Effect Mode, it currently resets Thermal Expansion Dynamos to a base steam dynamo, no matter what upgrades it began with.

Here is a clip of the behavior.

https://clips.twitch.tv/ExquisiteCrunchyKoupreyMoreCowbell

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Modular Powersuits
Thermal Suite

**Comment by tfox83** [comment]
Fixed in 1.6.0
