### ISSUE TITLE
Unable to craft "Essence of Scournful Oblivion"

### ISSUE THREAD

**Issue by Hedkracka** [FTBTeam/FTB-Ultimate-Reloaded#189]
* **Modpack Version**: 1.5.0

* **Issue**: Unable to craft "Essence of Scournful Oblivion" for Oblivion frames (recipe shows in NEI/JEI)Tried crafting both vanilla and AE2 methods

* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**: yeah
* **Mod/s Affected**: n/a

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 1.6.0
