### ISSUE TITLE
Game Crash on Loading World Solved

### ISSUE THREAD

**Issue by BeNiNN** [FTBTeam/FTB-Ultimate-Reloaded#19]
Hello when i try to Load the world that i created the game Crashes when i first see the player's hand
Please help me i was so excited to play this mod pack and i really want to play it as soon as possible , Thank you for the help in advance

* **Modpack Version**: FTBUltimateReloaded-1.0.1-1.12.2

* **Issue**: Game Crash when Loading the World

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/c14704aa

* **Is it Repeatable?**: Yes i can't play at all i was so excited to play this ModPack but it just keep crashing on me

* **Mod/s Affected**: i really don't know

* **Known Fix**:  updating the graphics driver

**Comment by modmuss50** [comment]
We need the crash report please.

**Comment by BeNiNN** [comment]
isn't that what i posted ? * https://paste.feed-the-beast.com/view/c14704aa

**Comment by modmuss50** [comment]
No you edited, the issue after I had seen it.

Seems to be an issue with Thermal Expansion's jei handling.

**Comment by BeNiNN** [comment]
so what should i do please :( ?

**Comment by BeNiNN** [comment]
PLEASE HELP :(

**Comment by LemADEC** [comment]
Update your Java, use the Jar launcher and don't allocate too much RAM to the game (8 GB allocated vs 4 GB recommended).

**Comment by BeNiNN** [comment]
Still not working :( downloaded latest java update and allocated only 7GB 

didn't know how to use the Jar launcher tho i've been searching for it for like an hour

this is the Crash log after those changes https://paste.feed-the-beast.com/view/327781b2

**Comment by BeNiNN** [comment]
Hope someone can help and thanks to anyone that tried

**Comment by tfox83** [comment]
I would suggest a clean install of the modpack.  I am not able to reproduce any of these issues.

**Comment by BeNiNN** [comment]
i did try to install a clean version i also tried deleting it and installing the 1.0.0(beta) version but still it didn't work

**Comment by BeNiNN** [comment]
please let me know if there's anything i can do that will assist you in helping me even if u want to access my computer via TeamViewer and thanks

**Comment by BeNiNN** [comment]
and i was wondering is there anyway i can download the modpack other than through The twitch app and thanks

**Comment by LemADEC** [comment]
Twitch launcher options  > Minecraft > Launching method > Jar launcher

**Comment by BeNiNN** [comment]
Done that and still no use :(

**Comment by BeNiNN** [comment]
the problem was fixed by updating the graphics driver
