### ISSUE TITLE
crafting issues in techreborn

### ISSUE THREAD

**Issue by NocturnalScream** [FTBTeam/FTB-Ultimate-Reloaded#190]
* **Modpack Version**: 1.5

* **Issue**: Crafting recipe in Industrial Centrifuge and Distiliation Tower are broken since they use the techreborn rubber wood which is inaccessible in this pack ( bug is known in the git of the techreborn dev team). Crafting recipe for diesel cells in the distillation tower wont work with buildcraft oil (also a bug and known to the techreborn team)

* **Is it Repeatable?**: YES

* **Mod/s Affected**: Techreborn (in conjungtion with ic2 and bc)

* **Known Fix**: Minetweaker can fix this, add this to the techreborn.zs

#fix carbon cell recipe to use ic2 rubberlog
mods.techreborn.centrifuge.removeRecipe(<techreborn:part:31> * 8);
mods.techreborn.centrifuge.addRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidcarbon", Amount: 1000}}) * 4, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidmethane", Amount: 1000}}), <ic2:misc_resource:4> * 8, null, <ic2:rubber_wood> * 16, <techreborn:dynamiccell> * 5, 5000, 5);

#fix oil cell of bc not being accepted
mods.techreborn.distillationTower.addRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidsulfuricacid", Amount: 1000}}) * 16, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluiddiesel", Amount: 1000}}) * 16, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidglyceryl", Amount: 1000}}), null, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}) * 16, <techreborn:dynamiccell> * 17, 1400, 13);

dont remove the standard oil recipe for techreborn as it would render asnother recipe useless in which you can create oil cells

**Comment by NocturnalScream** [comment]
forgot to mention that the recipe for nitrofuel is also affected since it wont accept bc oil either in the chemical reactor. Havent wrote a fix for this as of yet.

**Comment by tfox83** [comment]
Fixed in 1.6.0
