### ISSUE TITLE
Tech Reborn Auto Crafting Table Server Issue

### ISSUE THREAD

**Issue by GrimX145** [FTBTeam/FTB-Ultimate-Reloaded#191]
* **Modpack Version**: 1.5.0

* **Issue**: [SERVER] When crafting IC2 Generator, need to restart server to craft again
When trying to craft IC2 generator with Tech Reborn Auto Crafting table (becaus can't be craft with AE2) it craft up to one stack and after it's impossible to craft again the recipe except if we restart the server. That affect all the server becaus, after using Auto Crafting Table, we are also unable to craft the item in a standard crafting table until we restart the server. It affect all the items we crafted in a Auto Crafting table.

* **Is it Repeatable?**: Yes after server restart

* **Mod/s Affected**: Techreborn (All mod with craftable item)

* **Known Fix**: Restart server every time we craft one.

**Comment by tfox83** [comment]
At this time crafting items with a NBT data from IC2 is known to be an issue.  Please you vanilla crafting table for those items.  If a fix is ever found I will get it in next update
