### ISSUE TITLE
Railcraft void chest client crash

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#192]
* **Modpack Version**: 1.5.0

* **Issue**: I teleport to my friends base through a portal gun portal (or tp command so it's not the portal gun mod at all) and then my client crashes.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/cd461af1

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Railcraft

**Comment by tfox83** [comment]
Am not able to reproduce this at this time using the latest beta so it may of been fixed.
