### ISSUE TITLE
FFS Tanks randomly 'breaking'

### ISSUE THREAD

**Issue by AnyTimeTraveler** [FTBTeam/FTB-Ultimate-Reloaded#193]
* **Modpack Version**: 1.5.0

* **Issue**: FFS Tanks randomly 'breaking' (valves turning red and having to be right-clicked to re-form the tank).
Randomly, because I can't find a pattern. I did not observe it happening, just see it when returning to the base through portals or on foot.

* **Link to Log or Crash File Paste**: 
Client-Log when it happens on the server: https://paste.feed-the-beast.com/view/5ae967ab
Client-Log when reproducing on Client: https://paste.feed-the-beast.com/view/4c2772bf
Test world save where I reproduced it: https://drive.google.com/open?id=1bkwqbtk8VH-egTsBsg6xjYqqIfNKPCjr

* **Is it Repeatable?**: Yes, repeated in multi- and singleplayer (world save attatched).

**Instructions to reproduce:**
1. Open test world on client
2. Go into the Mining-World-Portal
3. Return to the Overworld
4. (Sometimes) see the tank with red valves, marking it disabled

Sometimes, I had to redo step 3 and 4 for up to 8 times, before the tank de-forms.

* **Mod/s Affected**: Fancy Fluid Storage (and maybe Aroma1997's Dimensional World) 

* **Known Fix**: None, other than manually clicking on the tank to re-form it.

**Comment by tfox83** [comment]
This is fixed in the next update
