### ISSUE TITLE
CraftTweaker Recipes Don't Work while on server

### ISSUE THREAD

**Issue by KIliuchok** [FTBTeam/FTB-Ultimate-Reloaded#194]
* **Modpack Version**: 1.5.0
* **Issue**: Some CraftTweaker Recipies don't work on a crafting table on the server. For example, you simply cannot craft sunnarium, advanced lappack, blast compressor, none of AE2, etc while it is appearing with correct recipe in JEI. Skipping crafttweaker files while the server is preinitializing. (Look for the lines 3-18 on log file)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/5b5694d6

* **Is it Repeatable?**: Every time we launch the official server from ftb website

* **Mod/s Affected**: CraftTweaker2 1.12-4.1.15

* **Known Fix**: No known fix as far as I searched

**Comment by tfox83** [comment]
Please reinstall the server, we are not having any issues across multiple test servers
