### ISSUE TITLE
Adding Missing Blocks (such as for IE and Buildcraft)

### ISSUE THREAD

**Issue by turtleguy42** [FTBTeam/FTB-Ultimate-Reloaded#195]
* **Modpack Version**: 1.5.0

* **Issue**: I am trying to unlock the missing features from mods like IE and Buildcraft. Essentially, I really like the mods in this pack and the idea that "1 block shouldn't do it all" but I am now at the endgame and would like to play with the mods more in depth such as playing with robots and the turrets from the portal gun mod. Is there a way to remove the restrictions?

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes

* **Mod/s Affected**: all with missing parts

* **Known Fix**: Heard of removing script conditions but unsure

**Comment by tfox83** [comment]
These are not included with the pack, sorry.
