### ISSUE TITLE
Charset Client Crash

### ISSUE THREAD

**Issue by Mauser3** [FTBTeam/FTB-Ultimate-Reloaded#196]
* **Modpack Version**: FTB Ultimate Reloaded Version 1.5.0 (unmodified, no additional mods installed)

* **Issue**: Client crash while using portable crafting table from Charset. With full inventory shift + left click on random item in the 3x3 crafting grid leads to client crash.

* **Is it Repeatable?**: yes, 5 out of 5 times yet

* **Mod/s Affected**: Charset-Crafting-0.5.5.0

* **Known Fix**: item clicked on should switch to an empty inventory place or event should be ignored

Best regards, Mauser3

**Comment by tfox83** [comment]
This should be fixed in 1.6.0+
