### ISSUE TITLE
Missing distillation tower recipe

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#197]
* **Modpack Version**: 1.5.0

* **Issue**: There should be a recipe for 16 biomass cells -> 8 ethanol cells + 8 empty cells in the distillation tower from tech reborn.

(It would be awesome if we could somehow submit PR's for a modpack... just a thought.)

**Comment by tfox83** [comment]
@modmuss50 I can confirm no such recipe exists

**Comment by tfox83** [comment]
Also we tried allowing PRs, its was too much and took too long to sort through the 98% PRs that were not correct.

**Comment by NiallDoherty** [comment]
Ah fair enough

**Comment by NiallDoherty** [comment]
I'll just leave this here.

#Add biomass to ethanol recipe to distillation tower.
mods.techreborn.distillationTower.addRecipe(
<techreborn:dynamiccell:0>.withTag({Fluid:{FluidName:"bio.ethanol",Amount:1000}}) * 8,
null, null,
<techreborn:dynamiccell:0> * 8,
<techreborn:dynamiccell:0>.withTag({Fluid:{FluidName:"biomass",Amount:1000}}) * 16,
null, 400, 32);

**Comment by tfox83** [comment]
added in next update
