### ISSUE TITLE
[Request] secretrooms mod missing?

### ISSUE THREAD

**Issue by zymex22** [FTBTeam/FTB-Ultimate-Reloaded#198]
ultimate had SecretRooms 
mod but reloaded dosent.

the mod have been updated/ported ? to 1.12 maybe it should be added again:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2869307-secretroomsmod-1-12-2
or
https://minecraft.curseforge.com/projects/secretroomsmod

MalisisDoors would also be lovely but they were not in original ultimate =)

**Comment by tfox83** [comment]
Was performance issues during our testing, so it was removed.
