### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Ultimate-Reloaded#2]
* **Modpack Version**: 1.0.0

* **Issue**: Issue Tracker is set to ftbone gitlab

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: Change the link

**Comment by DinnerBeef** [comment]
GG tfox GG

**Comment by tfox83** [comment]
MY BAD.  This is fixed in dev, thanks for the heads up.  This is what I get for rushing yesterday :)

**Comment by tfox83** [comment]
Update 1.0.1 released
