### ISSUE TITLE
Powered rolling machine will not accept RF power

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#20]
* **Modpack Version**: 1.0.1

* **Issue**: [Railcraft] powered rolling machine will not accept power, wiki states it should take RF
http://railcraft.info/wiki/device:rolling_machine

* **Is it Repeatable?**: yes
Try to power the powered rolling machine with [TE] fluxducts or [BC] golden kinesis pipes

* **Mod/s Affected**: Railcraft

* **Known Fix**: configs?

**Comment by tfox83** [comment]
Thats cause it uses Railcraft Charge power, use one of RC charge produces to convert from EU or RF
