### ISSUE TITLE
Strange outline over blocks

### ISSUE THREAD

**Issue by MarkofJoe** [FTBTeam/FTB-Ultimate-Reloaded#201]
* **Modpack Version**: 1.5.0

* **Issue**: As you can see from the examples below, this issue I found the other day was this odd outline that appears on not only movable objects like chests and crank (This one's really obvious) but all blocks as well. At the time I was just putting down a new pulverizer, steam dynamo and table + scribing tool in my base when I noticed it. It only appears when I look North-West at the blocks and only in certain chunks. Otherwise I don't know how to recreate this in a new world or what mods or even vanilla minecraft might be at fault here.

Originally I had Botania added to the pack, but removed it as per the policy here and it still persists. Looking online I could find two instances of other's having this issue with no fixes listed. It's not game breaking obviously but I'd like to try and figure out if I pressed something so that if I end up making a new world it doesn't just happen again.

![2019-04-28_08 59 23](https://user-images.githubusercontent.com/50066678/56864887-ec7a6a80-6995-11e9-9753-5c30d1394749.png)
![2019-04-28_09 24 29](https://user-images.githubusercontent.com/50066678/56865040-87277900-6997-11e9-8945-48e6f9385d7a.png)

EDIT: It seems the wooden crank from AE2 is the culprit! Removing it seems to have all the extra lines disappear, still weird that it's causing this but at least I figured out what's causing my problem. It's strange though since I didn't notice any problems when I first placed it, but it's definitely what's causing the problems.

**Comment by tfox83** [comment]
Weird, I am not able to reproduce this, glad you got it sorted for yourself
