### ISSUE TITLE
Immersive Engineering (Kinetic Dynamo not working)

### ISSUE THREAD

**Issue by Fluzik** [FTBTeam/FTB-Ultimate-Reloaded#203]
* **Modpack Version**: 1.6.0 

* **Issue**: I had gone through the process of starting immersive engineering and created a fully functioning wind mil. I consulted every forum and tutorial to properly get it to work but the power will not transfer from the Kinetic Dynamo to the copper wire, connectors, and relays. I have tried just about any alternatives the pack offers but couldn't get it to budge.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Immersive Engineering

**Comment by tfox83** [comment]
I cannot reproduce as they work fine for me in testing.
