### ISSUE TITLE
modpack version 1.6.0

### ISSUE THREAD

**Issue by Chopineln** [FTBTeam/FTB-Ultimate-Reloaded#204]
* **Modpack Version**: 
1.6.0
* **Issue**: 
My game crash some second after i join a world
* **Link to Log or Crash File Paste**: 
where to find this?
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Need more info and a crash report.
