### ISSUE TITLE
Logging out in Age Glitches Client (/tpx 0 or they are stuck on loading screen) / Instability

### ISSUE THREAD

**Issue by sirzuidy** [FTBTeam/FTB-Ultimate-Reloaded#206]
Hello. Huge, huge fan since the original FTB Ultimate. So glad to be playing this remastered classic with the PERFECT amount of changes from the original that seem to make the progression much more rewarding and a bit more challenging.

I have added the latest version of the Mystcraft 1.12 mod through the FTB legacy launcher. I am not sure if this is what is causing the conflict - I could not find any proper documentation on which exact version of Mystcraft was "tested to be compatible without crashes" like the last line of the main page for this modpack on the FTB website does. If in fact it was tested to be compatible and not crash, why have I been having so many strange issues with it?
-->

* **Modpack Version**: 1.5.0

* **Issue**: No matter what I do, if anybody on my server logs out in a Mystcraft age, they cannot log back into the server without /tpx command being used to move dimensions. They can click "connect" and make a client connection, but only see the dirt loading screen. From here, if teleported via /tpx back to another dimension, they receive a "Fatal Error" message, and are able to rejoin once they log back in.

Likewise, people also have crashed the server entirely on at least one occasion when generating a random age. Some ages cannot be entered at all without crashing upon arriving, and thus, the log out glitch from the above paragraph happens again. And, likewise, a random crash due to some other instability whilst in a Mystcraft dimension causes the same cycle to happen.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/7ed599ac (Note, the final line(s) which contain "Fatal Error" are the lines RIGHT upon me typing /tpx (name) out of the "glitched" Mystcraft age and back to the overworld or elsewhere. I hope this paste will do, it was not accepting the entirety of the file as input, for valid reasons I would hope, haha.

* **Is it Repeatable?**: Yes, the log out issue is ever present, and the random bits of instability seem inexplicable... am I using improper versions of something? Would updating the server to FTB Ultimate Reloaded 1.6.0 change any of this?

* **Mod/s Affected**: Mystcraft mystcraft-1.12.2-0.13.7.03.jar

* **Known Fix**: /tpx command when the client is in the weird connected but loading in dirt `screen`

**Comment by tfox83** [comment]
Sorry I cannot support mystcraft, as things have changed since the early testing over 4 months ago.  I suggest maybe posting a crash report on the mystcraft issue tracker.
