### ISSUE TITLE
Printed Calculation Circuit recipe isn't working? 

### ISSUE THREAD

**Issue by RiC0MD** [FTBTeam/FTB-Ultimate-Reloaded#207]
* **Modpack Version**: 1.6.0

* **Issue**: Printed Calculation Circuit recipe isn't working? 

* **Link to Log or Crash File Paste**: No errors reported client or server side
* **Is it Repeatable?**: Yes, JEI shows the two types (diff knives), tried both, multiple crafting tables, etc, cannot seem to be able to complete the craft.

* **Mod/s Affected**: AE2
* **Known Fix**: None that I'm aware of at this time.

**Comment by tfox83** [comment]
please try a fresh install of all scripts, on server and client.  These work fine for me in testing
