### ISSUE TITLE
Bee's Not Producing

### ISSUE THREAD

**Issue by ConvincedGaming** [FTBTeam/FTB-Ultimate-Reloaded#209]
* **Modpack Version**: 1..6.0

* **Issue**: Binnie's Extra Bees, bees like Emerald, Diamond, Ruby, Cinnabar do not produce any special combs that they should be.  Not sure if this is a config option and I know I'm not doing anything wrong with the bees, that I know of.

* **Is it Repeatable?**: Yes, probably the same with more specially produce bees

* **Mod/s Affected**: Binne's Extra Bees

* **Known Fix**: no idea

**Comment by tfox83** [comment]
Cannot reproduce, in our testing we received combs from those bees on a rare basis.
