### ISSUE TITLE
Cannot start Career Bees

### ISSUE THREAD

**Issue by ConvincedGaming** [FTBTeam/FTB-Ultimate-Reloaded#210]
* **Modpack Version**: 1.6.0
* **Issue**: Cannot start into career bees, properly setup the apiary over a bookshelf, used the right bees and despite being 100%, did not get the bee to start.

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Career Bees

* **Known Fix**: NA

**Comment by NiallDoherty** [comment]
Career bees isn't in the pack... unless you added it.

**Comment by tfox83** [comment]
There is no career bees
