### ISSUE TITLE
Game Crashing when joining server

### ISSUE THREAD

**Issue by JeNaiKe** [FTBTeam/FTB-Ultimate-Reloaded#212]
* **Modpack Version**:  1.5.0

* **Issue**: I was flying with the thuamcraft gaunglet and broke an bee hive with magic 'break', I usually do this, but this time it crashed the game and since then I'm unable to enter the server,

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2fb4fe4e

* **Is it Repeatable?**: I don't know. I was flying, with the gaunglet and spammed the magic "break V silk touch" on an Hive

* **Mod/s Affected**: Don't know

* **Known Fix**: none

**Comment by JeNaiKe** [comment]
Update:
* **Issue**: I actually broke an Forestry leave, "Hill Cherry Leaves" The block is in my inventory.

* **Is it Repetable**: Yes. Breaking the "Hill Cherry Leave" with Caster Gaunglet, Break[Silk Touch].

* **Mod Affected**: Forestry.

* **Known Fix**: Using NBTExplorer I removed it from my inventory.

**Comment by tfox83** [comment]
I was not able to reproduce this, glad you were able to fix your inventory.
