### ISSUE TITLE
Waiting for server bug

### ISSUE THREAD

**Issue by Riotzz** [FTBTeam/FTB-Ultimate-Reloaded#213]
* **Modpack Version**: 1.6.0

* **Issue**:Server is unresponsive when I join the server and it times me out 

* **Link to Log or Crash File Paste* *: https://paste.feed-the-beast.com/view/87df8b89

* **Is it Repeatable?**: Every time I start the server and join it.

**Comment by tfox83** [comment]
Please try a fresh world, I am not able to reproduce this
