### ISSUE TITLE
10K Coolant Cell Recipe

### ISSUE THREAD

**Issue by toffaste1337** [FTBTeam/FTB-Ultimate-Reloaded#214]
* **Modpack Version**: FTB Ultimate Reloaded 1.6.0(Release)

* **Issue**: When crafting a 10K Coolant Cell from IC2, with a portable tank from Thermal Expansion, the tank is not drained, rather it disappears after crafting only one.

* **Link to Log or Crash File Paste**: None.

* **Is it Repeatable?**: Yes. Just craft the coolant cell.

* **Mod/s Affected**: IC2, Thermal Expansion.

* **Known Fix**: Don't use the portable tank to craft coolant cells.

**Comment by tfox83** [comment]
Known bug with no fix, please do not use portable tanks for crafting.
