### ISSUE TITLE
Missing Multiple Recipies involving Aluminium

### ISSUE THREAD

**Issue by ZoomShadow40** [FTBTeam/FTB-Ultimate-Reloaded#215]
* **Modpack Version**: FTB Ultimate Reloaded 1.6.0(Release)

* **Issue**: Missing Multiple Recipies involving Aluminum

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: Only One set of recipes from specific mods are used

* **Mod/s Affected**: Thermal Foundation, Tech Reborn

**Comment by tfox83** [comment]
That is intended.

**Comment by meganleighwoulffe** [comment]
> 
> 
> That is intended.

I hate to necro a thread like this, but can we get a better reason than that it was intended? There seems to be no way to turn pulverized aluminum into ingots besides high level machinery. It makes no sense.
