### ISSUE TITLE
Multiple Duplicated, Extra, and Missing Recipes

### ISSUE THREAD

**Issue by ZoomShadow40** [FTBTeam/FTB-Ultimate-Reloaded#216]
Throughout this Pack, I have found multiple recipes for both crafting and machines are either duplicated, missing or extra unneeded recipes. The list here is what I have currently found, If I have found more I will post it here.

* **Modpack Version**: FTB Ultimate Reloaded 1.6.0 (Release)

* **Issue**: Duplicated Crafting Recipes: Advanced Lappack (x3), Diamond Nuggets (One is Tech Reborn and the other Thermal Foundation), Iron Fence (Duplicated one is the same but only outputs one Iron Fence from Tech Reborn), Tin Nuggets (One is Railcraft and the other is Thermal Foundation), Aluminum Block (One is Thermal Foundation and the other is Tech Reborn), Block of Nickel and Nickel Nuggets (One is Railcraft and the other is Thermal Foundation), Void Powder, Block of Bronze and Bronze Nuggets (One is Railcraft and the other is Thermal Foundation), Advanced Machine Frame (One is IC2 and the other is Tech Reborn)
Extra Crafting Recipes: Advanced Lappack
Extra Machine Recipes: Pulverizer: Nothing to Diamond (x5), Nothing to 3x Diamond, Nothing to 2x Sawdust (x3), Nothing to 2x Diamond
Missing Recipies: Fluid Transposer: All recipes for the Fluid Transposer are in the pack but they are unviewable.
Iridium Shard: This Item is new to me but no recipes are shown for it 

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: Yes (Craftable)

* **Mod/s Affected**: IC2, Gravitation Suite, CraftTweeker2, Thermal Foundation, Tech Reborn, Railcraft, UniDict

**Comment by tfox83** [comment]
This is intended
