### ISSUE TITLE
Game Crash while loading CraftTweaker2

### ISSUE THREAD

**Issue by TGavGav91** [FTBTeam/FTB-Ultimate-Reloaded#217]
* **Modpack Version**: 1.12.2
* **Issue**: Game Crash while loading CraftTweaker2

* **Link to Log or Crash File Paste**: 
[crash-2019-05-10_13.58.25-client.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3166368/crash-2019-05-10_13.58.25-client.txt)

* **Is it Repeatable?**: yes.
* **Mod/s Affected**: CraftTweaker2

* **Known Fix**:

**Comment by TGavGav91** [comment]
dont know why these fckn twitch app do not want to download a newer version....

**Comment by TGavGav91** [comment]
Sorry Modpack Version is 1.6.0

**Comment by tfox83** [comment]
Please post the crash report on pastebin, I am not downloading files.
