### ISSUE TITLE
No way to make blizz powder

### ISSUE THREAD

**Issue by drpertree** [FTBTeam/FTB-Ultimate-Reloaded#218]
* **Modpack Version**: 1.6

* **Issue**: No cold biomes except Extreme Hills within 3000 block radius found to spawn a blizz.  Looked up alternative way to make blizz powder and saw combining a snowball with destabilized redstone in a fluid transposer was a possibility.  This do not work either.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: I have 8 snowballs and a full fluid transposer of destabilized redstone.  I have flown 3000 blocks in every direction in a complete circle around my base and the only snow biome was extreme hills which spawns basalts not blizz.

* **Mod/s Affected**: 

* **Known Fix**: None

**Comment by NiallDoherty** [comment]
You need essence of knowledge, not destabilized redstone in the fluid transposer. https://teamcofh.com/docs/thermal-foundation/blizz-powder/
