### ISSUE TITLE
Crashing at world startup

### ISSUE THREAD

**Issue by Dexdook** [FTBTeam/FTB-Ultimate-Reloaded#219]
* **Modpack Version**: FTB Ultimate Reloaded

* **Issue**: I go to start up, or create a world, and the moment it loads into the world, it shows the HUD for a second, and then, the game closes down and it gives me an "Game crash! Unexpected Error occured" 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f85163d1
* **Is it Repeatable?**: It happens every time the game is restarted, or PC is restarted with no exception.

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by tfox83** [comment]
Cannot reproduce, please try a fresh install and be sure you are using latest version of Java 8.  This is not modpack related
