### ISSUE TITLE
Projectred blockplacer places "ghost" blocks when powered by a projectred timer and placing a projectred frame

### ISSUE THREAD

**Issue by Latiang** [FTBTeam/FTB-Ultimate-Reloaded#220]
* **Modpack Version**: 1.6.0

* **Issue**:  The issue involves blockplacers (projectred), timers (projectred), and blocks that when placed are a forge multipart. When a blockplacer is powered by a projectred timer to place a Forge multipart block such as a cover, a project red frame or a project red gate (not, and, timer, etc) it will use one item and place a "ghost" block which appears to just be part of the mesh and not actually added to the chunk. Reloading the map, placing a block in the ghost block or just waiting will cause the block to disapear. Once there is a "ghost" block the second activation of the blockplacer will place an actual block. This behaviour is not seen if a vanilla repeater is placed between the blockplacer and the timer. I encountered this issue whilst playing on my laptop with a core i5-8250u processo, integrated graphics, and 8gb of ram which becomes quite toasty. It is possible that the issue does not happen on a slightly more powerful computer but I have not tested that scenario as I currently do not have access to my desktop.

* **Link to Log or Crash File Paste**: There is no crash logg due to the lack of a crash. Here is a save file where the behaviour can be seen though! https://drive.google.com/drive/folders/1BY_HxSui01zUTLouV7AwaExle0pdTn_c?usp=sharing

* **Is it Repeatable?**: Yes, it is repeatable

* **Mod/s Affected**: projectred 4.9.1.82; forge multipart cbe 2.6.2.81 (modversions taken from the twitch client)

* **Known Fix**:

**Comment by tfox83** [comment]
This is a known issue.  A workaround as I doubt we will see a fix is do not use multiparts in placers at this time.
