### ISSUE TITLE
Looking at a leadstone fluxduct while holding a stone cover crashes 100% of the time

### ISSUE THREAD

**Issue by renhammer** [FTBTeam/FTB-Ultimate-Reloaded#221]
* **Modpack Version**: 1.6.0-1.12.2

* **Issue**: When looking at a leadstone fluxduct with a thermal dynamics stone cover in your hand, or try to switch to a stone cover while looking at a leadstone fluxduct, crashes 100% of the time. As soon as your mouse hovers over the block with the leadstone fluxduct the game will instantly crash with the error below.

* **Link to Log or Crash File Paste**: 
#1 https://paste.feed-the-beast.com/view/1bcf9b78
#2 https://paste.feed-the-beast.com/view/bc94f535

https://imgur.com/a/MbMavYj

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Might be Thermal Dynamics

* **Known Fix**: Don't do it :) 👍

**Comment by beanorx** [comment]
yup, just reproduced this: itemduct + wood planks cover.   should I drop my crash log?

**Comment by renhammer** [comment]
Is your wood planks cover a Forge Microblocks wood planks cover? I tested that and it seems ok, but I had issues constantly with the Thermal Dynamics covers. I just tested leadstone fluxduct plus thermal dynamics wood planks cover and also got a crash, so it seems pretty easily repeatable.

**Comment by tfox83** [comment]
I am not able to reproduce this in 1.7.0. Also if you have optifine that is a known issue that I am not able to support.

**Comment by tfox83** [comment]
1.7.0 is due out later today as beta.

**Comment by beanorx** [comment]
thermal dynamics covers: for itemducts.   made with structural ducts and the block you want the texture to be.  will update.

**Comment by Realmm** [comment]
I just had this error in 1.7.1, same exact thing.
