### ISSUE TITLE
Exception while rendering an item

### ISSUE THREAD

**Issue by EstagiarioAnphis** [FTBTeam/FTB-Ultimate-Reloaded#222]
* **Modpack Version**:  1.6.0

* **Issue**: Game keeps crashing after cuting some cherry leaves with vajra [Silk touch ON] #212 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8b02b355

* **Is it Repeatable?**: Maybe

* **Mod/s Affected**: forestry.arboriculture

Notes: Im playing on MP server

**Comment by tostamista23** [comment]
It does not happen if you are in creative mode, i was able to reproduce it almost 100% with vajra
*Video:*  https://youtu.be/MkEY_GkJ2Ow

**Comment by tostamista23** [comment]
not fixed but i have more information:
seems only crashs if cherry tree is spawned by pregnation/generated (idk what is called)
