### ISSUE TITLE
Tech Reborn Fusion Reactor - Generated power usage

### ISSUE THREAD

**Issue by Marcel2508** [FTBTeam/FTB-Ultimate-Reloaded#223]
* **Modpack Version**:
FTB Ultimate Reloaded v 1.6.0 MC 1.12.2
* **Issue**: 
Power (EU) extraction from tech reborn fusion reactors.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: yes

* **Mod/s Affected**: IC2, Tech Reborn, (Energy Converters)
* **Known Fix**:-

When using fusion reactors, there seems to be no proper way to pull out more than 16k eu/t out of them (using 2 IV-consumers on top and bottom with each of them connected to 4 EV-Producers).
Most of the energy produced by higher tier fusion generators is unuseable/wasted.
The Superconductor-Cables won't connect to it either (+ you can only craft them by destroing tech reborn machines with pickaxe).

**Comment by NiallDoherty** [comment]
Yeah this relates to issue #199. The superconductor cable is newly added to tech reborn, it's not like the other superconductors which are just used in crafting.

**Comment by NiallDoherty** [comment]
Ah apparently Tech Reborn cables don't work with EU at all, that would do it...

**Comment by tfox83** [comment]
At this time they are not intended for this pack as they transfer RF only.  Using IV consumers at this time are the best way.  If you convert directly to RF you should be able to capture most of the energy produced, due to the increased buffer rate a few updates ago.

**Comment by Zalgo2462** [comment]
Even though the buffer rate has been increased, the IV consumers only pull out a fraction of the power since each consumer is limited to 8192 Eu/t. I don't know if there's actually anything you can do to make this better though. I see there's a similar issue on TR's repo: https://github.com/TechReborn/TechReborn/issues/1607

**Comment by Marcel2508** [comment]
I think this issue was closed too early @tfox83 .
We would need a new kind of cable or converter (or a fixed superconductor-cable) for this to work.
Because IV consumers are limited to their 8k Package each tick, they can't supply the energy bridge with any more (from what I've tested).
A higher buffer limit on the energy-bridge wont help with this at all...
Only 2 sides outputting power = max 2 IV Consumers (8k/t each) = 16k eu/t (64k rf/t)
