### ISSUE TITLE
Simple Corn Crash

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#224]
* **Modpack Version**: 1.7.0

* **Issue**: Crashing when creating a new single player world, or after a short amount of exploration, and it keeps crashing after another bit of exploration. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/70833d91

* **Is it Repeatable?**: Yup every time I create a world or after a small bit of exploration, it crashes.

* **Mod/s Affected**: Looks like it's a Simple Corn issue

* **Known Fix**:

**Comment by tfox83** [comment]
Submitted issue to moddev:  https://minecraft.curseforge.com/projects/simple-corn/issues/24

**Comment by NiallDoherty** [comment]
This seems to be fixed in the latest version of the mod

**Comment by tfox83** [comment]
Yup, its in 1.7.1 which was just now pushed straight to release
