### ISSUE TITLE
Can't craft Fluix Crystal

### ISSUE THREAD

**Issue by lucasociale** [FTBTeam/FTB-Ultimate-Reloaded#225]
I can't craft fluix crystal ? How am i suppose to use AE2 without those crystals ? i've tried to make some, the recipe is good but won't work in a crafting table , is that normal ? IS AE2 useless in this modpack ?

**Comment by tostamista23** [comment]
[its working for me](http://puu.sh/Dtfjp/308618328c.png)
its Certus quartz crystal not the pure one
Which crafting table? modpack version? did you try reinstalling?
AE2 is not useless in this modpack

**Comment by tfox83** [comment]
Working fine for me too, please make sure you have all the scripts installed.  If not please try a fresh install
