### ISSUE TITLE
Resources not consumed in ProjectRed Expansion Project Bench

### ISSUE THREAD

**Issue by Zeemo** [FTBTeam/FTB-Ultimate-Reloaded#226]
* **Modpack Version**: 1.7.0

* **Issue**: The Project Bench does not consume resources for a recipe **provided the Recipe Plan for that recipe is present** and results in infinite crafting for some resources. Crafting a Wooden Gear via a Recipe Plan consumes 4 planks but crafts 2 wooden gears when shift clicking. Crafting items that require a bucket, such as Signalum or Enderium blends, will give infinite crafting, as the bucket and pulverized metals aren't consumed.
**NOTE: Recipe Plan MUST be present in order for this to be repeatable**
**Also reported since Feb 13 in ProjectRed Expansion GitHub, [#1458](https://github.com/MrTJP/ProjectRed/issues/1458)**

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b5518c72

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectRed-1.12.2-4.9.1.92-mechanical (assumption)

* **Known Fix**: None so far

**Comment by tostamista23** [comment]
ProjectRed is dead since nov 2018
(This repo is coming to)
