### ISSUE TITLE
Dissapearing Frame moved with Framemotor

### ISSUE THREAD

**Issue by lucabernegger** [FTBTeam/FTB-Ultimate-Reloaded#228]
* **Modpack Version**: FTB-Ultimate-Reloaded 1.6.0

* **Issue**: 
When moving ProjectRed Frames with a Framemotor the frame directly on the framemotor dissapears after 2-3 movements. 

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Project Red

* **Known Fix**: -

**Comment by rexlManu** [comment]
Try to update project red

**Comment by lucabernegger** [comment]
It is up to date I think. Version 4.9.1.92

**Comment by Chameebling-zz** [comment]
Happens in modpack version 1.7.1 also. Only with frames with covers on them pretty sure.

**Comment by tfox83** [comment]
fixed in latest version
