### ISSUE TITLE
Server Crash when turtle moves

### ISSUE THREAD

**Issue by rexlManu** [FTBTeam/FTB-Ultimate-Reloaded#229]
* **Modpack Version**: 1.6

* **Issue**: server crashes when the turtle begins to mine

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/84400aee

* **Is it Repeatable?**: yes

* **Mod/s Affected**: cc tweaked

* **Known Fix**: sry ._.

**Comment by NiallDoherty** [comment]
I believe this is fixed in CC: Tweaked 1.82.3 "Fix turtle.compare*() crashing the server."

**Comment by rexlManu** [comment]
In the 1.7 update from the modpack the mod got updated but the modpack update is still in beta.

**Comment by tfox83** [comment]
this is fixed in 1.7.0 which will be moved to release today
