### ISSUE TITLE
Plant gather stops working when maple saplings spawns 'tile.for.leaves.name' instead of maple leaves

### ISSUE THREAD

**Issue by EstagiarioAnphis** [FTBTeam/FTB-Ultimate-Reloaded#231]
* **Modpack Version**: 1.6.0
* **Issue**: Sugar maple sapling (tree) keeps spawning this 'tile.for.leaves.name' when using plant sower and then plant gather stops working (energy bar still works)

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: Floresty & Industrial Foregoing

 Screenshot: https://imgur.com/4jLh9aa

**Comment by tfox83** [comment]
fixed in latest
