### ISSUE TITLE
Sequential Fabricator doesnt craft QuantumSuit Boydarmor

### ISSUE THREAD

**Issue by tostamista23** [FTBTeam/FTB-Ultimate-Reloaded#233]
* **Modpack Version**: 1.6.0

* **Issue**: Crafting recipe for boydarmor doesnt work on Sequential Fabricator. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IndustrialCraft2 & Thermal Expansion

Notes & screenshot: 
![image](https://user-images.githubusercontent.com/47741781/58375421-9ffd5d00-7f4a-11e9-921c-3641e86fa4f6.png)
As you can see, it does not detect the recipe BUT if you exit the sequential fabricator and enter again it shows up but doesnt craft (set recipe included)
![image](https://user-images.githubusercontent.com/47741781/58375433-d3d88280-7f4a-11e9-8ffd-99da1b3a4b22.png)

**Comment by letsgo00** [comment]
Happens to me also with me unable to repair lzh-condensators

**Comment by tfox83** [comment]
craft those manually for now
