### ISSUE TITLE
cc: Tweaked not correctly detecting bundled cable signal

### ISSUE THREAD

**Issue by CryptoSmashr** [FTBTeam/FTB-Ultimate-Reloaded#234]
Modpack Version: 1.5.0

Issue: 
If i test redstone signal (redstone.getBundledInput) from a bundled cable it reports the signals at the time of connecting the computer to the bundled cable instead of the current signal.
e.g. there is a signal on white and orange i connect a computer to the bundled cable and test the colors it will report back white and orange. Then i change the signal to only white. the computer or turtle will still report white and orange have signal until i break the bundled cable connection from the computer and place the cable back again or make the turtle move 

Is it Repeatable?: yes with computers and turtles

Mod/s Affected: cc: Tweaked, Porject Red

Known Fix: (replace the connection before every test)

**Comment by NiallDoherty** [comment]
Update the pack, this has been fixed

**Comment by tfox83** [comment]
This is fixed in next version
