### ISSUE TITLE
Reliquary Mob Charms Crahes Game

### ISSUE THREAD

**Issue by Chintagious** [FTBTeam/FTB-Ultimate-Reloaded#235]
* **Modpack Version**: 1.7.1

* **Issue**: Wearing a mob charm (zombie, specifically) and attacking the mob causes game to crash.

* **Link to Log or Crash File Paste**: 
    * Crash Log - https://paste.feed-the-beast.com/view/70b72df3
    * Server Log - https://paste.feed-the-beast.com/view/b13a89a8

* **Is it Repeatable?**: Yes, use any weapon; do not think mob has to die.

* **Mod/s Affected**: Reliquary

* **Known Fix**: Unknown

* **Relevant Tickets**: https://github.com/P3pp3rF1y/Reliquary/issues/355

**Comment by gbartz** [comment]
I can confirm this.  It just happened to me.  In my case, it crashed the server.

**Comment by Chintagious** [comment]
Same with server crashing, actually not sure if it happens in single player. Apparently the two charms that cause it to crash are Blaze and Zombie, but the others are fine. I haven't tested the blaze one, however.

**Comment by tfox83** [comment]
disabled the two charms until they are fixed, if ever
