### ISSUE TITLE
Game crash on 260+ height [Xaero's Minimap]

### ISSUE THREAD

**Issue by EstagiarioAnphis** [FTBTeam/FTB-Ultimate-Reloaded#236]
* **Modpack Version**: 1.7.1

* **Issue**: Game crash when you reach 265+ height (MP and SP tested)
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2c9ee712

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: Xaero's Minimap / xaero96

Notes: Tested with 4 different players on MP server.

**Comment by Arbie456** [comment]
I'm having the same issue, AND I can't get logged back onto the server because of it.

**Comment by hardballryan** [comment]
I’m having the same issue. Still looking for a solution

**Comment by TheElementalOfDestruction** [comment]
Should be fixed by the most recent version of the minimap and worldmap mod (I actually talked to the developer of the mod). We just need the maintainers to update them :/

For now you can find an nbt editor and manually modify your position below 250

**Comment by TheElementalOfDestruction** [comment]
You could also potentially disable the mod on your end, get back to below 250, then re-enable it?

**Comment by tfox83** [comment]
Fixed with latest
