### ISSUE TITLE
Gravichestplate-- An expensive Jetpack with no creative flight

### ISSUE THREAD

**Issue by earlywyrm** [FTBTeam/FTB-Ultimate-Reloaded#237]
**Modpack Version**: 1.7.0/1

 **Issue**: Gravichestplate does not have proper Levitation mode as from older versions of GravitationSuite. The Gravichestplate is virtually no different from the Advanced jetpack nano chestplate, and has lost functionality since FTB Infinity and Minecraft 1.7.10. Going into hover mode is not creative flight as it disables when touching the ground, and cannot be activated by rapid double jump. Boost key still works, but the creative flight is missing which is the allure of the armor piece.

 **Mod/s Affected**: Gravitation Suite

 **Known Fix**: Go use MPS

**Comment by tfox83** [comment]
I am able to use creative flight just fine with it.

**Comment by Charterino** [comment]
I get the same issue on version 1.12.2.

**Comment by Fadirstave** [comment]
Having the same myself on Modpack Version 1.8.0.

**Comment by 45freehold** [comment]
Same issue. MC 1.12.2 / GS 3.1.1

There is no difference between AEJ and GCP in terms of flying - both have "hover mode" that disables every time you land. In earlier versions, GraviChestPlate had the true creative mode flying and it was really worth crafting. Now, considering the cost, it is useless and a complete waste of resources.
