### ISSUE TITLE
Crafting duplication bug

### ISSUE THREAD

**Issue by Muzkito** [FTBTeam/FTB-Ultimate-Reloaded#238]
* **Modpack Version**: 1.7.1

* **Issue**: Shift left clicking then shift right clicking after crafting an item with a full inventory creates a full stack of the crafted item. Works with every craftable thing in the game.
I uploaded a demonstration of the dupe. https://youtu.be/gSoAlRyy6IU
 
* **Is it Repeatable?**: Yes, easily repeatable.

* **Known Fix**: Setting `"Experiemental Shift Crafting"` from true to false in fastbench seems to resolve this issue, it's true by default.

**Comment by watlok** [comment]
I just looked at the source for this mod. transferStackInSlot function has at least 3 ways to dupe with experimental shift crafting set to true.

**Comment by tfox83** [comment]
This has been fixed in latest version
