### ISSUE TITLE
Server restart loss of Modded Items.

### ISSUE THREAD

**Issue by CrazyM0nkeyy** [FTBTeam/FTB-Ultimate-Reloaded#239]
* **Modpack Version**: 1.7..1

* **Issue**: Me and a couple of mates have started hosting our own Ultimate Reloaded, we had been playing for a few hours and decided to turn off the server. The next day we started the server back up and we noticed that all the modded items we had ether mined, tools which we've made or machines have been de-spawned from all our inventories and from the world. We also noticed that some of the modded trees and turned into forestry workbenches and logs. The additional non vanilla ores have turned into cobble or stone. This has happened twice as we have tried a reset of the server along with continuing to play and then resetting the server.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d010483e

* **Is it Repeatable?**: Yes after each server restart

* **Mod/s Affected**: Can't tell that there is any direct moods, as we are seeing all modded items affected.

**Comment by tfox83** [comment]
Please check with your server provider, as I am not able to support or reproduce this issue, thanks
