### ISSUE TITLE
Missing recipe of "fluid pipes" from immersive engineering

### ISSUE THREAD

**Issue by detrophy** [FTBTeam/FTB-Ultimate-Reloaded#241]
* **Mod Version**:1.7.10 

* **They can be created using the creative mode in GUI with searching for "fluid pipe". Searching in the parts menue (right side) or trying to craft them doesn't work**: 

* **https://paste.feed-the-beast.com/view/f5c8fb50**: 

* **Yes**: 

* **immersive engineering**:

**Comment by diabloget** [comment]
I think I found a solution for the problem of the recipes and it is deleting the folder called "Config" in the the server

**Comment by diabloget** [comment]
It works for IC2 and other mods

**Comment by ktole1999** [comment]
deleting the config folder resets the pack to default which is not the intention of the pack dev

**Comment by tfox83** [comment]
fluid pipes are disabled.  Deleting any config files without knowing what you are doing will break the pack
