### ISSUE TITLE
Can't find any marble or limestone.

### ISSUE THREAD

**Issue by FamelZundapp** [FTBTeam/FTB-Ultimate-Reloaded#242]
- Modpack Version: 1.7.1

- Issue: I cannot find any marble or limestone spawned in the world.

- Link to Log or Crash File Paste: Dont't have any.

- Is it Repeatable?: Not sure.

- Mod/s Affected: Chisel - version MC1.12.2-0.2.1.35

Known Fix: Couldn't find any.

**Comment by gbartz** [comment]
You can make marble with Chisel out of Quarried Stone.
