### ISSUE TITLE
V1.7.1

### ISSUE THREAD

**Issue by CubieX** [FTBTeam/FTB-Ultimate-Reloaded#243]
* **Modpack Version**: 1.7.1 / MC 1.12.2

* **Issue**:
Probably AppliedEnergistics config and/or script erroneous.
It's impossible to craft "PrintedCircuits" or dependent ones.
Without those, there is no way to craft most of the AE components.
As Inscribers and metheorites are disabled, it's necessary to craft the circuits with that other recipe. (JEI says: Nether dust cutter, 2x gold, 1x redsone, 1x silicone)
But it's not outputting anything.

* **Is it Repeatable?**: 
Just run the mod pack and try to craft any printed circuit.
Recipe is in JEI, but does not output anything.
Makes AE2 useless.

Seems like the script is kind of working
(because JNE shows the alternate recipe, the disabled items are hidden), but the recipies do not work.
Others in the same script do work. (like converting charged crystal to normal crystal)
Strange.

* **Mod/s Affected**: AppliedEnergistics2 rv6-stable 6

* **Known Fix**:
Re-enable Presses, Inscriber and Meteorites and do it the old fashioned way.

**Comment by diabloget** [comment]
IC2 have the same problem, I cant start with the mod because every time that I try to make something of IC in the crafting table, nothing happends :c

**Comment by tfox83** [comment]
Please try a fresh install of the pack
