### ISSUE TITLE
No use for iridium shards found in chests,,,

### ISSUE THREAD

**Issue by gbartz** [FTBTeam/FTB-Ultimate-Reloaded#245]
* **Modpack Version**: 1.7.1

* **Issue**:  There are no uses for Iridium Shards found as loot in chests.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: Pehraps add a recipe to convert these shards to Iridium Nuggets?

**Comment by AHrubik** [comment]
I fixed this for my server using craft tweaker. I've included the script in the pastebin below.

https://pastebin.com/W5NpTxiQ

**Comment by estebes** [comment]
This is now fixed within IC2 (syarting from build #167). Iridium shards now have an ore dictionary entry with the value "nuggetIridium" so they can be crafted into an ingot.

**Comment by tfox83** [comment]
This is fixed in latest version
