### ISSUE TITLE
Industrial Foregoing - Fluid Pump stop working after some lava pumped

### ISSUE THREAD

**Issue by LuckyLuke2019** [FTBTeam/FTB-Ultimate-Reloaded#246]
* **Modpack Version**: 1.7.1

* **Issue**: Fluid Pump isn't working. After i placed down the Fluid Pump 1 block over lava in nether, the pump will generate only 10k Lava and stops after it. There is no way to continue the production. Also there is a range upgrade +10 placed in.

Screenshot links:
1.  http://i.grab.la/09603-9221c521-75df-498c-a61a-4224948f5ec5.png
2. (with show range enabled) http://i.grab.la/09603-82b6e805-79e3-4cdd-8f18-4ae431039b74.png

* **Link to Log or Crash File Paste**: No log because nothing crashed. The machine is only not working after 10k lava pumped.

* **Is it Repeatable?**: Yes. Place the pump on another place 1 block over lava in nether and it will produce only 10k lava (with +10 range upgrade). 

* **Mod/s Affected**:  Industrial Foregoing

* **Known Fix**: No known fix yet

**Comment by tostamista23** [comment]
Dont know if this is affected or not but placing range addon after giving RF, most of the time fluid pump only works 1x1 (tested in 1.5), dont know if this affects unloading and loading chunks

Notes: 
1. Build everything in the same chunk (pressing F9, may crash you) 
2. Switch pipes to fluxduct with [servo](https://youtu.be/cn2ypMmQddM?t=422) 
3. Enough RF in energy cell?

Check this [printscreen](http://puu.sh/DBbyP/cf931a6ff6.jpg)
magmatic dynamo
fluid pump
servo (white servo may not work)
ender tank or black hole tank
2x fluxduct

**Comment by TheElementalOfDestruction** [comment]
So here is some details for you all:

• if the fluid pump completes one unit of work without a block to suck up it will get stuck until broken

• use range upgrades

**Comment by 0xlsca** [comment]
> So here is some details for you all:
> 
> • if the fluid pump completes one unit of work without a block to suck up it will get stuck until broken
> 
> • use range upgrades

This caused mine to pump lava ad infinitum (no lava blocks consumed). Seems like the pump could use some love.

**Comment by TheElementalOfDestruction** [comment]
@tomconnery which part?

**Comment by 0xlsca** [comment]
> @TomConnery which part?

Using range upgrades.

Here's the desription how I got mine to pump ad infinitum without consuming lava blocks:

- place down pump
- install range upgrade
- supply power

You need to follow those steps in this *exact* order for it to work.

**Comment by TheElementalOfDestruction** [comment]
Are you using it on a pool that is more than one block deep? Because it starts with the bottom and I sometimes find it will pull from further than it says it will. Make by hand a small lake that is one block deep and see if the problem still occurs

**Comment by rrreche** [comment]
> 
> 
> > @TomConnery which part?
> 
> Using range upgrades.
> 
> Here's the desription how I got mine to pump ad infinitum without consuming lava blocks:
> 
>     * place down pump
> 
>     * install range upgrade
> 
>     * supply power
> 
> 
> You need to follow those steps in this _exact_ order for it to work.

Followed these steps and still not working.

**Comment by 0xlsca** [comment]
This seemed to work now, the lava was pumped as normal.

Also, I have checked the world in which I installed the other pump and you were right with the radius:
There was just so much lava that it seemed like the pump would be duping stuff, but I now have certainty that this is not the case.

It also makes sense that the small lake next to the pump hasn't been touched yet because it takes a long time to get from the outer perimeter (and the lava located there) to the middle of the space.

**Comment by StrayCargo** [comment]
Why was this ticket closed this is still an active issue with the most current version of the mod

**Comment by saturner** [comment]
I am also experiencing this on FTB Academy.

**Comment by kennyiv** [comment]
I had a similar issue with the fluid pump. I resolved it by fully enclosing the liquid pocket. The liquid wasn't fully surrounded by blocks on the layer below the fluid pump. The issue may be caused by running liquids or that because the pool wasn't enclosed it couldn't determine the size of the pool. Hope this helps.

**Comment by jxu** [comment]
I am having issues as well. Even after enclosing the liquid I still could only get 1x1 to work (range upgrades didn't work)

**Comment by jxu** [comment]
Here are issues in mod repo 
 https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues?utf8=%E2%9C%93&q=pump
