### ISSUE TITLE
Advanced solar helmet has no texture

### ISSUE THREAD

**Issue by siebrant** [FTBTeam/FTB-Ultimate-Reloaded#247]
* **Modpack Version**: 1.7.1

* **Issue**: Advanced solar helmet has no texture/ shows only as black. Using a custom mod pack also doesn't work.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/1c75753d

* **Is it Repeatable?**: Yes, reinstalling the mod did not fix it.

* **Mod/s Affected**: Advanced solar panels (?)

* **Known Fix**: None.

**Comment by tfox83** [comment]
know issue without a fix, it still works fine
