### ISSUE TITLE
Rending Gale Causes Server Crashing

### ISSUE THREAD

**Issue by mbaello** [FTBTeam/FTB-Ultimate-Reloaded#249]
**Modpack Version:** 1.7.1

**Rending Gale Causes Server Crashing** (and sometimes widespread client crashing -- this is speculation). It happens randomly on my server, but it's due to using the Flight feature of the Rending Gale (I believe it has to deal with particle effects according to the crash log). While the Rending Gale is used, the server may randomly hang. At this point, it never recovers. Eventually, everyone is timed out. A server tick ends up taking too long for the server and it will auto-shutdown under the assumption that the server crashed (mine is set to 2 minutes for benefit of the doubt that it'll recover). Another notable observation is the fact that across the span of 2 days (i.e. the first day it was used and the second day which was the day we decided to stop using it) people were crashing in "batches." They would report their clients froze and then would crash at essentially the same time. This was happening consistently to any player who was around someone using Rending Gale at the time (there's only 1 person currently using it on the server, so it's easy to track).

**Link:** https://paste.feed-the-beast.com/view/cc83dd3f

**This is repeatable.** To repeat, just have someone fly around using Rending Gale until the server hangs or someone crashes.

**Mods Affected:** Reliquary v1.3

**Known Fix:** No known fixes, but crash reports keep referring to particles of the Rending Gale while in flight -- Perhaps modifying the particles or causing none to spawn?

**Comment by Roadcrosser** [comment]
Also having the same issue here.

**Comment by tfox83** [comment]
that is supposed to be disabled in this pack, ill look into it

**Comment by tfox83** [comment]
removed/disabled in next version
