### ISSUE TITLE
Nothing to use Redstone Flux on besides basic machines

### ISSUE THREAD

**Issue by Sparten4ever92** [FTBTeam/FTB-Ultimate-Reloaded#250]
Been working with all sorts of Thermal Foundation/Dynamics/Expansion stuff, but now that I've found myself having an excess of RF and a flux capacitor to fill 'items and equipment' with, I can't find anything to actually use it on. Anything I've read about is from the thermal mods aren't in this pack, like Innovation or Redstone Arsenal. After going through all 133 pages of JEI I couldn't find anything that said it accepted RF other than the regular Thermal Foundation machines.

**Comment by EstagiarioAnphis** [comment]
Energy acceptor from Applied Energistics 2 works with RF
