### ISSUE TITLE
nanosaber 

### ISSUE THREAD

**Issue by Titanslayer74** [FTBTeam/FTB-Ultimate-Reloaded#252]
Version 1.7.1 

there is no way to activate or deactivate the nano saber from tech reborn. I have tried this in singleplayer and on a server and the problem is consistent. Also if the active version is brought in from creative or the inactive version the mode cannot be switched.  

* **Mod/s Affected**: Tech Reborn

**Comment by zedoax** [comment]
I was unable to duplicate this.  The command should be crouch+right click by default.  Have you tried this already?
