### ISSUE TITLE
Arcane Crafting Terminal dupes filled carts

### ISSUE THREAD

**Issue by Hanoverfist** [FTBTeam/FTB-Ultimate-Reloaded#253]
Ultimate Reloaded 1.7.1

 Placing filled carts (TNT cart, Tank cart, etc) in the Arcane Crafting Terminal crafting grid then right clicking the output gives a stack of the cart's contents and does not use up the carts. This works in both singleplayer and multiplayer.

https://i.imgur.com/jX5penz.png

Easily repeatable.

This dupe relates to the Arcane Crafting Terminal from Thaumic Energistics.

**Comment by tfox83** [comment]
fixed in latest
