### ISSUE TITLE
Bee analyser crash

### ISSUE THREAD

**Issue by jelek21** [FTBTeam/FTB-Ultimate-Reloaded#254]
* **Modpack Version**: 1.7.1

* **Issue**: Right-click on a Bee analyser causes a NullPointerException in PeripheralPlusPlus. Makes the game crash on Client side. (It is in a Screen rendering function...) I have tested: On a server, in solo, normal and creative gamemode.

* **Link to Log or Crash File Paste**: I had a 502 on your paste website, I used PasteBin instead.
https://pastebin.com/Gx2RD4z6 

* **Is it Repeatable?**: Yes, just place a Bee Analyser and right-click on it, Kaboom!

* **Mod/s Affected**: PeripheralPlusPlus

* **Known Fix**: None...

**Comment by hudony** [comment]
Yup, I got the same exact issue.

**Comment by bwoods89** [comment]
Seeing the same issue on my server

**Comment by executoronline** [comment]
Same here. Tree Analyzer too. Perhaps Butterfly also.

**Comment by tfox83** [comment]
removed them in favor of the default forestry ones
