### ISSUE TITLE
Viaduct No Texture and Not Working

### ISSUE THREAD

**Issue by zedoax** [FTBTeam/FTB-Ultimate-Reloaded#255]
* **Modpack Version**: 1.7.0

* **Issue**: Thermal Dynamics Viaducts do not have any texture, except a basic pipe skeleton
![2019-06-21_22 08 21](https://user-images.githubusercontent.com/9372283/59958232-28e7b580-9471-11e9-9a33-7d7d0f714e2a.png)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Dynamics

* **Known Fix**: None

**Comment by Roadcrosser** [comment]
This happens because you are placing untreated viaducts. For some reason JEI in this pack doesn't show fluid transposer recipes.

Fluid transpose them with Zephyrean Aerotheum to make working viaducts, and further fluid transpose them with resonant ender for long range linking viaducts.

**Comment by tfox83** [comment]
That is correct.  Its an issue with IC2 classic that was unable to be fixed.
