### ISSUE TITLE
Immersive Engineering missing crafting recipes

### ISSUE THREAD

**Issue by JDawgForReal** [FTBTeam/FTB-Ultimate-Reloaded#256]
* **Modpack Version**: 1.7.1
* **Issue**: Immersive Engineering doesn't have a crafting recipe for Blast Brick or Coke Oven that I could find.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/13d76320

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Immersive engineering - 0.12.89

* **Known Fix**: No known fix that I could find

**Comment by ktole1999** [comment]
is this item disabled in the pack?

**Comment by AHrubik** [comment]
Most of Immersive Engineering is disabled in this pack by default. You can fix this by deleting or renaming the Immersive Engineering script in the "scripts" subfolder.

" ...\Instances\FTB Ultimate Reloaded\scripts "

**Comment by ktole1999** [comment]
I would advise against deleting scripts unless you delete all. Deleting a single script will more than likely break other features



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------
