### ISSUE TITLE
I cant get my FTB Ultimate reloaded server to start

### ISSUE THREAD

**Issue by MonkeyNBananas** [FTBTeam/FTB-Ultimate-Reloaded#258]
* **Modpack Version**: FTBUltimateReloadedServer_1.7.1
* **Issue**: I cant get my server to run it says i dont have enough RAM to run it but i do

* **Link to Log or Crash File Paste**: Missing eula.txt. Startup will fail and eula.txt will be created
Make sure to read eula.txt before playing!
Starting server
Java HotSpot(TM) Client VM warning: ignoring option PermSize=; support was removed in 8.0
Java HotSpot(TM) Client VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Exiting...
Press any key to continue . . .

* **Is it Repeatable?**: yes

* **Mod/s Affected**: probably not

* **Known Fix**: getting more RAM or making my computer give the server more RAM which idk how to do

**Comment by ktole1999** [comment]
make sure you are running 64bit java so you can allocate more ram.

**Comment by MonkeyNBananas** [comment]
> make sure you are running 64bit java so you can allocate more ram.

I am

**Comment by tostamista23** [comment]
"Could not reserve enough space for 2097152KB object heap"

**Comment by MonkeyNBananas** [comment]
i would say that was correct if i didnt have an extra 6gigs of ram that it wont use 
update to my problem: my friends cant join my server

**Comment by MonkeyNBananas** [comment]
i can but they cant

**Comment by tostamista23** [comment]
how do you know its RAM? log shows 'space' (disk) not RAM

**Comment by MonkeyNBananas** [comment]
> how do you know its RAM? log shows 'space' (disk) not RAM

bruh

**Comment by tfox83** [comment]
Closing as this is not a modpack issue, please get support from your server provider
