### ISSUE TITLE
IC2 Fuel Rods do not become near depleted uranium

### ISSUE THREAD

**Issue by thomas15v** [FTBTeam/FTB-Ultimate-Reloaded#262]
* **Modpack Version**: 1.7.1

* **Issue**: In older versions of IC2 there used to be a chance that depleted fuel rods became near depleted rods. However currently in this pack we seem to be getting IC2 experimental items:
![image](https://user-images.githubusercontent.com/2163941/60756483-f3f56a00-9ffd-11e9-8d46-572aed93cb04.png)

Problem is that we do not have machines to turn this into something useful. Jei is also not showing this item nor can find recipes for it. 

* **Is it Repeatable?**: Yes. When a reactor finishes it's cycle you will see the behaviour (I recomend spawning in nearly depleted rods).

* **Mod/s Affected**: IC2 and possible Tech Reborn.

**Comment by estebes** [comment]
This is a problem with IC2 Classic profile since it would mean reactors hd to have different logic. I'll check if it is possible to fix.

**Comment by estebes** [comment]
Starting with build 169 of IC2 the Classic profile now adds extractor recipes for the depleted cells. (Single = 1 Cell - Dual = 2 Cells - Quad = 4 Cells )
![Screenshot from 2019-07-16 01-10-50](https://user-images.githubusercontent.com/6414656/61256936-b794dd00-a766-11e9-8c6b-e010a71083ff.png)

Maybe in the future Near Depleted Cells will be back. For now this will have to do.

**Comment by thomas15v** [comment]
It's not that ideal, since this sadly enough makes breeder reactors pointless :(. But yeah like you said this might have to do. EU-reactors are also not worth the time investment what power output is concerned sadly enough, but they are a niche item.

**Comment by estebes** [comment]
I made it this way because breeder reactors are not a thing anymore. So the depleted cells would still be useless. And they are only useless if you are converting rf to eu since for eu only they are a great investment especially with all the automation you can achieve nowadays.

**Comment by tfox83** [comment]
Closing issue as I cannot change those mechanics sadly

**Comment by Barhandar** [comment]
Depleted isotope cells (near depleted + coal dust) function in the reactor just fine (becoming re-enriched rod that you can add coal dust to to turn it into uranium fuel rod) in the pack, though.

Could add a centrifuge recipe to turn 4 single depleted rods/2 doube/1 quad into 3 cells and 1 near-depleted, since original chance to produce one was 25%.
