### ISSUE TITLE
Server doesn't work cause Java virtual machine wasn't create

### ISSUE THREAD

**Issue by ReinTristan** [FTBTeam/FTB-Ultimate-Reloaded#264]
* **Modpack Version**: FTB Ultimate Reloaded 1.7.1

* **Issue**:The server start file gave me the message:
OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
 

* **Link to Log or Crash File Paste**:None crash or log file yet 

* **Is it Repeatable?**:idk , maybe with the configuration of settings.sh file 

* **Mod/s Affected**:None 

* **Known Fix**:perhaps the -XX configuration in the settings.sh file  
(probably is a silly issue xd)
Thanks in advance guys

**Comment by ryan-loveland** [comment]
This probably has to do with the version of Java running on your sever. What OS you trying to run it on?

**Comment by tfox83** [comment]
This isnt a modpack related issue.  Please check with your server provider
