### ISSUE TITLE
FTB ultimate reloaded Game Crashes on loading screen whenever I try to load up a world. (Server/singleplayer) 

### ISSUE THREAD

**Issue by Beefy620** [FTBTeam/FTB-Ultimate-Reloaded#265]
<!--
Thanks for wanting to report an issue you've found. Please delete
this text and fill in the template below. If unsure about something, just do as
best as you're able. Thank you!
(FTB Ultimate reloaded) 
So everytime I attempt to open up a world it's stuck on the minecraft loading screen when loading up a new world, whether the world is a server or a single layer it refuses to load up. I have reinstalled the mods to no avail, I have also updated all graphics drivers.. I am playing on a server with friends and they are able to play it with less capable computers than mine. It happens every time I try to open a world. It doesn;t crash necessarily so I don't get a crash report, it just stays on the loading screen without ever loading the world. 

if you know of a fix please let me know! Thanks

**Comment by Beefy620** [comment]
I don't know where the description went lol. 
The issue is everytime I open a world it goes to the loading screen and does open the actual world, this happens for both my worlds and servers. I have tried to fix it by reinstalling and updating graphics drivers but nothing works. A fix would mean a lot, thanks!

**Comment by tostamista23** [comment]
reinstall java?
Do you have any crash logs/errors?
