### ISSUE TITLE
Server crash when loading certain chunks

### ISSUE THREAD

**Issue by BenUnderscore** [FTBTeam/FTB-Ultimate-Reloaded#266]
* **Modpack Version**: Version 1.7.1

* **Issue**: Whenever someone loads one particular base, the server crashes after 30 seconds.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1314e272

* **Is it Repeatable?**: Yes, by going to a particular area in the world (60.71, 49.00, -219.12 as written in the crash log) and loading a particular offending chunk (usually takes 30 seconds or so).

* **Mod/s Affected**: Unknown, the log does not indicate the offending mod, only that the server crashes while loading a chunk.

There was DiscordIntegration on the server side, but removing that did not help the issue, or change the logs.
The world is >128MB, so I cannot attach it to the issue.

**Comment by ktole1999** [comment]
i would restore from recent backup to allow you access to that block

**Comment by tostamista23** [comment]
Hydrator from industrial forgoing, I had the same problem
Work around: lily pad of fertility

Link: https://github.com/Buuz135/Industrial-Foregoing/issues/581

**Comment by BenUnderscore** [comment]
Thank you, removing the hydrators worked.

**Comment by tfox83** [comment]
This seems to be a forge issue.  I can slate to remove those blocks from the pack, as I highly doubt we will see a fix

**Comment by tfox83** [comment]
Hydrators have been removed from the pack until a fix is in place

**Comment by ichttt** [comment]
Bug fix is in forge 14.23.5.2846
