### ISSUE TITLE
My server wont start(JVM problem)

### ISSUE THREAD

**Issue by imdoneon** [FTBTeam/FTB-Ultimate-Reloaded#267]
* **Modpack Version**:  1.7.0 

* **Issue**:  When I try to start it immediately 
Detected following JVM error:
=======================================
Too many arguments in command line.
=======================================
JVM test failed. Can't run server, Exiting... 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  very repeatable 

* **Mod/s Affected**:  None 

* **Known Fix**:  IDK

**Comment by tfox83** [comment]
Please try to run only with the supplied jvm args
