### ISSUE TITLE
Right clicking on Project Red Illumar button with Soul Cage crashes and corrupts worldsave. 

### ISSUE THREAD

**Issue by awmayhall** [FTBTeam/FTB-Ultimate-Reloaded#269]
FTBUltimateReloaded-1.7.1-1.12.2: 

Right-clicking Project Red Illumar button with soul cage crashes and corrupts the world save: Just as the title states, when (normally) right-clicking on a Project Red button with a soul cage in hand a null pointer exception is thrown. The particular button in question was activating an iron door.  

From the crash report, the server saves in an incorrect state and corrupts the save file. (At least we were not able to fix it) 

Not sure if when clicking the button a soul cage tries to be placed in the space occupied by the button? This can be recreated in single player but is easier to achieve in multiplayer. Slightly spamming the button in single player causes the crash. Multiplayer, just clicking the button causes the crash. 

First Crash file: 
https://paste.feed-the-beast.com/view/90ba7d5b

Rebooted server crash: 
https://paste.feed-the-beast.com/view/4baf50f0

Restored from backup, repeated the action. Can confirm the issue is repeatable. Also tried to recreate the issue in a new local world with success. 

Project Red, Soul Shards Respawn:

**Comment by tfox83** [comment]
Fixed in latest version
