### ISSUE TITLE
Thermal Dynamics Servos, Filters, Retrievers not functioning in multiplayer

### ISSUE THREAD

**Issue by awmayhall** [FTBTeam/FTB-Ultimate-Reloaded#270]
FTBUltimateReloaded-1.7.1-1.12.2:

As the title states, there seems to be a weird issue going on with Thermal Dynamics Servos, Filters, and Retrievers. For sake of clarity, this is the interface we are seeing on a Resonant Servo.

![image](https://user-images.githubusercontent.com/52192442/61248100-0a937380-a718-11e9-8dc7-b19813d5b946.png)
 
No items can be placed in the servo interface for blacklist or whitelist. There are no advanced features, and the servo just doesn't work. 

What's even weirder is that previously placed servos work fine. But when you remove them, and replace them. they are bugged. At first, we thought this was an issue with the player data as other people on the server could craft working servos. HOWEVER! if the player interacted with a bugged servo, they could no longer craft functioning servos. 

Just a formality of posting what a functioning resonate servo should look like... 

![image](https://user-images.githubusercontent.com/52192442/61248324-74138200-a718-11e9-9406-5d4da0b4b410.png)

This issue doesn't just affect servos, but filters and retrievers too.  

Deleting the player data fixed this issue once. However it is back and no amount of server restarting, or player data deleting fixes the issue. Any ideas on what could be causing this? No errors are thrown in the server. 

Downloading the world from the server and opening it in single player everything works as expected.  

Team CoFH, Thermal Dynamics. 

Known fix at first seems to be corrupted player data, removing the player data fixed the issue for a short time but it comes back with no permanent fix at this time.

**Comment by tfox83** [comment]
You may need to test this in another world, I cannot reproduce this issue
