### ISSUE TITLE
[Question] Harder AE2

### ISSUE THREAD

**Issue by 0xlsca** [FTBTeam/FTB-Ultimate-Reloaded#271]
This is not a bug, but a question regarding the modpack config.

I really like the modpack and want to continue playing with it, but for my private installation I'd like to make my AE2 gaming more challenging by enabling channels etc. back into the game. This only worked to the point that I got everything back with the respective Zenscript and config edits, except for the Charger.

Since I seem to be running out of options, I want to ask where exactly you guys disabled it because it's a rather crucial element of the mod for me.

I made sure it is enabled in my AE2 config and I went ahead and disabled the AE2 script, but to no avail.

Best regards, Conn.

**Comment by ktole1999** [comment]
you could always make a backup of config and scripts folder. reset them to defaults.

**Comment by 0xlsca** [comment]
Scripts I checked, but configs is something I haven't yet.

Will answer again after checking - thanks for the hint!

**Comment by 0xlsca** [comment]
This worked, I'll proceed with pinpointing the causing mod / configuration.

**Comment by 0xlsca** [comment]
I found the culprit.
They put it on the item blacklist of JEI, therefore an edit of the respective JEI config is required.
