### ISSUE TITLE
FTB-Ulzimate-Reloaded Server Crashes on Startup (Parsing Error)

### ISSUE THREAD

**Issue by xMosbi** [FTBTeam/FTB-Ultimate-Reloaded#272]
* **Modpack Version**: FTB Ultimate Reloaded-1.7.1-1.12.2

* **Issue**: Server Crashes when ever we are trying to Start it

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/af573104

* **Is it Repeatable?**: Yes, everytime we start the Server Up

* **Mod/s Affected**: Computercraft

* **Known Fix**: -

**Comment by tfox83** [comment]
That is not computercraft causing that.  Please try a fresh install of the server with a fresh world.  Also not using multicraft
