### ISSUE TITLE
FTB Ultimate Reloaded 1.7.1 server industrialcraft-2

### ISSUE THREAD

**Issue by star4802** [FTBTeam/FTB-Ultimate-Reloaded#273]
* **Modpack Version**: 
FTB Ultimate Reloaded 1.7.1
* **Issue**: 
industrialcraft-2 Forge hammer is played only in singleplay but not crafting and use forge hammer in multiplayer.
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Try a fresh install of the server, sounds like you are missing the scripts server side
