### ISSUE TITLE
Game crashes on loading single player world

### ISSUE THREAD

**Issue by teo20** [FTBTeam/FTB-Ultimate-Reloaded#274]
The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)

This is the error that I'm getting. Please help me
[crash-2019-07-20_16.42.06-server.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3413982/crash-2019-07-20_16.42.06-server.txt)

**Comment by tostamista23** [comment]
https://github.com/CreeperHost/CreeperHostGui/issues for better help

probably pregenData.json is corrupted 
if you delete world save data and load again should work.

**Comment by teo20** [comment]
Thank you! This worked for me.

**Comment by tfox83** [comment]
Thanks @pedrotest1
