### ISSUE TITLE
FTB Aluminumm Ingot.

### ISSUE THREAD

**Issue by Simsuy** [FTBTeam/FTB-Ultimate-Reloaded#275]
* **Modpack Version**: FTB Ultimate Reloaded 1.7.1 from the twitch app

* **Issue**: Aluminum Ingot isn´t compatible with Compressor since it´s the item version from Tech Reborn instead of Thermal Foundation.

* **Is it Repeatable?**: 100% Repeatable.

* **Known Fix**:

**Comment by Simsuy** [comment]
Semi Fluid Generator from tech reborn Can load Cerosote oil but it doesn´t produce any energy.

**Comment by tfox83** [comment]
Any Alum ingot now works in compressor or compactor
