### ISSUE TITLE
Logic processors crafting doesnt work

### ISSUE THREAD

**Issue by tostamista23** [FTBTeam/FTB-Ultimate-Reloaded#277]
* **Modpack Version**: 1.8.0
* **Issue**: none of logic processors crafting works

P.S: may be server side since im in MP but i ill update soon, found more bugs

**Comment by tostamista23** [comment]
server side problem, reset configs fix the problem
this was affecting any type of gear to (gear from ae2, buildcraft thermal foundation, etc)

**Comment by ktole1999** [comment]
resetting configs may have killed the pack based on original intentions by dev. some items are disabled or changed for pack difficulty. i would redownload the pack configs to restore any corruption that may have caused the issue to begin with.
