### ISSUE TITLE
[MP] disconncted from server after pressing f9

### ISSUE THREAD

**Issue by tostamista23** [FTBTeam/FTB-Ultimate-Reloaded#278]
* **Modpack Version**: 1.8.0 but works on 1.7.1 to

* **Issue**: press f9 a few times

* **Link to Log or Crash File Paste**:[ Image](http://puu.sh/DWzut/e6a1d412df.png)

* **Is it Repeatable?**: Most of the time

**Comment by RedCorpIndustry** [comment]
I can repeat it on 1.8.0 as well.

**Comment by tfox83** [comment]
This has been fixed in 1.9.0 beta (public in a couple days) according to the mods changelogs
