### ISSUE TITLE
[Question] How much EU/t is matter fab supposed to use?

### ISSUE THREAD

**Issue by tostamista23** [FTBTeam/FTB-Ultimate-Reloaded#280]
i was going to post this on techreborn github but wikipedia from techreborn mentions FE and not EU, I was confused which side was the problem

Right now, is using 1k per 2% which is easy, wikipedia doesnt mention EU or FE per UU to

https://wiki.techreborn.ovh/doku.php?id=blocks:matter_fabricator

**Comment by tfox83** [comment]
FE divided by "4" is EU.  In some mods they use 10, but I believe everything TR is divided by 4 for EU
