### ISSUE TITLE
Railcraft Steam Engines Missing

### ISSUE THREAD

**Issue by Sipnol** [FTBTeam/FTB-Ultimate-Reloaded#282]
are the Railcraft Steam engines disabled in FTB Ultimate Reloaded V1.7.1? Cant find them in JEI and cant craft them. if yes is there any harm in reenabling them and how can i do that?

* **Modpack Version**: 1.7.1

* **Issue**: Not finding Railcraft Steam Engines

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Railcraft

**Comment by Sipnol** [comment]
OK just looked through the Source Code of RailCraft and the engines are not included there as far as i can see

**Comment by ktole1999** [comment]
making pack changes like that could cause more issues with other parts of the pack that were intentionally changed.
