### ISSUE TITLE
AE2 Crafting

### ISSUE THREAD

**Issue by Phantum** [FTBTeam/FTB-Ultimate-Reloaded#283]
* **Modpack Version**: 1.8

* **Issue**:  AE2 Autocrafting with Lapotron Crystals, RE Batteries, EnergyCrystals, MFE, MFSU, lapotronic energy orb etc...

* **Is it Repeatable?**: Yes, setup autocrafting for MFE, MFSU, Lapotron Crystals, or anything else of that sort.

* **Mod/s Affected**: IC2, AE2    The Devs of AE2 Insist it's not on their end, and instead on the end of either IC2, or the modpack devs, so not sure if there's a config setting that can be adjusted on that?

* **Known Fix**: Fully charging the energy containers lets you craft with them, but when you're crafting for example and adjustable SU, where it takes 8 lapotronic energy orbs, that's 800M EU to just make one of them.

**Comment by squishey123** [comment]
This has been an issue since AE1, its related to the metadata on the items when they are crafted vs. what they show in JEI. An easy fix is usually manually updating the output of the recipe with the crafted one

**Comment by tfox83** [comment]
Squishey123 is correct.
