### ISSUE TITLE
Forestry Vegetable Farm

### ISSUE THREAD

**Issue by brunocu** [FTBTeam/FTB-Ultimate-Reloaded#284]
* **Modpack Version**: 1.7.1

* **Issue**: Iron Electron Tubes can't be used to create vegetable farms

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes, I also tried it in the latest 1.8 modpack version.

* **Mod/s Affected**: Forestry

**Comment by brunocu** [comment]
Did a bit of digging. Apparently this was removed in Forestry 5.7.0.240 so not a bug

**Comment by tfox83** [comment]
Thanks for the update.
