### ISSUE TITLE
AE2 autocrafting logspam

### ISSUE THREAD

**Issue by Phantum** [FTBTeam/FTB-Ultimate-Reloaded#285]
* **Modpack Version**: 1.8 

* **Issue**: MASSIVE log spam 

* **Link to Log or Crash File Paste**: https://gist.github.com/Phantum/5b97a400d755423d6e414aedb92cab20

* **Is it Repeatable?**: yes

* **Mod/s Affected**: AE2, TechReborn, Ic2

* **Known Fix**: Unknown at this time (will be attempting to use a process pattern on a molecular assembler to see if that will solve the issue for the time being.

**Comment by tfox83** [comment]
I am not able to reproduce this with that recipe at AE2 crafting.  Maybe your fix was the workaround.
