### ISSUE TITLE
thermal expansion and buildcraft

### ISSUE THREAD

**Issue by gangsterlx** [FTBTeam/FTB-Ultimate-Reloaded#286]
* **Modpack Version**:  1.7.1

* **Issue**: i have a pump in the nether, quarry in overworld, wanting to power it with thermal expensions lava gens, but they dont connect with buildcraft blocks, soo now i need to remake the system with buildcraft items while they do the exact same... is it possible to let them just connect with each other?

* **Is it Repeatable?**: yea

* **Mod/s Affected**: buildcraft and thermal expansion in ftb ultimate reloaded 1.7.1

* **Known Fix**:

**Comment by tostamista23** [comment]
i do not recomend using buildcraft for that
You can use magmatic dynamos and energy producer/consumer to convert RF to MJ or you can still use thermal expensions lava gens and convert EU to MJ

I dont know which pump are you using but i find my build quite simple and  better [ image](https://images-ext-1.discordapp.net/external/GmeTW5YsbeTXnmdpTysqgELgCHghLnlcilOmUmHB3KE/https/puu.sh/DBbyP/cf931a6ff6.jpg?width=1240&height=677)
magmatic dynamo
fluid pump
servo (white servo may not work)
ender tank
2x fluxduct
Range addon, just make sure to place it before turn it on

**Comment by gangsterlx** [comment]
Yeah thanks i have it fixed now indeed with power converters mybad didnt remember how they worked, but quarry is up and running, and my pump station is a bit bigger then ures but its first and it has decent range, so lavalake has been emptied i wil ise ure design indeed
