### ISSUE TITLE
Supercondutor cable missing in JEI

### ISSUE THREAD

**Issue by tostamista23** [FTBTeam/FTB-Ultimate-Reloaded#287]
* **Modpack Version**: 1.8

* **Issue**: Supercondutor cable are working now but its missing in JEI.

its using advanced machine frame from tech reborn and not from IC2  but it still possible to get advanced machine frame from tech reborn by mining tech reborn machines without wrench

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/64277727-e6763680-ceff-11e9-8e94-847fa3a73f1c.png)
Its availbe in 1.9.0 beta which is due out in a couple days.

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/64277759-01e14180-cf00-11e9-8169-7ca322cd35c1.png)

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/64277817-1cb3b600-cf00-11e9-93cb-74083a6d7c2d.png)
