### ISSUE TITLE
Can't build ProjectRed 2 Tunnel Bore.

### ISSUE THREAD

**Issue by RedEXperiment** [FTBTeam/FTB-Ultimate-Reloaded#289]
I know there is the railcraft tunnel bore but I like the old days where I could build monstronsities of tunnel bores using ProjectRed 2.

* **Modpack Version**: 1.7.1

* **Issue**:  Cannot create ProjectRed2 tunnel bore items missing.

**Comment by tfox83** [comment]
There is no tunnel bore in PR.  Sorry.
