### ISSUE TITLE
FTB Ultimate Reloaded - Very Laggy

### ISSUE THREAD

**Issue by SupahMayo** [FTBTeam/FTB-Ultimate-Reloaded#290]
This may not be the best place to put this, but here it goes.

I recently updated from a long outdated GTX 960 to an RX 580 and I am having trouble playing the game on my server. When loading into the server, there is immense lag when using the RX 580, but when I use the GTX i do not have this problem. Either games run fine, if not, great, including other modpacks, but this one just does not work properly. I have uninstalled old drivers and installed new ones. They are up to date. I am using version 1.7.1 for this modpack.

What should i do? Please help!

**Comment by MrDoritos** [comment]
I too had a problem with an AMD card.

1. Go to the AMD control panel
2. Click on tab "Gaming"
3. Go to "Global Settings"
4. Set "Wait for Vertical Refresh" to "Always on"
5. Enable and move slider "Frame Rate Target Control" to your monitor refresh rate
