### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Moonpaw8** [FTBTeam/FTB-Ultimate-Reloaded#291]
* **Modpack Version**:  1.12.2

* **Issue**:  Game crashes upon opening. First happened while battling the UR-Ghast in the Twilight Forest.

* **Link to Log or Crash File Paste**:   https://paste.feed-the-beast.com/view/79561448

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**:  Xaero's Minimap and possibly SplashAnimationCoremod

* **Known Fix**:  The crash message says to contact the author on planetminecraft or minecraftfourm.

**Comment by tostamista23** [comment]
First, modpack version is not 1.12.2 thats minecraft version and second you are probably using 1.7.1 which your problem is related to: #236

**Comment by Shybella** [comment]
@pedrotest1 No.

This is a crash with the minimap is you go higher than 254 blocks. 

This is fixed in 1.8.0 release but it's still set to beta.
