### ISSUE TITLE
Can´t start the mod

### ISSUE THREAD

**Issue by atomixxsk1ll3r** [FTBTeam/FTB-Ultimate-Reloaded#293]
* **Modpack Version**: 1.8.0

* **Issue**: When starting the launcher from Twitch, there shows an issue: Game crashed. I don´t even get out of the launcher.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: It is repeatable

* **Mod/s Affected**: FTB Ultimate Reloaded

* **Known Fix**:

**Comment by cr998** [comment]
NMI (need more info), please attach yout log files
