### ISSUE TITLE
Notable exception in modlist

### ISSUE THREAD

**Issue by squishey123** [FTBTeam/FTB-Ultimate-Reloaded#294]
Logistics Pipes is now available for 1.12 and feels like a necessity for how important of a mod it has been since 1.4.7 and before. Would love to see it added to the pack!

https://www.curseforge.com/minecraft/mc-mods/logistics-pipes

**Comment by tfox83** [comment]
During our early testing we had huge performance issues.  Also LogPipes wasn't in FTB Ultimate.  However I do agree it would be a good fit in the pack.  We may try testing the mod in the pack again once its in a more stable state and possibly get it added.
