### ISSUE TITLE
I cant download the modpack. it just doesn't download.(this may be on twitch's part)

### ISSUE THREAD

**Issue by barharanargar** [FTBTeam/FTB-Ultimate-Reloaded#296]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by cr998** [comment]
More Info please

**Comment by gadjio** [comment]
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 74072

**Comment by ktole1999** [comment]
this is a twitch issue. try again later.
