### ISSUE TITLE
Thermal Expansion Issues

### ISSUE THREAD

**Issue by jakethesnake1989** [FTBTeam/FTB-Ultimate-Reloaded#299]
* **Modpack Version**: 1.7.1 (Current) and even tried 1.8 (Beta) and had same issue

* **Issue**: Upon first installation of modpack or reinstallation, using pulverizers and other Thermal Expansion items is flawless. After second load of modpack, the top input in the Pulverizer or Redstone furnace (only ones tried so far, may be more items affected) as well as the auto-input option only, are unusable. Meaning, I can toggle auto-export, the orange, but I cannot change the auto-input, and it is stuck off, meaning a hopper is required which takes more space. Also, some of the items in Thermal Expansion and other items in JEI, when hovered over, do not allow you to click on them. It is the same issue with all of these places, when I hover over the auto input, the top port, or some of the other items in JEI, nothing pops up and they are unselectable. It is frustrating to have to reinstall the mod pack to fix it, and then reload the modpack and find that it no longer works.

* **Link to Log or Crash File Paste**: There is no crash, only not working items as aforementioned.

* **Is it Repeatable?**: I have reinstalled the modpack to fix it in both the current release and the 1.8 beta and after loading the modpack a second time it is broken again.

* **Mod/s Affected**: To my knowledge, Thermal Expansion is the only mod I have encountered that is affected. (Other than building my house, trying to solve this issue has taken much of my time and I have not encountered more mods with this issue yet)

* **Known Fix**: As I said, I can reinstall the mod pack to fix it, but if I reload the modpack after closing it off of the initial first start, it reverts to the issue.

**Comment by tfox83** [comment]
Thats strange, I am not able to reproduce this nor have I seen any reports like this.  Ill leave it open for now incase anyone runs into this issue we can dive deeper into it.
