### ISSUE TITLE
Update Aroma Mining Dim 

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-Ultimate-Reloaded#3]
* **Modpack Version**:  1.0.0

* **Issue**:  So That you can remove water from the mining dim, Aroma said that the mod is stable just marked as alpha for below reason

* **Known Fix**:  Would need to say that you need to restart the mining dim would but if this comes out soon i dont think that would be an issue

**Comment by tfox83** [comment]
Fixed in dev, will be in next update, probably Thursday

**Comment by tfox83** [comment]
actually this will come out today in 1.0.1

**Comment by tfox83** [comment]
Update 1.0.1 released
