### ISSUE TITLE
Coal coke

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#30]
* **Modpack Version**: 1.0.1
* **Issue**: there are 2 types of coal coke being produced: TE and Railcraft
> one from the railcraft coke oven
> other from the pyrolitic augment upgraded TE redstone furnace
* **Is it Repeatable?**: yes

* **Mod/s Affected**: all

* **Known Fix**: crafttweaker recipe fix

**Comment by tfox83** [comment]
Its fine, they are oreDict.  Use can use either in recipes or for fuel
