### ISSUE TITLE
Forestry stamp_collector located on trees.

### ISSUE THREAD

**Issue by MGlolenstine** [FTBTeam/FTB-Ultimate-Reloaded#300]
* **Modpack Version**: 
1.7.1
* **Issue**: 
Forestry stamp_collectors located on the bottom side of trees, facing upwards, don't have a texture. https://cdn.discordapp.com/attachments/380778299020017676/611985277874864138/20190816_201046.jpg
* **Link to Log or Crash File Paste**: 
No logs...
* **Is it Repeatable?**: 
Yes, they're everywhere, just start a new world.
* **Mod/s Affected**: 
Forestry
* **Known Fix**: 
None yet.

**Comment by tfox83** [comment]
Could you try a fresh install of the pack, I am not able to reproduce this.  Also the mod has been updated in the next beta which will be public in a couple days, that could possibly fix your issue
