### ISSUE TITLE
Clients Freeze when a torch breaks a lever on a Redstone Engine

### ISSUE THREAD

**Issue by Ryleyy** [FTBTeam/FTB-Ultimate-Reloaded#302]
* **Modpack Version**: 1.7.1
* **Issue**: When a lever is connected and powering a redstone engine, once you place a torch on the same block as the lever and the lever breaks it freezes every client in the server and they must restart.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/31167b13

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: Closing the .game entirely and restarting. The lever is on the ground as a dropped entity and the torched is in the placed spot

**Comment by 016Nojr** [comment]
Unfortunately this issue is still present, but it wont be fixed because the mod author isnt working on the version anymore
