### ISSUE TITLE
Buildcraft Engines Facing up

### ISSUE THREAD

**Issue by parkitka** [FTBTeam/FTB-Ultimate-Reloaded#303]
* **Modpack Version**:  FTB Ultimate Reloaded 1.12.2

* **Issue**: Any kind of buildcraft engine orientation can`t be changed. If I attach them to quarry they do self allign, however if I try to connect one engine to another it does not work. **No kind of wrench can change its direction either**, unless they self allign I cannot use them properly. I **made sure** that this problem occurs in pure version of this modpack (at least at my pc) .

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d7a58134

* **Is it Repeatable?**: Yes, its kinda eternal 

* **Mod/s Affected**: Buildcraft (I also use Projecte and openblocks but for the sake of this bug I deleted them and re-installed the modpack just to make sure that none of them cause the problem 

* **Known Fix**:

**Comment by parkitka** [comment]
Here is a short video showing the problem
https://youtu.be/tQHUclU6k8U

**Comment by parkitka** [comment]
Why closed when nobody answered?

**Comment by ktole1999** [comment]
daisy chaining engines doesnt work anymore.
