### ISSUE TITLE
Some Recipes not working on server

### ISSUE THREAD

**Issue by Don-Chris** [FTBTeam/FTB-Ultimate-Reloaded#304]
Some Recipes like 
- "Empty Cell" from IC2, 
- "FE Energy Producer" from Energy Converters, 
- "Pump" from Buildcraft 
aren't working when playing on the server. When playing in Singleplayer, crafting isn't a problem.

* **Modpack Version**: 1.8.0 and 1.7.1 

* **Issue**: Recipes when put correctly in the crafting table can't be crafted.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: I Found no Fix for it

**Comment by huskies62** [comment]
Did you ever find a solution for this?
