### ISSUE TITLE
Lost items in JEI

### ISSUE THREAD

**Issue by Fryderyk01** [FTBTeam/FTB-Ultimate-Reloaded#305]
There is a problem with my JEI. He doesn t show all of recipers for example in immersive engineering I have about a half of all recipes. is here someone else who have the same problem ore can help me ??
* **Modpack Version**: Version which is now inplement in MP Luncher  
* **Issue**: missing recipes in JEI

* **Link to Log or Crash File Paste**: I dont know I don t have
* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by ktole1999** [comment]
items have been disabled and hidden due to pack difficulty.

**Comment by squishey123** [comment]
From what I can tell either recipes have been changed or hidden for the Engineers workbench and manual. Other recipes that seem hidden but are craftable are the Thermal Foundation cables that require a fluid transposer. Immersive engineering seems fairly unusable without any sort of guide other than outdated wiki pages

**Comment by Fryderyk01** [comment]
Thx

czw., 22 sie 2019 o 19:58 squishey123 <notifications@github.com> napisał(a):

**Comment by NiallDoherty** [comment]
Thinking about it, what exactly is the point of immersive engineering in this pack? The only thing I've come across is pulverized uranium which can be replaced with crushed uranium from ic2...

**Comment by tfox83** [comment]
The power wires were heavily requested during testing as it fit well with all the train stuff players were using.  Also windmills were in 1.4 Ultimate and we were able to use IE's windmill, not exactly the same, but had a similar feel to the original 1.4 Ultimate.
