### ISSUE TITLE
IC2 Miner Bug

### ISSUE THREAD

**Issue by squishey123** [FTBTeam/FTB-Ultimate-Reloaded#306]
* **Modpack Version**: 1.8.0 (Release)

* **Issue**: When the IC2 Miner has finished work and you remove the drill (I used the Tech Reborn Advanced Drill) The miner gets progressively more loud while retracting the mining pipes and it also returns far more than it used during work. For Example, I'm in the Aroma1997 mining dimension at y80, put in 63 mining pipes and after fully retracting (And blowing out my eardrums from how loud it gets) I get 500 mining pipes back (7x64+52)

**Comment by 016Nojr** [comment]
Hopefully this bug has been fixed with the new pack update coming in a few days, the mod isnt getting any updates for 1.12
