### ISSUE TITLE
IC2 Not usable at all in survival

### ISSUE THREAD

**Issue by Seraphyel** [FTBTeam/FTB-Ultimate-Reloaded#307]
* **Modpack Version**: Last FTB Ultimate Reloaded
* **Issue**: IC2 Is just useless because it seems that on the classic version you just can´t get the base materials to craft any machine at all. For example; you try to create a macerator wich is a basic machine to optimize your mineral output. But you need a *machine casing* wich requires *Refined Iron* wich is crafted on a *blast furnace* wich requires a *machine casing*. So you need to craft a *machine casing* to craft a *machine casing*. Its just useless if you want to play a survival made party. 

* **Is it Repeatable?**:  Actually you can try anytime, JEI only has classic IC2 items so you can only get the through credits (that you actually need to craft machines to earn them and you CAN NOT craft any machine) or though transmutation (wich requires diamonds and transmutation shads wich are preety hard to find elite items).

* **Known Fix**: Maybe update the pack to the advance version of IC2? That would be the only answer to make it playable at all.

**Comment by ethand8** [comment]
You can put iron in a regular furnace to create Refined iron, a blast furnace is just an upgraded regular furnace

**Comment by Seraphyel** [comment]
> You can put iron in a regular furnace to create Refined iron, a blast furnace is just an upgraded regular furnace
Ok,, the recipies were not shown properly. Anyway, I feel like an idiot. Thanks ethand8.
