### ISSUE TITLE
GraviChestPlate Creative Flight doesn't work

### ISSUE THREAD

**Issue by Fadirstave** [FTBTeam/FTB-Ultimate-Reloaded#308]
GraviChestPlate working as if its an expensive jetpack, creative flight doesn't work. 

* **Modpack Version**: 1.8.0

* **Issue**: @GraviChestPlate Creative Flight doesn't work

**Comment by tfox83** [comment]
Holding space to fly then pressing IC2 mode key (check controls should be M default) will switch into hovermode, which is creative flight

**Comment by tfox83** [comment]
![2019-09-04_10 41 16](https://user-images.githubusercontent.com/4246308/64278054-b3807280-cf00-11e9-99c9-011653ff180a.png)
