### ISSUE TITLE
Techreborn glass fiber cable missing. 

### ISSUE THREAD

**Issue by egohommeli** [FTBTeam/FTB-Ultimate-Reloaded#309]
* **Modpack Version**: 1.8.0

* **Issue**: No sign of tech reborn glass fiber cable. It is in config files but cannot find it ingame.

* **Is it Repeatable?**: Yes

**Comment by NiallDoherty** [comment]
It's not in because tech reborn cables transfer RF and the mod is configured to use EU in this pack

**Comment by egohommeli** [comment]
Oh okay. 
I tested with my other pc and there I can find it in game (recipe for it shows too) but it cannot be crafted. It also says when hovering mouse over it that it handles 8192 EU/t and is extreme -tier. It would be nice if it worked that way cause using AESU’s as a cable with quantum solar is pretty expensive. :D

**Comment by tostamista23** [comment]
In >1.8.0, we have superconductor cable but doesnt show on JEI
Recipe: http://puu.sh/EazDg/b4583257f4.jpg (right click)
Recipe 2: http://puu.sh/EazFr/3067db8bd4.png (need fusion size 50)

**Comment by egohommeli** [comment]
Thank you!
