### ISSUE TITLE
problem with the industrial blast furnace 

### ISSUE THREAD

**Issue by d7oomgam3r** [FTBTeam/FTB-Ultimate-Reloaded#310]
* **Modpack Version**: <1.8.0>

* **Issue**: < the industrial blast furnace does not get more than 2880 with all advanced casing and 2 sources of lava inside so i cant make the hot tungstensteel ingot>

* **Link to Log or Crash File Paste**: < NO >

* **Is it Repeatable?**: < yes >

* **Mod/s Affected**: < Tech reborn >

**Comment by tostamista23** [comment]
Now we need to use coils

A stack of 4 Kanthal Heating Coils(KHC) right-clicked on the furnace block adds another 500 K.
After the 4 KHCs, 4 Nichrome Heating Coil(NHC) can be right-clicked on the furnace to add a final 500 K.

font: https://feed-the-beast.fandom.com/wiki/Industrial_Blast_Furnace (is not from tech reborn but works the same way)

**Comment by tfox83** [comment]
pedrotest1 is correct, thanks!
