### ISSUE TITLE
FTB Utils config reset

### ISSUE THREAD

**Issue by Fadirstave** [FTBTeam/FTB-Ultimate-Reloaded#311]
* **Modpack Version**: 1.8.0

* **Issue**: Can't edit config of FTB Util

This issue occurs even if the config is edit while the server is down.

The mod pack profile is unlocked

A simple video to show you my issue https://www.dropbox.com/s/ux19vx5kykhzjkk/cvryngGby2.mp4?dl=0

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: FTB Utils

* **Known Fix**: None

**Comment by tfox83** [comment]
Hmm let me have @LatvianModder take a look at this, seems something maybe overriding that setting.

**Comment by LatvianModder** [comment]
Try shutting down server, changing the value, then turning server back on

**Comment by tfox83** [comment]
"This issue occurs even if the config is edit while the server is down." 

I think he has tried that already @LatvianModder

**Comment by LatvianModder** [comment]
Oh, didn't see. Hmm. There is nothing in code that changes afk value so it might be config loading itself that is broken. I will try to replicate in my dev env

**Comment by LatvianModder** [comment]
Issue on mod GitHub: https://github.com/FTBTeam/FTB-Utilities/issues/1023

**Comment by LatvianModder** [comment]
See if this version works https://jenkins.latmod.com/job/FTB-Utilities/104/
