### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Keopha** [FTBTeam/FTB-Ultimate-Reloaded#312]
* **Modpack Version**: Latest version of the modpack (1.12.2 is the only version number I can find)

* **Issue**: After clicking on my save, it loads, and then crash without even loading the map

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7df434d3

* **Is it Repeatable?**: Yes, it does that everytime I start the game

**Comment by tostamista23** [comment]
Try changing render distance to 12 or lower

**Comment by tfox83** [comment]
Is this still a problem after lowering your render distance? Does this happen with a new world?

**Comment by Keopha** [comment]
Hello yes every time I start a new world It crashes whatever the render distance but then I can load it

Le 4 sept. 2019 à 19:01, tfox83 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Is this still a problem after lowering your render distance? Does this happen with a new world?

**Comment by will-blk** [comment]
Just a guess, are you using any config file for invtweaks? Try removing it if so. Looks like its trying to load a slot that doesn't exist.
