### ISSUE TITLE
i can't download 

### ISSUE THREAD

**Issue by lionszzs** [FTBTeam/FTB-Ultimate-Reloaded#314]
hello i can't download the modpack it says downloading now but it doesn't download

**Comment by tfox83** [comment]
Which launcher are you using?  Do other packs download?

**Comment by lionszzs** [comment]
I am trying to download via twitch's website and no other packs download.

**Comment by ctbdtb** [comment]
I am also having this issue any fixes?

**Comment by ktole1999** [comment]
the issue is with Twitch, not the pack.
