### ISSUE TITLE
Crashing when starting the game

### ISSUE THREAD

**Issue by hackexblog** [FTBTeam/FTB-Ultimate-Reloaded#315]
* **Modpack Version**: 1.8.0

* **Issue**: Insta crashing on start

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/74315526
* **Is it Repeatable?**: yes
* **Mod/s Affected**: not sure

**Comment by tfox83** [comment]
Could you please try a fresh install and make sure you are using the latest version of Java 8.  I am not able to reproduce this.  If it still fails a new version will be coming to beta in a couple days.

**Comment by hackexblog** [comment]
The issue was twitch. i deleted the (vanilla) 1.12 files in the twitch folder and that fixed it
