### ISSUE TITLE
Crossbow missing

### ISSUE THREAD

**Issue by Wakizashimaster** [FTBTeam/FTB-Ultimate-Reloaded#316]
* **Modpack Version**: 1.8.0

* **Issue**: "Vanilla" Minecraft Crossbow missing from crafting. As per the recipe linked here
https://minecraft.gamepedia.com/Crossbow 

* **Is it Repeatable?**: Yes, its never been available.

* **Mod/s Affected**: Base.

**Comment by tostamista23** [comment]
> Yes, its never been available.

because crossbow is only for 1.14+ and minecraft modpack version is 1.12?

**Comment by tfox83** [comment]
Correct the crossbow is not a 1.12 feature
