### ISSUE TITLE
Silktouching ripe Hill Cherry Leaves crashes client.

### ISSUE THREAD

**Issue by Dinomannen** [FTBTeam/FTB-Ultimate-Reloaded#317]
Version 1.8
After using a sickle with silktouch on the leaves of a Hill cherry Tree with ripe fruit on it the client crashed.
Crash log description: "Rendering entity in world"
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 14525620
	Entity Name: item.tile.for.leaves.default.fruit.0
	Entity's Exact location: 1000.43, 72.72, -6743.40
	Entity's Block location: World: (1000,72,-6744), Chunk: (at 8,4,8 in 62,-422; contains blocks 992,0,-6752 to 1007,255,-6737), Region: (1,-14; contains chunks 32,-448 to 63,-417, blocks 512,0,-7168 to 1023,255,-6657)
	Entity's Momentum: -0.03, 0.20, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

I had "Coin of Fortune" that transfered the item that caused the crash to my inventory before the server had completely registered my client disconnecting. And everytime i logged in and tried to open an interface that would show my inventory the client crashed.
Crash log description: "CCL Has caught an exception whilst rendering an item."
Item Class:     class forestry.arboriculture.items.ItemBlockLeaves
  Registry Name:  forestry:leaves.default.fruit.0
  Metadata:       3
  NBT:            null
  Model Class:    class net.minecraftforge.client.model.PerspectiveMapWrapper
  Model Location: forestry:leaves.default.0#inventory

This Error was fixed by deleting the item from the inventory in the player .dat file.
The Error was reproduced without fail on single player world and when "Coinf of Fortune"(or similar items) caused the item that crashes the game to be pulled to the inventory, the error behaves as above, when the item is left on the ground the game crashes as it tries to load in to the world again.
No mods beside the ones that comes with the modpack and no resource packs are being used.

**Comment by tostamista23** [comment]
#279
