### ISSUE TITLE
feedthebeast ultimate reloaded outdated?

### ISSUE THREAD

**Issue by jonte141** [FTBTeam/FTB-Ultimate-Reloaded#318]
-->

* **Modpack Version**: 1.8.0

* **Issue**:  it says i need my mods updated to join my own server but ive been spamming update in the twitch launcher and nothing happens

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  yes because i need my mods updated

* **Mod/s Affected**:  

* **Known Fix**:

**Comment by tostamista23** [comment]
[1.9.0](https://www.feed-the-beast.com/projects/ftb-ultimate-reloaded/files/2778968) came out yesterday
