### ISSUE TITLE
Uncraftable items (maby because of recipe collisions)

### ISSUE THREAD

**Issue by sevsev9** [FTBTeam/FTB-Ultimate-Reloaded#319]
* **Modpack Version**: Twitch Latest: 1.8.0

* **Issue**: Most of Immersive Engineering's Items are not craftable.

* **Is it Repeatable?**:  Yes even after complete reinstall of both server and client.

You cannot craft most of IE's items:

Engineering Blocks (all)
Engineers Workbench
Engineers Manual
Blast Brick (&Reinforced)
Water Wheel
Turnable
Reinforced Stone Crate
Gunpoweder Barrel
Item Router
Fluid Router
Wooden Barrel
Wooden Storage crate
Kiln Brick
Insulating Glass
Leaded Concrete
Reinforced Blast Brick Slab
Copper Coil Block
Electrum Coil Block
HV Coil Block
Light Engineering Block
Generator Block
Radiator Block
...

* **Mod/s Affected**: 
Immersive engineering

* **Known Fix**: -

* **Logs from Server Start** *:
[debug.log](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3586540/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3586541/latest.log)

**Comment by ktole1999** [comment]
they are turned off in the pack due to original pack preservation. not a conflict.
