### ISSUE TITLE
QOL fix

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#32]
* **Modpack Version**: 1.0.1

* **Issue**: The pack has 4 different types of power:
> ic2: EU
> TE: RF
>BC: MJ
>RC: charge

* **Is it Repeatable?**: yes

* **Mod/s Affected**: all

* **Known Fix**: Please enable compatibility between these mods, having MJ is nearly pointless as there is no way to transfer it to other types of power.

**Comment by tfox83** [comment]
No, sorry that is intended.

**Comment by tfox83** [comment]
also look up the mod energy converters it supports all but RC charge currently and is in the pack

**Comment by EthernalVoid** [comment]
Will do, thanks
