### ISSUE TITLE
World is gone/corrupted after crash

### ISSUE THREAD

**Issue by Dreikas1** [FTBTeam/FTB-Ultimate-Reloaded#321]
* **Modpack Version**: 1.7.1

* **Issue**: After the crash world was not displayed in the menu but the file of the world still exists

* **Link to Log or Crash File Paste**: [2019-09-12-1.log.gz](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/3607481/2019-09-12-1.log.gz)
/ 

* **Is it Repeatable?**: No

* **Mod/s Affected**: None

* **Known Fix**: There is no known fix

**Comment by tfox83** [comment]
Please paste your logs per instructions.  I am not able to help.
