### ISSUE TITLE
Gravichestplate not working as intended

### ISSUE THREAD

**Issue by Keciam75** [FTBTeam/FTB-Ultimate-Reloaded#322]
* **Modpack Version**: 1.8.0
* **Issue**: The Gravichestplate doesn't seem to have the creative flight mode as it probably should. Instead it acts like a simple jetpack.

* **Link to Log or Crash File Paste**: ----

* **Is it Repeatable?**: yes

* **Mod/s Affected**: ----

* **Known Fix**: ----

**Comment by tfox83** [comment]
Duplicate https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/308
