### ISSUE TITLE
Can't find the crop harvester 1.8.0

### ISSUE THREAD

**Issue by Zoukani** [FTBTeam/FTB-Ultimate-Reloaded#323]
* **Modpack Version**: 1.8.0

* **Issue**: Crop Harvester missing ?

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IC2

So i was trying to go on some cross breeding for a farm, but then i saw that the crop harverster was missing ? Any info on that ?

BR
Zoukani

**Comment by hizokuto** [comment]
The pack is a throw back to FTB Ultimate from 2014, and has some mods nerfed back to resemble it. So you might be meant to use Industrial Foregoing as the had Minefactory Reloaded. There's also Steve's Carts and the Forestry farm multi block. Notice that you don't even have the crop sticks to cross breed in the first place, let alone the harvester for IC2.

Funnily, the Forestry multiblock farm would be nice for early to mid game, if it weren't for the pump being broken for me. Lava cells in an industrial centrifuge for a ton of tin+copper = bronze for a lot of machine casings or parts.

**Comment by tfox83** [comment]
It is not avail when set to classic mode.
