### ISSUE TITLE
Plutonium and Thorium Recipes

### ISSUE THREAD

**Issue by Generic505** [FTBTeam/FTB-Ultimate-Reloaded#325]
Modpack Version: 1.9.0

Issue: Recipe for Plutonium or Thorium fuel rods

Is it Repeatable?: Yes

Mod/s Affected: Tech Reborn

JEI shows that the items exists, but it doesn't give me a crafting recipe for either one

**Comment by Shotguun29** [comment]
Same here bro. Kinda annoying.

**Comment by RedCorpIndustry** [comment]
I think they are not yet implemented in Tech Reborn itself

**Comment by Barhandar** [comment]
They're not implemented. Allegedly IC2's Classic profile cannot run them, even though 1.4.7's IC2+GT could have them just fine (thorium is 5x durability 1/5 energy output, plutonium is 2x durability and 2x output).

**Comment by Generic505** [comment]
Well damn...

So is there any use for the depleted uranium rods?

**Comment by tfox83** [comment]
They are not implemented, and since devs aare moving to 1.14 I doubt we will see that in 1.12
