### ISSUE TITLE
Redstone furnace smelting any Log into Jungle Log

### ISSUE THREAD

**Issue by SuperCuber** [FTBTeam/FTB-Ultimate-Reloaded#326]
* **Modpack Version**: 1.9.0

* **Issue**: Sometimes the redstone furnace will output Jungle Wood as the output to smelting any type of wood. This is also reflected in JEI, where all the other smelter blocks will correctly output charcoal.

* **Is it Repeatable?**: Happens occasionally, stays until restarting the client

* **Known Fix**: Restarting the client

**Comment by tfox83** [comment]
Sorry I am not able to reproduce, please try a fresh install of the client and see if it still happens.  Thanks
