### ISSUE TITLE
Blast Furnace Inventory. 1.9.0 

### ISSUE THREAD

**Issue by Shotguun29** [FTBTeam/FTB-Ultimate-Reloaded#327]
* **Modpack Version**: 1.9.0

* **Issue**: Inventory Glitch with (multi block) blast furnace. Items getting duplicated (sometimes). Cannot access inventory w/Blast furnace right after log in (every time). Single player, windows.

* **Link to Log or Crash File Paste**:  n/a

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Railcraft..

* **Known Fix**:  Braking a block and replacing it.

**Comment by tfox83** [comment]
Try moving the multiblock to within one chunk.  Press F9 I believe to show chunk boundaries.  This is a known issue
