### ISSUE TITLE
Industrial Foregoing (Fluid Pump and Range Addon) 1.9.0

### ISSUE THREAD

**Issue by hizokuto** [FTBTeam/FTB-Ultimate-Reloaded#328]
* **Modpack Version**: 

* **Issue**: Industrial Foregoing Fluid Pump not pumping and ignores Range Addon. When a Fluid Pump is first placed and powered, it detects the lava source block as shown in the bucket filter. However, it does not start pumping. Adding the range addon does not start pumping. Interestingly, removing the Range Addon seems to "update" the Fluid Pump and cause it to pump 1 source block somewhere below it. By cycling the Range Addon in the GUI, one can "manually pump" only the vertical column of source blocks under the pump until it cobbles up to itself. 

So the range add on seems to work vertically in a column, but not horizontally. A related observation is an instance where the Fluid Pump works, but then pauses indefinitely when a chuck gets reloaded, such as when closing and reopening the game. Similar to all other cases, toggling the play/pause in GUI doesn't affect this.

* **Is it Repeatable?**: Yes. 

* **Known Fix**: Previous community fixes of replacing the block over other lava sources, or placing blocks in certain orders no longer work. For example, placing the pump, range addon, and THEN adding power was a work around to prevent the pump from cobbling up to itself and getting stuck before the range add on could be placed. Instead, the pump doesn't even cobble up to itself. Cycling the play/pause in the GUI didn't work

I renabled the BC Pump on my singleplayer world  instead, despite it being inferior to continue with my game.

**Comment by tfox83** [comment]
I do not have these issues, try powering with RF.  Also make sure you are not in a claimed area.
