### ISSUE TITLE
Sorting Tech Reborn cells with diamond pipe

### ISSUE THREAD

**Issue by TeeCape** [FTBTeam/FTB-Ultimate-Reloaded#329]
* **Modpack Version**:  1.9.0

* **Issue**:  Sorting the Distillation tower output ( Diesel Cell, Sulfuric Acid Cell and Glyceryl Cell ) with a diamond pipe does not work. The cells just went through, like in a normal transport pipe juction. In a minimum example, a bunch of other cells (Hydrogen, Lava, Compressed Air) of the Tech Reborn mod behaved in the same way. So far all tested cells behave like this.   

* **Link to Log or Crash File Paste**:  Not applicable.

* **Is it Repeatable?**:  Yes.

* **Mod/s Affected**:  Tech Reborn, BuildCraft Transport

* **Known Fix**:  For the described set up there is no fix known to me.

**Comment by tfox83** [comment]
That is due to NBT, please use a different sorting method that supports NBT data
