### ISSUE TITLE
No Charged Certus Quartz Crystal or Ore?

### ISSUE THREAD

**Issue by LashBane** [FTBTeam/FTB-Ultimate-Reloaded#330]
* **Modpack Version**: < FTBUltimateReloaded-1.9.0-1.12.2>
* **Issue**: <Charged Certus Quartz Crystal does not exist>
* **Mod/s Affected**: <AppliedEnergetics>

Neither Charged Certus Quartz Crystal or Ore spawns in my game. I even tried to get some via console command but it could not find the item (unsure if it's even in the library?) Did i miss some kind of changelog when it was removed? Just started with this modpack like a month ago.

**Comment by Chameebling-zz** [comment]
AE2 in this modpack is at the lowest difficulty, so all charged certus quartz recipes would use regular certus quartz.

**Comment by tfox83** [comment]
Chameebling is correct, charged certus quartz isnt needed in this pack
