### ISSUE TITLE
Minecraft Won't Launch

### ISSUE THREAD

**Issue by Shisoku** [FTBTeam/FTB-Ultimate-Reloaded#332]
Modpack Version: 1.9.0

Issue: When Launching FTB Ultimate Reloaded Version 1.9.0 through the Twitch Windows Application, the Task Manager will show Minecraft Launcher opening, but shortly after it will Suspend itself and disappear. This happens on the first launch of the modpack, right after it was installed through Twitch. I've tried uninstalling the modpack, Minecraft, and Twitch multiple times. Each time it will crash itself before launching Minecraft.

Issue is Repeatable

**Comment by tfox83** [comment]
The issue is probably with the Twitch launcher, try using the FTB launcher instead to see if that fixes your issue.  Launcher download link: http://ftb.forgecdn.net/FTB2/launcher/FTB_Launcher.jar
