### ISSUE TITLE
(Minor AE2 bug) Pattern Terminal adding Pure Certuz/Pure Nether Quartz Crystal instead of regular crystals.

### ISSUE THREAD

**Issue by thaffy** [FTBTeam/FTB-Ultimate-Reloaded#333]
* **Modpack Version**: Current

* **Issue**: When creating patterns for AE2 Components it will register the Certus Quartz Crystal as a Pure Certus Quartz crystal when using "fill items" from JEI. The issue is fixed by manually removing the Pure crystals and inserting the usable ones 

* **Link to Log or Crash File Paste**: N/A 

* **Is it Repeatable?**: Yes 

* **Mod/s Affected**: AE2 

* **Known Fix**: No known fix, but to get around it - Just manually adding the recepie (Not using fill items) or using fill items and then replacing the Pure Crystals

**Comment by tfox83** [comment]
You have to manually set the recipes, there is nothing I can do about that easily, sorry

**Comment by thaffy** [comment]
No worries, its more of a heads up than a complaint/major bug/major problem so to say 👍
