### ISSUE TITLE
Assembling Machine recipes

### ISSUE THREAD

**Issue by AstroSnout** [FTBTeam/FTB-Ultimate-Reloaded#334]
* **Modpack Version**: 1.9.0

* **Issue**: JEI does not display correct recipes for TechReborn's Assembling Machine.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: TechReborn or JEI

* **Known Fix**: The recipes still function, it's just the display that is wrong. I will provide an example as a screenshot.

It appears that the culprit here is TechReborn's Advanced Electronic Circuit (AEC in further text). When checking what one can use it for, you get recipes that don't display the actual item, but you can use them in recipes shown.

This is what JEI displays when looking what AEC can be used for:
![AEC Recipes](https://user-images.githubusercontent.com/26722560/66849139-b1d1b200-ef76-11e9-99c4-d4bcd96ae1af.PNG)

Upon trying to actually use AEC with Thermal Foundation's Platinum Plate, I get the correct item. The other item (Other than TF's Plat Plate) is another plat plate, but from TechReborn (which is uncraftable and doesn't actually appear in the JEI sidebar).
![Actual Recipe](https://user-images.githubusercontent.com/26722560/66849142-b1d1b200-ef76-11e9-9be3-11adb7292678.PNG)

**Comment by 016Nojr** [comment]
This is fixed in an upcoming update
