### ISSUE TITLE
Some of the recipes (IC2 UUM gold/iron and tin/copper, TR-IC2 interchange) are wrong

### ISSUE THREAD

**Issue by Barhandar** [FTBTeam/FTB-Ultimate-Reloaded#336]
* **Modpack Version**: 1.9.0

* **Issue**: UniDict doesn't correctly shape the IC2 UUM recipes in question and fails to leave voids, so instead of the intended shapes it's just five/three UUMs in a row, leaving iron and copper ores uncraftable and iridium recipe wrong (IC2 does not have recipe for lead to conflict with). TechReborn UUM recipes are fine, for some reason, and have the correct relevant shapes.  
Plate interchange recipes use incorrect metadata, resulting in magnalium-iridium alloy and refined iron-advanced plate exchanges instead of correct iridium-iridium and advanced-advanced.
There are two recipes for TRUUM platinum dust, one by UniDict, the other by CraftTweaker

* **Link to Log or Crash File Paste**: None.
![ic2uum](https://user-images.githubusercontent.com/2338212/67269123-c2c27c00-f4be-11e9-9b96-66d5593c913e.PNG)
![truum](https://user-images.githubusercontent.com/2338212/67269134-c8b85d00-f4be-11e9-8785-b822151bf0bb.PNG)
![truum2](https://user-images.githubusercontent.com/2338212/67269140-cc4be400-f4be-11e9-80f1-876a20fbf5fb.PNG)

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: TechReborn, IC2. 

* **Known Fix**: None known for UniDict issue (manually overriding with CT might work), for CT issues amend the relevant code in ic2.zs and remove duplicate platinum recipe from it:
```
#swap between iridium reinforced plates
//37 was magnalloy plate, 38 is iridium.
recipes.addShapeless(<ic2:crafting:4>, [<techreborn:plates:38>]); 
recipes.addShapeless(<techreborn:plates:38>, [<ic2:crafting:4>]);

#switch between advanced alloys
//35 is refined iron plate, 36 is advanced alloy
recipes.addShapeless(<ic2:crafting:3>, [<techreborn:plates:36>]);
recipes.addShapeless(<techreborn:plates:36>, [<ic2:crafting:3>]);
```

**Comment by 016Nojr** [comment]
Closing this, another issue regarding this issue is still open.
