### ISSUE TITLE
[Feature Request] (CraftTweaker) Add Certus Crystal Ore to Macerator (1:2 / ore:crystal)

### ISSUE THREAD

**Issue by MuriloGhignatti** [FTBTeam/FTB-Ultimate-Reloaded#337]
Modpack Version: 1.9.0

Issue: Just edit a config

Link to Log or Crash File Paste: Don't Need

Is it Repeatable?: Yes?

Mod/s Affected: IndustrialCraft2 and AppliedEnergistics 2

Known Fix: Add to crafttweaker config

**Comment by 016Nojr** [comment]
Added in an upcoming pack update
