### ISSUE TITLE
[Issue] Overclock IC2 Tier 2 Machines

### ISSUE THREAD

**Issue by MuriloGhignatti** [FTBTeam/FTB-Ultimate-Reloaded#338]
* **Modpack Version**: 1.9.1

* **Issue**: Can't put Overclocks in Tier 2 IC2 Machines (Induction Furnace, Rotary Macerator, Singularity Compressor and Centrifugue Extractor)

* **Link to Log or Crash File Paste**: Not crash-related

* **Is it Repeatable?**: Put on of the machines that was mentioned above and try to put any Overclock in the space you normaly would put it.

* **Known Fix**: I don't know how to fix that

**Comment by Barkorgb** [comment]
You cannot add Overclock upgrades to T2 IC2 machines anyway.

**Comment by 016Nojr** [comment]
Advanced Machines arent supposed to be overclocked
