### ISSUE TITLE
CF Sprayer durability goes to negative and produces unlimited construction foam

### ISSUE THREAD

**Issue by Chameebling-zz** [FTBTeam/FTB-Ultimate-Reloaded#340]
* **Modpack Version**: 1.9

* **Issue**: Because of how the durability system is designed on the CF sprayer, a change made it so that it loses durability by -100 with full durability starting at 0, this going to the negatives.

* **Link to Log or Crash File Paste**: There are no logs associated with this issue, but I do have screenshots
![2019-11-06_20 46 21](https://user-images.githubusercontent.com/49128957/68361917-5e1c3980-00da-11ea-9556-0f22eca7f493.png)
![2019-11-06_20 46 49](https://user-images.githubusercontent.com/49128957/68361919-5e1c3980-00da-11ea-9e01-4c38f36dc31c.png)

* **Is it Repeatable?**: Yes it is easily repeatable

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by 016Nojr** [comment]
Fixed in an upcoming pack update
