### ISSUE TITLE
Buildcraft Fuel Not Accepted By Railcraft Liquid Fueled Fireboxes

### ISSUE THREAD

**Issue by GitDubz4Nubz** [FTBTeam/FTB-Ultimate-Reloaded#341]
* **Modpack Version**: 1.9

* **Issue**: Buildcraft fuel won't work with Railcraft Liquid Fueled Fireboxes to generate steam. 

* **Is it Repeatable?**: Try to use build-craft fuel to fuel a liquid fueled firebox.

* **Mod/s Affected**: Buildcraft, Railcraft

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I can unfortunately not do anything with it as the mod version isnt supported anymore
