### ISSUE TITLE
JEI still showing disabled Immersive Engineering Recipes

### ISSUE THREAD

**Issue by zedekblue** [FTBTeam/FTB-Ultimate-Reloaded#345]
* **Modpack Version**: 1.9.0
* **Issue**: JEI is still showing disabled multiblock machines (IE) as viable ways to produce many items such as gears, plates, etc.. Issue has been brought up a number of times but never pointed out the main issue, the reason these people are trying to make the items in the first place.
#319 #305 #256 

Removing these recipes from JEI should help prevent people from trying to make the structures to begin with.

**Comment by 016Nojr** [comment]
Looking into fixing this, closing this
