### ISSUE TITLE
Tech Reborn Micro Tier shows incorrect Input Rate

### ISSUE THREAD

**Issue by zedekblue** [FTBTeam/FTB-Ultimate-Reloaded#346]
* **Modpack Version**: 1.9.0

* **Issue**: Wire Mill & Assembling Machine both show an input rate of 32 eu/t, however show their tier as Micro, which I believe is only 8 eu/t. Both of these machines will explode when attached to an LV (32eu/t) current.

**Comment by arawden** [comment]
Is it even possible to transform down to 8 eu/t? Are these machines usable at all?

**Comment by zedekblue** [comment]
@arawden 
You cannot transform down to 8eu/t, however you can generate 8eu/t. I simply used 8 tier 1 solar panels to run them. You can also upgrade them with a transformer augment to accept 32 eu/t.

**Comment by 016Nojr** [comment]
Looks fine to me in an upcoming pack update which should be out in a few days.
