### ISSUE TITLE
I dont have dense cables for my ME-System

### ISSUE THREAD

**Issue by Tomatenquetscher** [FTBTeam/FTB-Ultimate-Reloaded#348]
Im using the latest version of ftb ultimate reloaded. And I am trying to build an automatic Alveary using ME Import and Export Busses. Except for 8 Busses or so none are working. I looked my problem up and found out i needed dense cables for more channels. But i cant make them on my Minecraft Version. Anybody have a fix for this?

**Comment by NicholasDreyer** [comment]
AE2 has channels disabled in this pack, you wouldn't need dense cables. This must be another issue. I have a similar issue in my world where sometimes buses don't work but breaking and replacing them usually fixes it.
