### ISSUE TITLE
Multiple issues with Tech Reborn - 1.9.0

### ISSUE THREAD

**Issue by Hobby-boy** [FTBTeam/FTB-Ultimate-Reloaded#349]
Modpack version 1.9.0

I've noticed a couple of issues with Tech Reborn and JEI within this modpack, including the following:
Superconductor Cable doesn't appear in JEI, but you can find the recipe.
Wrong recipe appears in the Assembling Machine for Basic Circuit Boards (shows that 2 Aluminium plates makes 2, should be 1 Aluminium plate and 2 Electrum plates) and Advanced Circuit Boards (shows that 2 circuits make 1, should be 1 circuit and 2 Electrum plates).
The other recipe for Basic Circuit Boards in the Assembling machine shows up wrong in JEI too (shows 1 refined iron plate and 4 Electrum plates makes 2, should be 2 Electrum plates).

Basic machine casings from IndustrialCraft are also registered as machineBlockAdvanced, which should only apply to Advanced Machine Casings.

![2020-01-05_16 55 56](https://user-images.githubusercontent.com/4096060/71783372-d9687180-2fdd-11ea-971e-aea8f1ef930a.png)
![2020-01-05_16 56 00](https://user-images.githubusercontent.com/4096060/71783373-d9687180-2fdd-11ea-85d1-dea1a796afe6.png)

I believe most of these issues are fixed in the latest version of Tech Reborn, as I have not noticed them in another modpack. The latest version is 2.24.3.1043 for 1.12.2.

**Comment by 016Nojr** [comment]
Fixed in a pack updating coming within a few days
