### ISSUE TITLE
Remove setting to auto-shutdown server

### ISSUE THREAD

**Issue by ArbitraryHubris** [FTBTeam/FTB-Ultimate-Reloaded#35]
* **Modpack Version**: 1.0.1

* **Issue**: ftbutilities.cfg has a setting to auto-shutdown servers.  I noticed that my server was gracefully shutting down every night and not generating a crash-log or recovering and restarting.  I took a look at my latest.log file and saw that this happened at 03:00 exactly - the server went through an intentional shutdown.  Then I searched through the config files for that time and found it referenced in ftbutilities.cfg, as shown in the below snippet:

```cfg
auto_shutdown {
    # Enables auto-shutdown.
    B:enabled=true

    # Enables auto-shutdown in singleplayer worlds.
    B:enabled_singleplayer=false

    # Server will automatically shut down after X hours.
    # Time Format: HH:MM. If the system time matches a value, server will shut down.
    # It will look for closest value available that is not equal to current time.
    S:times <
        03:00
        15:00
     >
}
```

* **Is it Repeatable?**: It repeats at 03:00 and 15:00 as set up in the config

* **Known Fix**: set B:enabled=false in the auto_shutdown cfg entry

BTW, who would EVER want this?

**Comment by tfox83** [comment]
We ship that enabled by default, if using our scripts the server reboots automatically

Its suggested for a smoother running server to reboot every 12 hours or so to clear ram.  This setting will remain enabled.  You can disable it if its not something you want.

**Comment by ArbitraryHubris** [comment]
ok, thanks for the explanation.  makes sense.  I use my own wrapper and
restart every 6 hours.

**Comment by LemADEC** [comment]
Just remove FTBUtilities like any public server do as there quite a few other configurations/behaviors not suited for larger facing servers.

**Comment by ArbitraryHubris** [comment]
I have a small private server for a group of friends and we utilize
ftbutils for chunkloading.  What other settings are ill-suited for
servers?  I do pull request diffs of config so it's not a problem for me if
you leave that property as is.  I'll catch it with each update.

**Comment by ha15224** [comment]
Hello, I'm running a small FTB ultimate reloaded server and have it set to shutdown and restart every dat at a certain time. However, after the designated shutdown, it doesnt seem to restart. Any fixes?
