### ISSUE TITLE
Tech Reborn Energy Flow Circuit recipe broken

### ISSUE THREAD

**Issue by Hobby-boy** [FTBTeam/FTB-Ultimate-Reloaded#350]
Version 1.9.0

So I've noticed an error with the Energy Flow Circuit recipe from Tech Reborn, which has been configured using CraftTweaker.

The recipe uses 4 advanced circuits, but the 4th circuit is set to "<ic2:crafting:2>" instead of "<ore:circuitAdvanced>", which means the recipe is broken if the advanced 
circuits are made with the assembling machine instead of the crafting table.

![2020-01-05_17 22 30](https://user-images.githubusercontent.com/4096060/71783547-26e5de00-2fe0-11ea-9f9f-152ce9eee57f.png)

**Comment by SuBZoiD** [comment]
Seems to be working fine.

![Capture](https://user-images.githubusercontent.com/53588373/77825328-8ce28d00-7119-11ea-9f48-55a4185e6ee5.PNG)
