### ISSUE TITLE
Game Crashes While Loading a World

### ISSUE THREAD

**Issue by Ddshaffer** [FTBTeam/FTB-Ultimate-Reloaded#351]
Game keeps crashing while loading. I believe it says shutting down internal server. I tired a numerious amount of things to fix this. What confuses me is I can create a copy of this world and create new ones with no problem. Somebody please help me!

[crash-2020-01-08_22.28.40-server.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/4038446/crash-2020-01-08_22.28.40-server.txt)

**Comment by 016Nojr** [comment]
Minetogether has been updated which should fix this in a few days
