### ISSUE TITLE
Immersive Engineering disabled?

### ISSUE THREAD

**Issue by SlikNinjaZ** [FTBTeam/FTB-Ultimate-Reloaded#356]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by SlikNinjaZ** [comment]
Why does it not show anything for me? It looks like the ticket is empty :(

**Comment by SuBZoiD** [comment]
It is empty dear, writing between "< ! - -" and " - - >" generates a comment (empty text).

**Comment by 016Nojr** [comment]
Immersive Engineering machines are intentionally disabled
