### ISSUE TITLE
Iridium reinforced plate cannot be made using iridium

### ISSUE THREAD

**Issue by Laggger164** [FTBTeam/FTB-Ultimate-Reloaded#357]
* **Modpack Version**: 1.9.1

* **Issue**: The iridium reinforced plate required to craft Quantum armor is impossible to make using the Iridium Alloy Ingot as it requires the Immersive Engineering's Metal press which is disabled (I am really debating why that was done, Immersive Engineering would've made a nice addition to this pack)
The only way to craft Iridium Reinforced Plates is through conversion of Magnalium Plates from Tech Reborn which require only Aluminum ingots and Magnesium Dust both of which are kinda expensive to get however none require actual Iridium... which kinda makes Iridium pointless for use in Quantum Armor. Is that intentional and if yes, is there a comprehensive list of things that were similarly changed so I don't get confused again?

This was also discussed here: https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/298
However nothing came of this thread and it's been months since then and another version of the pack and still nothing.

* **Link to Log or Crash File Paste**: None to report

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IndustrialCraft2, Immersive Engineering, Tech Reborn

* **Known Fix**: Nope, not up to me

**Comment by SupernovaDML** [comment]
You can make it in the rolling machine using magnesium and aluminum.

**Comment by Ren6767** [comment]
I'm running into this issue as well. I was wondering if this was unintentional?

**Comment by DenseInL2** [comment]
It's an unintentional off-by-one bug. It's clear in the comments in ic2.zs that they are disabling the IC2 method of crafting reinforced iridium plates in favor of forcing use of the Implosion Compressor method. They intend you to make the Tech Reborn RI plates and then just convert them to the IC2 version, but Tech Reborns RI plates are techreborn:plates:38, not techreborn:plates:37, the interchange recipe is just wrong.
