### ISSUE TITLE
I am new to FTB, and whenever i try to launch a mod pack, it doesn't work. The only one that has worked is FTB Ultimate (the original version). It has happened every time i have tried to play, so it is repeatable. 

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Ultimate-Reloaded#359]
![Screenshot (331)](https://user-images.githubusercontent.com/62319982/76960644-43f93000-68f2-11ea-8abf-5d0263f3818d.png)

* **Modpack Version**: 1.9.0

* **Issue**:  Whenever i try to open FTB Ultimate Reloaded, and other FTB packs, it goes to the screen i've shown and stops responding after that point. FTB Ultimate Reloaded always ends at the exact same datapoints as in the screenshot.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/90f60f1c

* **Is it Repeatable?**:  Yes, it happens every time.

* **Mod/s Affected**: there are no direct mods as far as i know.

* **Known Fix**:

**Comment by taahamahdi** [comment]
Try increasing the memory allocated to 2GB in the launcher options.
