### ISSUE TITLE
Thaumcraft: Research Table freezes program

### ISSUE THREAD

**Issue by JL1963** [FTBTeam/FTB-Ultimate-Reloaded#364]
* **Modpack Version**: <Minecraft 1.12.2; Forge 14.23.5.2846>

* **Issue**: <when using the research table the program sudden freezes. sometimes when you start a research, sometime after some questions. Sometimes it is working. It seems that when just entering the world the research table is most "sensitiv" for freezing the system. I'm using a MAC (latest OS) and only a kill command can stop the program-->

* **Link to Log or Crash File Paste**: <where do I find this file?>

* **Is it Repeatable?**: <yes, just use the table several times, but can't say which prerequisite are going to trigger it>

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I can unfortunately not do anything with it as the mod version isnt supported anymore
