### ISSUE TITLE
ComputerCraft: Tweaked pastebin/wget not working

### ISSUE THREAD

**Issue by NicholasDreyer** [FTBTeam/FTB-Ultimate-Reloaded#366]
* **Modpack Version**: 1.9.0

* **Issue**: When using the command "pastebin get <paste> <name>", it attemts to connect and fails with Forbidden being returned.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/019fccdb

* **Is it Repeatable?**: It only happens on my personal server, works on singleplayer. I have deleted the config files for ComputerCraft: Tweaked and have ensured that the http enabled flag is set to true.

* **Mod/s Affected**: ComputerCraft: Tweaked and Plethora's ComputerCraft integration.

* **Known Fix**: Cannot figure out a fix. Reinstalling the client does not fix it.

**Comment by KriKri98** [comment]
I had the sampe problem in singleplayer. I got it fixed by visiting the pastebin website and complete a captcha.

**Comment by 016Nojr** [comment]
Try what was mentioned above

If this issue is still present in an update that will be released in a few days I can unfortunately not do anything with it as the mod version isnt supported anymore
