### ISSUE TITLE
Server crashing due to Applied Energistics 2 (And more AE2 issues)

### ISSUE THREAD

**Issue by NicholasDreyer** [FTBTeam/FTB-Ultimate-Reloaded#368]
* **Modpack Version**: 1.9.0

* **Issue**: Server has crashed from AE auto crafting submit request twice. Both instances have been with the wireless terminal. I have been using the wireless terminal without issue for the past couple weeks.
I have been having issues with Applied Energistics 2 since creating the system, sometimes import and export buses will randomly stop working (this happens to every bus in the system, it's seemingly random when it happens). Disconnecting the buses from the system and reconnecting immediately fixes all buses that were reconnected, but not those that weren't disconnected.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d7b39548
https://paste.feed-the-beast.com/view/1e31e416

* **Is it Repeatable?**: Yes, but I do not know exactly how it is triggered as it only happens occaisionally.

* **Mod/s Affected**: Applied Energistics 2

* **Known Fix**: N/A

**Comment by 016Nojr** [comment]
I cant reproducte this on an upcoming update of the pack, should be out within a few days
