### ISSUE TITLE
Crafting recipe error for Processor Circuit Board in Assembling Machine

### ISSUE THREAD

**Issue by Danatr0nika** [FTBTeam/FTB-Ultimate-Reloaded#370]
* **Ultimate Reloaded 1.9.0**: 

* **In order to craft Energy Flow Circuits in the Assembling Machine, a crafting component called the Processor Circuit Board is required. However, the recipe is wrong: Instead of a Platinum Plate and an Advanced Circuit, the recipe requires two Platinum Plates of different varieties, one of which is unobtainable.** 

* **Known Fix: Replace Platinum Plate 4397/27 with Advanced Circuit 4168/2 using CraftTweaker.** 

![2020-05-04_00 14 48](https://user-images.githubusercontent.com/43836358/80938009-09156380-8d9d-11ea-936a-605a68bd7525.png)

**Comment by ThwartAbyss54** [comment]
The recipe in jei is wrong but if you just put the plate in one slot and an advanced circuit board in the other it crafts fine
