### ISSUE TITLE
!! still a issue !! Gravichestplate-- An expensive Jetpack with no creative flight !! still a issue !!

### ISSUE THREAD

**Issue by snakeeater98** [FTBTeam/FTB-Ultimate-Reloaded#371]
* **Modpack Version**: 1.9.0

* **Issue**: The Gravichestplate has no "Creative Fly" just a normal Jetpack.
I noticed that someone already made a ticket [(#237)](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/237#issue-449024186) for this issue, but it got closed before a propper solution was found.

![javaw_c4hqlH1neA](https://user-images.githubusercontent.com/64694429/81113396-730a4600-8f20-11ea-8cd2-41c27c6541cc.png)

* **Link to Log or Crash File Paste**: - none -

* **Is it Repeatable?**: Yes, by pressing the "Gravi Fly Key" key only a jetpack mode gets activated.

* **Mod/s Affected**: Gravitation Suite

* **Known Fix**: - none - (change jetpackmode with levitationmode)

**Comment by Danatr0nika** [comment]
I believe this is an issue with the mod itself, not the pack. You can workaround this by activating Hover Mode using the IC2 "Mode Switch" key. This is by default M, but there are other binds for M so I suggest changing it to Ctrl.

**Comment by snakeeater98** [comment]
This workaround is not realy a good one.
I can not confirm it but i guess you are right and the issue is from the Mod "Gravitation Suite" itself.
For now i will close the issue.
Thanks anyway.
