### ISSUE TITLE
ProjectRed Item Responder Chip does not work well with YABBA's Item Barrel Connector

### ISSUE THREAD

**Issue by Eufranio** [FTBTeam/FTB-Ultimate-Reloaded#373]
* **Modpack Version**: 1.9.1

* **Issue**: When using the Item Responder Chip on pipes connected to a YABBA's Item Barrel Connector, seems like it only "provides" space for 64 items at once, so if I have the network to extract 3 stacks of an item that is inside a (not full) barrel, only 1 gets sent to the connector. Once the item arrives at the connector, one more stack is extracted and etc. This seems like a bug, since all 3 stacks fit in the barrel and they should all be sent.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ProjectRed Transportation

* **Known Fix**: None

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I cant do anything with it as the mod version isnt supported anymore
