### ISSUE TITLE
Unexpected error when launching

### ISSUE THREAD

**Issue by spotiris** [FTBTeam/FTB-Ultimate-Reloaded#375]
* **Modpack Version**: 1.9.0

* **Issue**: After downloading the modpack, I press play and the Minecraft Launcher appears. I press play in the launcher and immediately an error occurs: "An unexpected issue has occurred and the game has crashed."
I have fully deleted all FTB modpacks and the FTB install directory, and reinstalled it three times.

* **Link to Log or Crash File Paste**: https://pste.ch/zihozakube

* **Is it Repeatable?**: yes

**Comment by BartMitTyp** [comment]
In the log, it says 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
The site says
```
Placing one (and only one) of slf4j-nop.jar slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem. 
```
I sadly don't know that the class path is, but when you figure that out, maybe that will already fix it

**Comment by 016Nojr** [comment]
Looks like this isnt related to the pack
