### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by weebphobia** [FTBTeam/FTB-Ultimate-Reloaded#376]
* **Modpack Version**:  1.12.2

* **Issue**:  the launcher doesnt let me launch anything i had before (optifine, fabric, etc.) and i dont know how to fix it. thsi is annoying as shit and id prefer to find ma away that i can use optifine instead of deletring minecraft, reinstalling it, and then reinstall everything else i had before.

* **Link to Log or Crash File Paste**:  no crash no log.

* **Is it Repeatable?**:  yes many times

* **Mod/s Affected**:  nope

* **Known Fix**:  nope

![05e014c7076cf7396649afe3b3494741](https://user-images.githubusercontent.com/68624113/88124343-c1270100-cb81-11ea-8ea4-27a91d6b81b8.png)

**Comment by BartMitTyp** [comment]
The message when creating an issue (now) says that when installing additional mods, devs can't help. Just reinstall it, you won't lose anything, or will you?
