### ISSUE TITLE
Charset Pocket crafting table causes crash then converting a stack of oak wood

### ISSUE THREAD

**Issue by BartMitTyp** [FTBTeam/FTB-Ultimate-Reloaded#377]
* **Modpack Version**: 1.9.0

* **Issue**: Converting a stack of oak wood logs into planks with the pocket crafting table when your inventory only has the 9 slots free via shift+rightclick crashes the game. I have not tried it with other woods.
I think this will be repeatable with any kind of item.
Maybe a fix will also fix that when you shift+leftclick on an item in the pocket crafting table and have no more space, it also crashes the game.

* **Link to Log or Crash File Paste**: There was no crash report generated

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Charset 0.5.6.3

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I can unfortunately not do anything with it as the mod version isnt supported anymore
