### ISSUE TITLE
GraviGun Gravity Gun caused crash when climbing a ladder and looking straight up

### ISSUE THREAD

**Issue by BartMitTyp** [FTBTeam/FTB-Ultimate-Reloaded#378]
* **Modpack Version**: 1.9.0

* **Issue**: Holding a gravity gun and climbing a ladder while looking straight up causes the game to crash. This also happens on every rejoin after that, so single player games would be impossible to access.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ed74d065

* **Is it Repeatable?**: yes

* **Mod/s Affected**: GravityGun 1.12.2-7.0.1

**Comment by BartMitTyp** [comment]
This doesn't seem to happen with the supercharged gravitygun and the ladder has to be of a minimum length. Around 10 should be enough

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I cant do anything with it as the mod version isnt supported anymore
