### ISSUE TITLE
Thaumcraft Thaumonomicon won't complete any Thaumic Tinkerer research

### ISSUE THREAD

**Issue by BartMitTyp** [FTBTeam/FTB-Ultimate-Reloaded#379]
* **Modpack Version**: 1.9.0

* **Issue**: When trying to complete anything from the Thaumic Tinkerer Research Tree, even though I have all the requirements fullfilled, the "completing ..." text never finishes. The "complete" button is clickable, but there is no progress.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes. To test this, one must only complete the first steps, which takes just a few minutes. (I did that on another world to confirm)

* **Mod/s Affected**: Thaumic Tinkerer 1.12.2-5.0-353c71c and Thaumcraft 6.1.BETA26

**Comment by will-blk** [comment]
Same here on modpack version 1.10

**Comment by zellfrey** [comment]
This is fixed in the later versions of Thaumic Tinkerer.

The last update for thaumic tinkerer was in May 2020.

They released a new version of the pack in October. This maybe an oversight

**Comment by mxswat** [comment]
I can confirm, broken on modpack 1.10

**Comment by 016Nojr** [comment]
Thaumic Tinkerer updated

**Comment by zellfrey** [comment]
> Thaumic Tinkerer updated

So what, does this mean that the pack will be updated? Because I stated that the mod updated. But the pack doesn't have the updated version of the mod

**Comment by Sunekaer** [comment]
We are working on updating the pack

**Comment by zellfrey** [comment]
> We are working on updating the pack

That sounds really good, did SlowPoke ever talk to you about the fan pack update I wanted to push?
