### ISSUE TITLE
Server wont startup after accepting EULA 

### ISSUE THREAD

**Issue by SanderForl** [FTBTeam/FTB-Ultimate-Reloaded#381]
This is a issue with creating a server for ftb. (ive tried with FTB Ultimate Reloaded and FTB Revelation)

So i downloaded and installed all the server files via the serverinstall_35_37 file i got of the launcher. When i try to start the Start.bat program to start the server, it asks me to type [y or n] if i want to accept the EULA. I ofcourse press y for yes and then the server cmd program crashes right away. After this happenes a EULA text document appears in my server folder. Inside the text doucment it says EULA: true by default. When i try to open the start.bat program once again, i am once again met with the press [y or n] to accept EULA and the cmd crashes right after once again. This is where i am stuck. i cant open the server, and when i try to start the forge-1.12.2...ect java program it runs for a good while, but i cant connect to the server at all. not even locally. 

Not sure where to find the crash or log report. dont find anything obvious in the server folder atleast.

But this is what the start.bat file says:
 "Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?"
[y/n]

And this is the coding inside the start.bat file:
@echo off
echo "Do you agree to the Mojang EULA available at https://account.mojang.com/documents/minecraft_eula ?"
set /p EULA=[y/n]
IF /I "%EULA%" NEQ "y" GOTO END
echo eula=true>eula.txt
:END
java.exe -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6124M -Xms4096M -jar forge-1.12.2-14.23.5.2846-universal.jar nogui

I can repeat the problem

Appreaciate all the help i can get

Thanks

**Comment by ScarlettSamantha** [comment]
Same running on ubuntu server 20.04LTS, extracted the java string from the start.sh to see if i could mess around with some of the values to make it work, no success.

Other minecraft forge servers ... No issue at all running.

![Screenshot_20200901_184531](https://user-images.githubusercontent.com/33827053/91882513-59d19600-ec83-11ea-8520-e98f8db1eebc.png)

**Comment by SanderForl** [comment]
I just fixed my problem. I uninstalled my current version of java. (i think it was update 8 version 261). and installed java update 8 version 221. Dont know if this is ur problem, but hope it works for u too

**Comment by ScarlettSamantha** [comment]
@SanderForl Can confirm that this works as it tried running it with openjdk8 instead of openjdk11 so how to solve this (for people finding this issue) on linux(deb based distro's) is.

Download openjdk-8-jdk `sudo apt-get install openjdk-8-jdk`
and then going to verify the install location with the `sudo update-java-alternatives --list` which should give a like

```
scarlett@ubuntu-2gb-nbg1-2:~/feedthebeast$ sudo update-java-alternatives --list;
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64
```

take the path of java-1.8.0-openjdk-amd64 and add `/bin/java` to the end of it to create a start command like this in your `start.sh`

```
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -server -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx2000M -Xms1500M -jar forge-1.12.2-14.23.5.2846-universal.jar nogui
```

After performing these actions i get what looks like a clean boot and fixes my issue.

With kind regards,
Scarlett
