### ISSUE TITLE
Infinite Harvest

### ISSUE THREAD

**Issue by will-blk** [FTBTeam/FTB-Ultimate-Reloaded#384]
* **Modpack Version**: 1.10.0

* **Issue**: Right clicking a vanilla planted crop with an Axe Of The Stream gives the full harvest without turning growth state back to 0%

* **Mod/s Affected**: Thaumcraft

**Comment by 016Nojr** [comment]
If this issue is still present in an update that will be released in a few days I cant do anything with it as the mod version isnt supported anymore
