### ISSUE TITLE
Missing reinforced bows crafting

### ISSUE THREAD

**Issue by mxswat** [FTBTeam/FTB-Ultimate-Reloaded#386]
* **Modpack Version**: 1.10.0

* **Issue**: I see that I can use them to craft the "Fricking Laser beam" but I'm unable to craft any reinforced bow

* **Mod/s Affected**:  Thermal Foundation

**Comment by 016Nojr** [comment]
The recipe isnt locked to reinforced bows, it accepts any bow with flame or any sword with fire aspect
