### ISSUE TITLE
The server files linked to from Curseforge app do not seem to be correct files.  It links me to here

### ISSUE THREAD

**Issue by Howsyomamanem** [FTBTeam/FTB-Ultimate-Reloaded#387]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by fabm3n** [comment]
Can you close this issue? You gave more Informations in #388
