### ISSUE TITLE
The FTB-Ultimate-Reloaded server files?

### ISSUE THREAD

**Issue by Howsyomamanem** [FTBTeam/FTB-Ultimate-Reloaded#388]
The Server files link in the description of the pack in CurseForge do not seem to be valid.  
The link from the description:  

> Server Files: https://www.feed-the-beast.com/projects/ftb-ultimate-reloaded/files

The windows file is an EXE that launches Overwolf and just seems to install the client pack again.

The linux file has no extention at all.  Not sure what to do with that.  I would prefer a linux file, since I run servers on a headless linux server.

* **Modpack Version**: Any

* **Issue**: See above

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by fabm3n** [comment]
Visit this Page: https://feed-the-beast.com/modpack/ftb_ultimate_reloaded
Go to the "Server Files" Tab
Download the Server Files for your Version and your OS


This should be fixed in the Description

**Comment by Quetzi** [comment]
Stale link in the pack description has now been removed

**Comment by Howsyomamanem** [comment]
sorry for wasting your time.  I'll read the past issue better in the future.
