### ISSUE TITLE
FTB-Ultimate-Reloaded

### ISSUE THREAD

**Issue by MacoDeVinx** [FTBTeam/FTB-Ultimate-Reloaded#390]
* **Modpack Version**:
1.10.0

* **Issue**:
I have a server with FTB Ultimate Reloaded on Scalacube and when i reported this to them, they then told me to contact you, the devs about it.

Every time someone or yourself joins the server then you will meet loads of full_frame(@number,{},{Null,Object[#396],Object[#396]},Integer,Object[#number]}) in the chat, i've attached an image with more informations.
![Problem_Maybe](https://user-images.githubusercontent.com/38403004/103469904-40dd0c80-4d6b-11eb-93c1-32f59b7501cc.png)

Am not sure if it's a issue or what it is tbh, but thought i would report it anyways.

EDIT: i did remove MineTogether as i wasn't really fan of the global talk but the issue were there before i removed the mod, just wanted to clear that up if you were to ask that, that is why.

* **Link to Log or Crash File Paste**:
https://pastebin.com/m62hDKPu

* **Is it Repeatable?**:
Yes, every time you join the server this happens.

* **Mod/s Affected**:
N/A

* **Known Fix**:
N/A

**Comment by 016Nojr** [comment]
Please check if this is still happening when the new pack update is released in a few days, and send a new issue on it.
