### ISSUE TITLE
Unbalanced energy conversion rate from Railcraft steam to RF using upgraded steam dynamos from ThermalExpansion

### ISSUE THREAD

**Issue by Tyrrx** [FTBTeam/FTB-Ultimate-Reloaded#393]
* **Modpack Version**:  1.10.0

* **Issue**: Railcraft boilers can produce a huge amout of steam (about 720.000 mb/tick) which is not quite much for Railcraft machines but a Thermal Expansion steam dynamo can consume 120 steam mb/tick from an external source (on level one; not sure if you can upgrade them) and produces 240 RF/tick. This conversion rate is very problematic as you do not need any other energy sources during the whole gameplay. The maximum possible RF generation with this method results in 1.440.000 RF/tick from just one Railcraft steam bioler. Using the energy bridge mod you can produce 360.000 EU/tick. You still need 6000 steam dynamos but there are not very expensive to craft.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Setup a full size Railcraft steam bioler and attach 6000 steam dynamos (turbine conversion) to it. Attach an energy bridge to the RF output to produce EU.

* **Mod/s Affected**: Thermal Expansion 2, Railcraft

* **Known Fix**: The best solution would be to change the steam consumtion rate of the steam dynamos to a more appropriate value but I am not sure if that is possible. Another possible solution: change the "CustomPowerScaling" of "Steam" in ThermalExpansion settings but I do not like this solution as it could affect the not upgraded steam dynamos.

**Comment by 016Nojr** [comment]
If you have the capacity to set up 6000 steam dynamos, your power gen isnt an issue anymore. Yes, it may seem inbalanced, but it affects other parts if we start changing it.
