### ISSUE TITLE
ProjectRed mod replacing Immersive Engineering's Kinetic Dynamo crafting recipe.

### ISSUE THREAD

**Issue by Orion-Netix** [FTBTeam/FTB-Ultimate-Reloaded#396]
* **Modpack Version**: 1.10-0

* **Issue**: Trying to build kinetic dynamo from IE early in the game requires mid-end game ressources because crafting recipe has been changed (requiring PR ressources) and Copper Coil block (IE) cannot be found (Disabled?).

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Immersive engineering v.0.12-91 and ProjectRed v.4.9.4.120

* **Known Fix**: Manually changing the config files of both mods to enable the Copper Coil block and use IE crafting recipe for Kinetic Dynamo block.

**Comment by 016Nojr** [comment]
This is intentional to gate the kinetic dynamo. This wont be changed
