### ISSUE TITLE
Forestry carpenter recipes

### ISSUE THREAD

**Issue by petitelegume** [FTBTeam/FTB-Ultimate-Reloaded#397]
* **Modpack Version**: 1.11.0

* **Issue**: Since updating to 1.11 the oredict in the Forestry carpenter doesn't seem to be working properly. For many recipes involving wood/planks (impregnated sticks, scented paneling, etc.) it now only accepts oak, not any of the other vanilla or forestry woods. Prior to the update all of these were accepted.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Forestry

**Comment by 016Nojr** [comment]
Can you please resubmit this issue here https://www.feed-the-beast.com/support. This issue tracker was supposed to be closed after the last update, the links in the main menu of the pack have already been updated.
