### ISSUE TITLE
MagicBees-Skystone Bees not breedable

### ISSUE THREAD

**Issue by WungTung** [FTBTeam/FTB-Ultimate-Reloaded#398]
**Modpack Version**: 1.11.0

**Issue**: In Version 1.11.0 of Ultimte Reloaded the mod **MagicBees** added a few new species of bees like for example the Fluix-Bee to the game. To breed the bees of this branch you **need** to breed the Skystone-Bee first. In order to breed the Skystone-Bee you **need to place a Skystoneblock** under your apiary. Normally Applied Energistics 2 spawns meteorites made out of Skystone in your world and the meteorites have a chest located in the middle of them with fore example inscribers. In Ultimate Relaoded the crafting for circuits is different and you don't need to find inscribers inside the meteorites to craft circuits for your ME-System. That means Skystone doesn't spawn in your world and is not obtainable in any way, in version 1.11.0 of Ultimate Reloaded it also has bin removed from NEI.

**Mod/s Affected**: Applied Energistics 2, Forestry, MagicBees

**Known Fix**: Add a recipe to craft Skystone with fore example uu-matter.

**Comment by 016Nojr** [comment]
Can you please resubmit this issue here https://www.feed-the-beast.com/support. This issue tracker was supposed to be closed after the last update, the links in the main menu of the pack have already been updated.
