### ISSUE TITLE
Binnie's Genetics issue in multiplayer.

### ISSUE THREAD

**Issue by DonovanKermal** [FTBTeam/FTB-Ultimate-Reloaded#399]
Modpack Version :  1.11.0

Issue : Binnie's Genetics machines don't work

Mod/s Affected : Binnie's Genetics

Issue :
I'm playing on mc-complex. Since the 1.11.0 update the machines of binnie's genetics don't work. I made a ticket in their discord and the moderators answered me that the problem come from the modpack and not the server so they can't do anything.
The mod work fine in singleplayer.
The machines which are runnning just before the modpack update are locked at % they were.
The enzyme slot is not charging when i put the right material (enzyme/gold nugget...).
The machines allows RF and liquids, but don't take items from the waiting list.

Sorry if my english is not correct.

**Comment by 016Nojr** [comment]
Can you please resubmit this issue here https://www.feed-the-beast.com/support. This issue tracker was supposed to be closed after the last update, the links in the main menu of the pack have already been updated.
