### ISSUE TITLE
It'se broken

### ISSUE THREAD

**Issue by TechnicianLP** [FTBTeam/FTB-Ultimate-Reloaded#4]
#remove drills and chainsaws in favor of TR
mods.jei.JEI.removeAndHide(<gravisuite:advanceddrill:26>);
mods.jei.JEI.removeAndHide(<ic2:diamond_drill:26>);
mods.jei.JEI.removeAndHide(<ic2:drill:26>);
mods.jei.JEI.removeAndHide(<ic2:iridium_drill:26>);
mods.jei.JEI.removeAndHide(<ic2:chainsaw:26>);
mods.jei.JEI.removeAndHide(<gravisuite:advancedchainsaw:26>);

needs more * and less 26

**Comment by tfox83** [comment]
Fixed in dev as well as nano saber

**Comment by tfox83** [comment]
Update 1.0.1 released
