### ISSUE TITLE
Conflicting recipes rendering some items uncraftable

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#40]
* **Modpack Version**: 1.0.1

* **Issue**: there are 78 existing conflicting recipes

[Conflict.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/2870158/Conflict.txt)

* **Is it Repeatable?**: yes
> do /ct conflict

* **Mod/s Affected**: all

* **Known Fix**: 
> CraftTweaker script 
>> unless you just don't care about conflicting recipes, then just leave the uncraftable items remain uncraftable like they are now :)

**Comment by modmuss50** [comment]
Most of those seem like a none issue as either use the ore dict, or are there to handle the ic2 energy items.

**Comment by tfox83** [comment]
Correct, thanks to OreDict its not an issue.

**Comment by EthernalVoid** [comment]
Good to hear!
