### ISSUE TITLE
Broken recipe for Reactor Plating (IC2)

### ISSUE THREAD

**Issue by jonps97** [FTBTeam/FTB-Ultimate-Reloaded#400]
* **Modpack Version**:
1.11.0

* **Issue**:
Reactor Plating for IndustrialCraft 2 is uncraftable, results in alot of items/blocks (such as GraviChestPlate) to be uncraftable without cheating

* **Link to Log or Crash File Paste**:
No log or crash files required

* **Is it Repeatable?**:
Yes, just try to craft the Reactor plating

* **Mod/s Affected**:
IndustrialCraft 2

* **Known Fix**:
None, need to cheat in order to continue

**Comment by 016Nojr** [comment]
Can you please resubmit this issue here https://www.feed-the-beast.com/support. This issue tracker was supposed to be closed after the last update, the links in the main menu of the pack have already been updated.
