### ISSUE TITLE
Anormally high CPU Usage

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Ultimate-Reloaded#42]
* **Modpack Version**: 1.0.1 

* **Issue**: High CPU Usage 

* **Link to Log or Crash File Paste**: NO LOGS     https://gyazo.com/2dd057df3baaf58042c43ac7f64ee749

* **Is it Repeatable?**: I don't know 

* **Mod/s Affected**: None 

* **Known Fix**: none

**Comment by tfox83** [comment]
Sorry that screenshot tells me nothing.  What CPU do you have, and also will need logs if you have a strong enough CPU to supported 1.12 modded MC.

**Comment by ghost** [comment]
I do run Project Ozone 3 without any problem 
I have an Intel Core i5-7400 3GHz and an GTX 1050 2gb
Here are the latest logs https://paste.feed-the-beast.com/view/ee8ba771

**Comment by ghost** [comment]
I am running ATM 3 remix and Enigmatica 2 expert without any issue

**Comment by ghost** [comment]
Normally running those 3 packs I am not even at 75% of my CPU Usage !

**Comment by LemADEC** [comment]
First boot is lagging during a few minutes while building the Thaumcraft aspects cache for JEI.
If you let it finish, you won't be impacted anymore by it until the modpack is updated.

**Comment by ghost** [comment]
Ok thanks @LemADEC

**Comment by tfox83** [comment]
Closing as cannot reproduce this even on an older laptop CPU
