### ISSUE TITLE
IC2 MOX fuel is not craftable, yet is shown in jei

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#43]
* **Modpack Version**: 1.0.1

* **Issue**: IC2 MOX dual and quad fuel rods are not craftable rendering MOX reactor builds useless, same as with mox fuel

* **Is it Repeatable?**: yes

* **Mod/s Affected**: ic2

* **Known Fix**: adding a recipe

**Comment by tfox83** [comment]
IC2 mox fuel was not avail in classic.  Have hidden the items to avoid confusion in next update
