### ISSUE TITLE
Some TechReborn tools are not craftable

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#44]
* **Modpack Version**: 1.0.1

* **Issue**: Some TechReborn tools are not craftable
![q](https://user-images.githubusercontent.com/45131452/52876502-ad3eca80-3157-11e9-9176-f00f97cdfa73.jpg)
![w](https://user-images.githubusercontent.com/45131452/52876503-ad3eca80-3157-11e9-8138-7a78247dfa03.jpg)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: TechReborn IC2

* **Known Fix**: recipe change
#41

**Comment by EthernalVoid** [comment]
![q](https://user-images.githubusercontent.com/45131452/52876587-f0993900-3157-11e9-8ec7-8f5f89e53bff.jpg)

**Comment by modmuss50** [comment]
All of the battery one are fixed in the next version of TR, I will look into the other issues.

**Comment by modmuss50** [comment]
I have fixed the recipes using the energy crystals, fix will be in the next TR update.

**Comment by tfox83** [comment]
fix in next udpate
