### ISSUE TITLE
Forcepower_crystal has no crafting recipe yet is used to make MFFS items

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#45]
* **Modpack Version**: 1.0.1

* **Issue**: ITEM: <modularforcefieldsystem:forcepower_crystal:101>.withTag({ForceEnergy: 0})
has no crafting recipe
![q](https://user-images.githubusercontent.com/45131452/52876781-7fa65100-3158-11e9-8737-ab05d6191a36.jpg)
![w](https://user-images.githubusercontent.com/45131452/52876782-7fa65100-3158-11e9-82b1-f3fbd2b04227.jpg)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: MFFS

* **Known Fix**: recipe change

**Comment by tfox83** [comment]
fixed in next update

**Comment by Jay9971** [comment]
What is the crafting recipe for force power crystals btw?
