### ISSUE TITLE
LED lamps from tech reborn have uncraftable recipes

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#46]
* **Modpack Version**: 1.0.1

* **Issue**: LED lamps from tech reborn have uncraftable recipes due to using techreborn cables
![q](https://user-images.githubusercontent.com/45131452/52877437-453db380-315a-11e9-86a1-d2efeb3e17f0.jpg)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Tech reborn

* **Known Fix**: recipe change

**Comment by modmuss50** [comment]
Fixed in next TR update

**Comment by tfox83** [comment]
Included in 1.1.0 update
