### ISSUE TITLE
Incandescent lamps from tech reborn have uncraftable recipes

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#47]
* **Modpack Version**: 1.0.1
* **Issue**: Incandescent lamps from tech reborn have uncraftable recipes due to using techreborn cables

![q](https://user-images.githubusercontent.com/45131452/52877505-75855200-315a-11e9-9830-ee723bbc9867.jpg)

* **Is it Repeatable?**: yes
* **Mod/s Affected**: Tech reborn
* **Known Fix**: recipe change

**Comment by modmuss50** [comment]
Fixed in next TR update.

**Comment by tfox83** [comment]
Included in 1.1.0 update

**Comment by ThwartAbyss54** [comment]
See i cant craft these because you need Tech Reborn carbon fibre not ic2 and the only craftable fibre is ic2s
