### ISSUE TITLE
IC2 charging lapotron crystal has no recipe, yet is enabled

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#48]
* **Modpack Version**: 1.0.1

* **Issue**: <ic2:charging_lapotron_crystal:26>has no recipe

* **Is it Repeatable?**: yes

* **Mod/s Affected**: IC2

* **Known Fix**: hide it or add a recipe

**Comment by EthernalVoid** [comment]
Same as with IC2 Crystal memory
and the advanced RE battery

**Comment by tfox83** [comment]
Both have recipes for me, please make sure your instance is fully installed, including the scripts folder

**Comment by EthernalVoid** [comment]
Coming from a new twitch install:
The battery's do not have recipes, neither does the crystal memory.

> might want to remove them from jei or do you enjoy the clutter?

Try typing:  "charging lapotron crystal" letter by letter in the JEI i'm sure you will find there is no recipe for anything i mentioned here.

**Comment by will-blk** [comment]
The crystal memory (should be done in the furnace, https://wiki.industrial-craft.net/index.php?title=Crystal_Memory) and advanced re-battery doesn't have a recipe for me either; 
The "charging" lapotron crystal doesn't appear on the JEI for me and the normal version seems normal.

**Comment by EthernalVoid** [comment]
Silicon dioxide does not exist in the pack, neither does Crystal memory(raw) ;)

As for the crystals that i even specified the item:value of:
![q](https://user-images.githubusercontent.com/45131452/52903693-995f9b00-3221-11e9-900a-c5494f578c3b.jpg)

**Comment by tfox83** [comment]
hidden in next update
