### ISSUE TITLE
Typo in "Language" on main menu

### ISSUE THREAD

**Issue by lifeofchrome** [FTBTeam/FTB-Ultimate-Reloaded#5]
* **Modpack Version**: 1.0.0

* **Issue**: In the main menu, "Language" is spelled "Lauguage". Locale is English (US).

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: CustomMainMenu configuration

* **Known Fix**: Edit the configuration

**Comment by tfox83** [comment]
Update 1.0.1 released
