### ISSUE TITLE
IC2 Miner has no compatible drill

### ISSUE THREAD

**Issue by will-blk** [FTBTeam/FTB-Ultimate-Reloaded#50]
* **Issue**: There is no compatible mining drill for the ic2 miner.

**Comment by modmuss50** [comment]
I will have a look to see if its possible to add support for TR's tools.

**Comment by modmuss50** [comment]
Humm, there is no api for this, I will have to investigate some more.

**Comment by will-blk** [comment]
What about the otherway around, adding back the recipe from ic2 mining drill and make TR compatible with it?

**Comment by modmuss50** [comment]
An issue has been opened with ic2, hopefully we can get an api added. https://bt.industrial-craft.net/view.php?id=2492

**Comment by tfox83** [comment]
I prefer to not use IC2 tools since they are not enchantable and do not have as much support as the TR tools.

**Comment by Chocohead** [comment]
The API is added in IC2 2.8.117, looks like modmuss is on the case already: TechReborn/TechReborn#1708

**Comment by MaxiBerdy** [comment]
Still doesn't work as on version 1.5.0...

**Comment by modmuss50** [comment]
Yes, I’ve been super busy and haven’t got a chance to look at it, sorry about that

**Comment by zmaster587** [comment]
Is there any reason why a recipe cannot be added to switch the drills back and forth kinda like there is with the IC2/techreborn upgrades and put the tag "for use in IC2 miner" on the IC2 drill using craft tweaker?  It could make an okay temp solution.

**Comment by tfox83** [comment]
Due to NBT that does not work correctly. Ill get the fix in from TR as soon as its avail.

**Comment by modmuss50** [comment]
Will be fixed shortly in an upcoming TR update, sorry about the delay

**Comment by tfox83** [comment]
Thanks
