### ISSUE TITLE
[Question] Tesseracts replace?

### ISSUE THREAD

**Issue by Dinip** [FTBTeam/FTB-Ultimate-Reloaded#51]
I have a question. Is there any block to replace the old tesseracts from thermal expansion?
Thanks

**Comment by EthernalVoid** [comment]
Transceiver from enderio

**Comment by Dinip** [comment]
there is no enderio...

**Comment by LemADEC** [comment]
EnderStorage chests are chunkloaders, so you don't want to use them.
AE2 QuantumBridge remains a valid option for items and fluids.
Minecart can go through portals, makes some interesting setups with Railcraft for items, fluids and energy.

**Comment by modmuss50** [comment]
The Interdimensional SU from TR may help. There are other interesting way of moving power long distances as well.

**Comment by Dinip** [comment]
But there is nothing for RF transfer...

**Comment by LemADEC** [comment]
Railcraft can transport RF with one the energy cart.
RF can be transfered in item form too.

**Comment by tfox83** [comment]
We have no plans of adding any more mods at this time, there are plenty of ways to move around power :)
