### ISSUE TITLE
Crash upon creating world

### ISSUE THREAD

**Issue by jacobwilki01** [FTBTeam/FTB-Ultimate-Reloaded#53]
* **Modpack Version**: 1.0.1

* **Issue**: Loaded into the game and everything runs fine, menus etc. When I create a world, it gets almost done and just crashes.

* **Link to Log or Crash File Paste**: https://pastebin.com/mcRLzqnj

* **Is it Repeatable?**: Yes. It happens every time.

* **Mod/s Affected**: There shouldn't be, as looking through logs it looks as if I load into the world and then the game crashes. I have Optifine installed in the log file on the pastebin, but have been able to repeat it without, so I know that it is not the issue.

**Comment by modmuss50** [comment]
Try without optifine? Line 84 seems to suggest its the minimap

**Comment by silkyspidar** [comment]
i dont have optifine and i have the same issue

**Comment by silkyspidar** [comment]
i fixed it by updating my graphics drivers try that
