### ISSUE TITLE
Marble can't be made to Chisel

### ISSUE THREAD

**Issue by Mini-kun** [FTBTeam/FTB-Ultimate-Reloaded#54]
* **Modpack Version**: 1.0.1

* **Issue**: Marble Is not Oredes.

* **Link to Log or Crash File Paste**: There is not a Log Error

* **Is it Repeatable?**: Won't Say so

* **Mod/s Affected**: RailCraft, Chisel and ProtectRed 

* **Known Fix**: make it Goes from RailCraft To Chisel Then to ProtectRed
[https://gyazo.com/e85c0b32c6a58f777d64155c8cdbc39c](url)

**Comment by tfox83** [comment]
You can switch the types of marble in the crafting table, same with basalt.
