### ISSUE TITLE
TOP config command not recognized

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Ultimate-Reloaded#55]
* **Modpack Version**:  1.0.1

* **Issue**: /top config command not recognized despite TOP being in the pack

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: all day long

* **Mod/s Affected**: the one probe 1.4.28

* **Known Fix**:

**Comment by grannymc** [comment]
ETA: cheats were enabled

**Comment by tfox83** [comment]
Will need to submit this to the dev, but you can just access the config under mod options in the main menu

**Comment by TheSaucyWelshman** [comment]
Last I knew the command was /topcfg
