### ISSUE TITLE
Only craftable [World control] recipes are the howler alarms

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#57]
* **Modpack Version**: 1.0.1

* **Issue**: Only craftable [World control] recipes are the alarms

* **Is it Repeatable?**: yes

* **Mod/s Affected**: World control

* **Known Fix**: add recipes for the other blocks, at least for the thermal monitor ............

**Comment by tfox83** [comment]
hmm seems that broke last update, Ill let the dev know.

**Comment by tfox83** [comment]
Added all recipes via scripts based on 1.4.7 nuclear control in next update
