### ISSUE TITLE
NanoSuit BodyArmor not charging with MFE.

### ISSUE THREAD

**Issue by Rasea-M** [FTBTeam/FTB-Ultimate-Reloaded#58]
* **Modpack Version**: Latest (v1.0.1)

* **Issue**: NanoSuit BodyArmor not charging with MFE. 

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: Yes, confirmed in both multiplayer and singleplayer, in and outside of spawn, also tested with the advanced version (with jetpack)

* **Mod/s Affected**: IndustrialCraft 2

* **Known Fix**: MFSU works (????????)

**Comment by Trinsdar** [comment]
It's an ic2 issue as the items don't have the correct tier or storage with the classic profile but keep their storage and tier from the experimental profile

**Comment by nan0bug00** [comment]
Same issue with Gravitation Suite Advanced Electric Jetpack

**Comment by tfox83** [comment]
IC2 is aware of the bug, I made the TR charge-o-mat cheaper just before release of the pack as a work around.  It will charge any tier EU item

**Comment by tfox83** [comment]
closing due to work around with charge-o-mat, will get the fix in if IC2 pushes an update.

**Comment by Chocohead** [comment]
The charge and discharge tier of the MFE is bumped up to 3 in IC2 2.8.117, should work around this along with any other items which are tired too highly.
