### ISSUE TITLE
Advanced Solar Helmet not craftable

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#59]
* **Modpack Version**: Latest (v1.0.1)

* **Issue**: Advanced Solar Helmet isn't craftable with the crafting recipe shown

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: ///

* **Mod/s Affected**: Advanced Solar Panels

* **Known Fix**: ///

**Comment by EthernalVoid** [comment]
![q](https://user-images.githubusercontent.com/45131452/52903747-57832480-3222-11e9-9b90-94ff4fac4dbd.jpg)

the intended recipe:
![q](https://user-images.githubusercontent.com/45131452/52903750-71246c00-3222-11e9-9593-fc7b2e562d3e.jpg)

**Comment by tfox83** [comment]
reported to dev

**Comment by tfox83** [comment]
Fixed all solar helmet with scripts
