### ISSUE TITLE
Storage Unit not craftable

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#60]
* **Modpack Version**: Latest (v1.0.1)

* **Issue**: Storage Unit isn't craftable with the crafting recipe shown

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: ///

* **Mod/s Affected**: ProjectX 2

* **Known Fix**: ///

**Comment by tfox83** [comment]
It is actually broken, so I will remove the blocks from JEI next update

**Comment by tfox83** [comment]
removed in next update 1.1.0
