### ISSUE TITLE
Empty Cell dupe bug 

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#61]
* **Modpack Version**: Latest (v1.0.1)

* **Issue**: If you use empty cells and fill them with water from a lake you get filled cells but the emty cells don't become less.

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: ///

* **Mod/s Affected**: IC2

* **Known Fix**: ///

**Comment by Chocohead** [comment]
Fixed in IC2 2.8.117 as far as I can tell, feel free to ping me if there's still missed cases.

**Comment by FolkFighter** [comment]
> Fixed in IC2 2.8.117 as far as I can tell, feel free to ping me if there's still missed cases.

Still Active Bug in current 1.5.0 modpack

**Comment by tfox83** [comment]
This is fixed in 1.6.0
