### ISSUE TITLE
Iron Tank Bug

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#62]
* **Modpack Version**: Latest (v1.0.1)

* **Issue**: every iron tank multi block got a capacity of 64.000 mb. doesn't matter wich size. and not every size is working.

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: ///

* **Mod/s Affected**: Railcraft

* **Known Fix**: ///

**Comment by EthernalVoid** [comment]
https://github.com/Railcraft/Railcraft/issues/1682 already fixed

**Comment by tfox83** [comment]
Still awaiting the next beta of RC to be released.  As of 1.4.0 of the pack we are still running Beta 5

**Comment by tfox83** [comment]
in 1.5.0 beta going live later today
