### ISSUE TITLE
Solar quantum suit helmet not craftable ;)

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#63]
* **Modpack Version**: 1.0.1

* **Issue**: 
![qw](https://user-images.githubusercontent.com/45131452/52903886-797da680-3224-11e9-9ded-78b2130bdead.jpg)
![q](https://user-images.githubusercontent.com/45131452/52903887-797da680-3224-11e9-9ea2-bdf1ac830085.jpg)
![w](https://user-images.githubusercontent.com/45131452/52903888-797da680-3224-11e9-937f-dde5ae5efacc.jpg)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Advanced solar panels

* **Known Fix**: Add legit recipes ;3

**Comment by tfox83** [comment]
Just tested in dev and they are def craftable, alot of players have them on our test server also.
