### ISSUE TITLE
Suggestion: add the new mod redwoods.

### ISSUE THREAD

**Issue by Trinsdar** [FTBTeam/FTB-Ultimate-Reloaded#67]
* **Modpack Version**: 1.0.1

* **Issue**: Redwoods is basically a companion mod to traverse that adds redwood and pine trees and biomed from extra biomes xl. It even uses most of the same textures. Would you be willing to add it considering it makes the pack a little closer to the original? 
https://minecraft.curseforge.com/projects/redwoods

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by tfox83** [comment]
After testing I cannot safely add this to existing worlds.  Sorry.
