### ISSUE TITLE
Overlapping recipes for basalt/marble

### ISSUE THREAD

**Issue by LemADEC** [FTBTeam/FTB-Ultimate-Reloaded#69]
* **Modpack Version**: 1.0.1
* **Issue**: unable to chisel marble and basalt
* **Link to Log or Crash File Paste**: n/a
* **Is it Repeatable?**: yes
* **Mod/s Affected**: Project Red, Railcraft and Chisel are providing 

* **Known Fix**: use shaped recipes with different position
or simply add all variants to chiseling with crafttweaker

![image](https://user-images.githubusercontent.com/4776032/52938444-fbbfb500-3361-11e9-8d54-08808a212521.png)
![image](https://user-images.githubusercontent.com/4776032/52938928-32e29600-3363-11e9-9a5e-3cc7f2e73c22.png)

![image](https://user-images.githubusercontent.com/4776032/52938408-e5b1f480-3361-11e9-8346-aecce8bbaed6.png)

**Comment by tfox83** [comment]
added project red basalt and marble to chisel in next update

**Comment by tfox83** [comment]
remove the placeholder recipes as well to simplify things
