### ISSUE TITLE
No recipe for Iridium Neutron Reflector

### ISSUE THREAD

**Issue by pavelgar** [FTBTeam/FTB-Ultimate-Reloaded#70]
* **Modpack Version**: 1.0.1

* **Issue**: No crafting recipe for **Iridium Neutron Reflector** from Tech Reborn

* **Known Fix**: Make a craftable recipe

**Comment by tfox83** [comment]
use the IC2 version of the Iridium Neutron Reflector which is craftable.  The TR version is removed from JEI so not sure why you are even seeing it.

**Comment by pavelgar** [comment]
Because NEI shows Ion Thruster recipe which requires Iridium Neutron Reflector from TR and not from IC2.
Crafting Ion Thrusters with IC2 version doesn't work. 
Recipe update for Ion Thruster needed then.

**Comment by tfox83** [comment]
ah I see that now, will change to the IC2 versions next update. Thanks

**Comment by phit** [comment]
fyi crafting the ic2 thick neutron reflector also doesnt seem to work at all, the recipe is in jei but doesnt work, and they are needed to make the ic2 iridium reflector

ive added these two to our scripts to fix it:

```
recipes.addShaped(<powersuits:powerarmorcomponent:4>, [[<ore:plateIridium>, <ore:craftingSuperconductor>, <ore:plateIridium>], [<ore:componentFieldEmitter>, <ore:componentHVCapacitor>, <ore:componentFieldEmitter>], [<ore:reflectorIridium>, null, <ore:reflectorIridium>]]);
recipes.addShaped(<ic2:thick_neutron_reflector>, [[null, <ic2:neutron_reflector>, null],[<ic2:neutron_reflector>, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidberylium", Amount: 1000}}), <ic2:neutron_reflector>],[null, <ic2:neutron_reflector>, null]]);
```

**Comment by tfox83** [comment]
these are both fixed in next update
