### ISSUE TITLE
Cannot Craft IC2 Forge Hammer

### ISSUE THREAD

**Issue by DocRegnas** [FTBTeam/FTB-Ultimate-Reloaded#71]
* **Modpack Version**: 1.0.1
* **Issue**: No recipe for IC2 Forge Hammer
* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**: Clicking on Forge hammer in JEI just pulls up enchanting w/ anvil.  Tried the usual recipe for it on multiple crafting tables with no luck, rotated the recipe, no luck, I'm at a loss.

**Comment by tfox83** [comment]
The forge hammer doesnt exist in classic mode, there for there is no recipe.

**Comment by YouPelicant** [comment]
How do we change off of classic mode? Will that require starting a new game?
