### ISSUE TITLE
AE2 Missing Components \ Console Errors

### ISSUE THREAD

**Issue by Savag3life** [FTBTeam/FTB-Ultimate-Reloaded#72]
* **Modpack Version**: 1.0.1

* **Issue**: Applied Energistics is missing components due to a FML loading error.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9a17d083

* **Is it Repeatable?**: Single Player & Server

* **Mod/s Affected**: Applied Energistics 2

* **Known Fix**: N/A

**Comment by tfox83** [comment]
That is due to channels being disabled, you can ignore as it breaks nothing in game
