### ISSUE TITLE
Quarry Not Working

### ISSUE THREAD

**Issue by itsNeutron** [FTBTeam/FTB-Ultimate-Reloaded#73]
* **Modpack Version**: * 1.0.1

* **Issue**: Quarry isn't working, and it doesn't accept any type of energy

* **Is it Repeatable?**: Just place a quarry and try to make it working

* **Mod/s Affected**: IC2

* **Known Fix**: //

**Comment by tfox83** [comment]
the quarry is BC, therefore it takes MJ.  Works as intended
