### ISSUE TITLE
Industrialcraft sounds persist after machine has finished.

### ISSUE THREAD

**Issue by Steampunk-Wizard** [FTBTeam/FTB-Ultimate-Reloaded#75]
* **Modpack Version**: FTB Ultimate Reloaded 1.0.1

* **Issue**: Some sounds persist indefinitely when they should stop, notably: Industrialcraft machines continue to make their processing noises if they finish while the player isn't nearby. These are chunkloaded with the FTB Utils feature. The Advanced Electric Jetpack (and presumably all jetpack sounds) persist if you turn off the jetpack (with the F key) before landing while the noise is playing. The sound will 'float' in the place where you turned off the jetpack. I would -assume- this is a bug with the most recent build of industrialcraft, as this problem doesn't exist in other modpacks like Revelation, and I've yet to run into any Non-IC2 sounds that persist like this.

If it matters, I'm running the default "Classic" IC2 profile that comes standard with the pack. 

* **Is it Repeatable?**: Both the jetpack and IC2 machines seem to re-produce this bug quite reliably, especially simple with the jetpack. 

* **Mod/s Affected**: Industrialcraft, Gravitation Suite

* **Known Fix**: In the case of the machines, you can either break and replace to stop the sound, or put in items and let them process while you are still within the range of the sound. For the jetpack, turning it back on and using it seems to remove the persistent sound.

**Comment by tfox83** [comment]
It has been a known issues with IC2 and other mods that use sounds for a long time.  If it is ever fixed I will get that into the pack right away.
