### ISSUE TITLE
Nanosaber requires a *fully charged* lapotron to craft

### ISSUE THREAD

**Issue by ProTriforcer** [FTBTeam/FTB-Ultimate-Reloaded#77]
* **Modpack Version**:  1.0.1

* **Issue**: Nanosaber's recipe requires a fully charged lapotron while other recipes ignore its charge. Some recipes that use re-batteries and energy crystals behave the same way. 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IC2/TR

**Comment by ProTriforcer** [comment]
I think i know what causes this. Discharged batteries/lapotrons etc aren't registered in ore dictionary
![2019-02-19_15 13 40](https://user-images.githubusercontent.com/25221392/53007753-b7174500-3459-11e9-8b6c-01d7cf48d415.png)
![2019-02-19_15 13 42](https://user-images.githubusercontent.com/25221392/53007755-b7174500-3459-11e9-9aec-bb49ed773d7c.png)
![2019-02-19_15 13 46](https://user-images.githubusercontent.com/25221392/53007756-b7174500-3459-11e9-9cdb-2a9fc44e5e4a.png)

**Comment by tfox83** [comment]
fixed in next update
