### ISSUE TITLE
missing recipes for copper cable from tech reborn

### ISSUE THREAD

**Issue by warlock1984** [FTBTeam/FTB-Ultimate-Reloaded#78]
* **Modpack Version**: 1.0.1
* **Issue**: missing recipe for copper cable from tech reborn needed for craft wiring from modular powersuits. without them you can craft modules for power tool and armor and without modules power tool and armor are useless.

* **Link to Log or Crash File Paste**: no crash
* **Is it Repeatable?**:yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by monkeybug34** [comment]
I posted this issue a weekish ago. fixed in 1.1.0 the recipe now uses IC2 cables instead.

**Comment by tfox83** [comment]
monkeybug34 is correct, this was fixed in the latest beta 1.1.0
