### ISSUE TITLE
TR Thermal Generator produces incorrect amounts of power from fuels

### ISSUE THREAD

**Issue by Catonyx** [FTBTeam/FTB-Ultimate-Reloaded#8]
* **Modpack Version**: 1.0.1

* **Issue**: Oil (Cool) from BuildCraft produces -1.619G EU in a Tech Reborn Thermal Generator.
Other fuels from BC and Forestry ethanol are similarly affected

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tech Reborn, BuildCraft, Forestry

**Comment by tfox83** [comment]
@modmuss50 mind having a look?

**Comment by modmuss50** [comment]
This is just a visual bug, I will look into it.

**Comment by Catonyx** [comment]
It's not just visual. I put in the bucket of oil in the generator and it produced over 350k EU on less than 1mb of oil. And Fuel (cool) does not display a negative EU count, but still produces over 10x more EU than a bucket of heliumplasma

**Comment by modmuss50** [comment]
Fixed, will be in the next version.

**Comment by tfox83** [comment]
Fixed in 1.1.0 of the pack, due out later today
