### ISSUE TITLE
[Request] chisel bit bag stack size

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Ultimate-Reloaded#81]
* **Modpack Version**: 1.1.0 Beta

* **Issue**: The stack size of the bit bag from chisel and bits is a bit lacking. you chisel one whole block and the bag is suddenly a quarter full.

* **Mod/s Affected**: Chisel and Bits

* **Known Fix**: In the chisel and Bits config, increase the stack size. prefferably to 16^3 (aka 4096)

**Comment by tfox83** [comment]
will be in 1.1.1
