### ISSUE TITLE
lang.java.NullPointerExcepion when connecting to a server.

### ISSUE THREAD

**Issue by nikolosrus** [FTBTeam/FTB-Ultimate-Reloaded#82]
1.0.1 FTB-Ultimate-Reloaded

Issue: lang.java.NullPointerException when connecting to a server. ( Using Twitch )

Crash: Didn't crash.

Repeating the Issue: If you launch the FTB Ultimate Reloaded from Twitch / Minecraft and try to connect to a server you will get this error

Mods: No mods caused the issue.

Fix: no knows fixes at all, relogging doesn't work.
![8e9335e9917112244711740aa86536dd](https://user-images.githubusercontent.com/47812667/53079862-2dc74780-3519-11e9-948c-a77a7aa98cdc.png)

**Comment by tfox83** [comment]
Will need logs.  Also try a fresh install of your client, we are not seeing this issue in testing.

**Comment by LemADEC** [comment]
This happens when connecting with invalid mods through a proxy.
Check the server discord announcements, you probably need to update your modpack to a more recent version.
