### ISSUE TITLE
Engineer's Manual

### ISSUE THREAD

**Issue by grecolons** [FTBTeam/FTB-Ultimate-Reloaded#83]
Engineer's Manual from Immersive Engineering not showing up in game. Can't be crafted and can't be found with JEI. 
Version 1.0.1 FTB Ultimate Reloaded

**Comment by tfox83** [comment]
Its not needed for anything, most of IE is disabled in this pack.

**Comment by TheElementalOfDestruction** [comment]
So I've noticed by looking through the issues that IE has been pretty much entirely disabled. So why does it exist at all in the pack? 

(I also spent way too long trying to figure out how to use it only to come here and find out it is mostly disabled. Is there a way to tell this from in game? Maybe it would be a good idea to have any recipes from IE multiblock structures disabled so others don't waste time trying to figure out how to get a disabled thing to work?)
