### ISSUE TITLE
Few issues found between IC2 and TechReborn

### ISSUE THREAD

**Issue by Argo11** [FTBTeam/FTB-Ultimate-Reloaded#84]
* **Modpack Version**: 1.0.1

* **Issues**: 
-TechReborn machines cannot be picked up by IC2 electrical wrench(though you can rotate it). Normal IC2 wrenches can pick it up.
-Mining the TechReborn machines drops the machine frames(as it is supposed to), but the machine frame it drops is TechReborn and not IC2(which is the type that is used most frequently in recipes). 

* **Link to Log or Crash File Paste**: Not crash-related

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: TechReborn, IndustrialCraft 2

* **Known Fix**: first issue can be avoided by using non-electric IC2/TechReborn wrenches(and a few others), 2nd has no known fix.

Note I am not sure if I should have reported this to each mod creators or the pack, but I assumed this was more of a pack issue given how both issues can most likely be changed in a pack(and are also unnecessary unless both mods are in the pack).

There are probably a few more issues between TechReborn and IC2 that I have not found.

**Comment by tfox83** [comment]
This is fixed in the latest betas
