### ISSUE TITLE
Tin Dupe Bug

### ISSUE THREAD

**Issue by wagyourtail** [FTBTeam/FTB-Ultimate-Reloaded#85]
* **Modpack Version**: 1.0.1
* **Issue**: pulverizing empty cell results in 4x small pile of tin dust. 4 tin crafts 16 cells... therefore crafting and pulverizing empty cells will net a gain of 12 tin dust per 16 empty cells crafted at a cost of 1 glass pane per 16 cells.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes. easily

* **Mod/s Affected**: 

* **Known Fix**: change output for pulverizing empty cell to 1x small pile of tin dust.

**Comment by tfox83** [comment]
its not meant to be pulverized, good catch.  This has been removed next update
