### ISSUE TITLE
Harvester infinite range

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Ultimate-Reloaded#86]
* **Modpack Version**: 1.0.1

* **Issue**: harvester when set to trees harvests a giant area rather then the intended area

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes, place a harvester down and set it to trees. Sometimes you need to upgrade it but let me know if its not happening so i can make a video or something

* **Mod/s Affected**: MFR

* **Known Fix**: N/A

**Comment by tfox83** [comment]
It looks beyond for leaves, safe practice with IF and MRF farms have at least 16 blocks free between the edge of the farm and other trees.  Been a mechanic since MFR added upgrades in MC 1.5
