### ISSUE TITLE
No Fuel for Railcraft Liquid fueled Boiler

### ISSUE THREAD

**Issue by Poegy** [FTBTeam/FTB-Ultimate-Reloaded#87]
No oil by product accepted by the liquid fueled boiler

-->

* **Modpack Version**: v1.1.0

* **Issue**: 
From messing around in creative, the only fluids Railcraft Liquid Fueled Firebox will accept is:

Creosote Oil
Ethanol (Forestry)
Biofuel (Industrial Foregoing)

Ideally it should accept refined fuel from thermal expansion and at least one type of fuel from buildcraft

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: railcraft

* **Known Fix**:

**Comment by tfox83** [comment]
RC is in alpha and doent not have much compact at this time, I am sure once he gets the mod more finished support for other stuff will be added
