### ISSUE TITLE
Cant craft thermal foundation gears

### ISSUE THREAD

**Issue by jasperdewinther** [FTBTeam/FTB-Ultimate-Reloaded#89]
* **Modpack Version**: 1.0.1

* **Issue**: Cant craft thermal foundation gears, the recipe with 4 sticks in a circle creates wooden gear from AE2. This can be crafted into buildcraft stone gear but these cant be used to craft tin gears which are required for rotary macerator. I have not tried to use a compactor with a gearworking die, as you need gears for those.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Big part of IC2, tech reborn, advanced machines and thermal foundation

* **Known Fix**: haven't found one except for cheating the items in.

**Comment by tfox83** [comment]
Seems like your configs or scripts got messed up on install.  Please try a fresh install.  4 sticks should produce a TE wooden gear.
