### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by CagivaKid** [FTBTeam/FTB-Ultimate-Reloaded#9]
Modpack Version :- 1.0.0

Issue :- Items in the JEI have dissapeared, yesterday I had 24 pages but today there are only 22, I made certain items that were available yesterday like the IndustrialCraft Mining Drill & Advanced Mining Drill from Gravitation Suite but today its unable to be found within the JEI or the Search Bar. Im not sure what other items are missing only that I have 2 less pages showing so know its quite a few.

Link to Log or Crash File :- N/A

Is it Repeatable? :- Tried restarting, tried fresh install an still cant locate certain items that i made yesterday!

Mod/s Affected :- IndustrialCraft2 & Gravitation Suite (only 2 that i made items from yesterday) must be more as earlier stated im missing 2 whole pages from the JEI 

Known Fix :- Yet to find one!

**Comment by tfox83** [comment]
If you load a resource pack or reload resources the hidden items from JEI appear until next reboot.  Its a known issues at the moment without a fix.

**Comment by tfox83** [comment]
Also those tools have been properly removed in 1.0.1
