### ISSUE TITLE
Dupe bug with Tech Reborn Casings

### ISSUE THREAD

**Issue by MrTiltit** [FTBTeam/FTB-Ultimate-Reloaded#90]
* **Modpack Version**: 1.0.1

* **Issue**: If you break a machine casing you get back one machine frame. With the frame you can make 4 new casings and so on. Happens with all three casings. 

* **Link to Log or Crash File Paste**: ///

* **Is it Repeatable?**: just try it with a diamond drill or pickaxe 

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: ///

**Comment by tfox83** [comment]
Hmm good catch.  This is in the mod, let me see if @modmuss50 could have a look at this.  Maybe it should drop something else if broken.  Or just drop the casing with any tool break to be safe.

**Comment by modmuss50** [comment]
Fixed in the next update.

**Comment by tfox83** [comment]
will be in next update of the pack today
