### ISSUE TITLE
Itemduct crafting issues

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#91]
* **Modpack Version**: 1.0.1

* **Issue**: Fix itemduct crafting recipes, as when you press the "recipe" key while hovering over an itemduct in JEI it gives you 2 more tabs of unrelated itemduct recipes.
while this normally isn't a problem, when we have 30 itemducts to choose from it gets annoying quickly.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ThermalDynamics

* **Known Fix**: CT changes

**Comment by EthernalVoid** [comment]
![q](https://user-images.githubusercontent.com/45131452/53278141-d76c2b80-3707-11e9-8bef-acee5905152f.jpg)
![w](https://user-images.githubusercontent.com/45131452/53278142-d76c2b80-3707-11e9-8561-cd1b797aeccc.jpg)
![e](https://user-images.githubusercontent.com/45131452/53278144-d76c2b80-3707-11e9-922d-d950955fba0f.jpg)

**Comment by EthernalVoid** [comment]
And that for a "how its made" recipe, not a "where it's used" recipe

**Comment by EthernalVoid** [comment]
![q](https://user-images.githubusercontent.com/45131452/53278217-477ab180-3708-11e9-9ed4-0695b70314d4.jpg)

where its used proof, clearly seen by the available thauminomicon book
![use](https://user-images.githubusercontent.com/45131452/53278236-5f523580-3708-11e9-99f8-1e950e595938.jpg)

**Comment by tfox83** [comment]
Submit this to COFH if you want that changed.
