### ISSUE TITLE
UU matter recipes

### ISSUE THREAD

**Issue by ThwartAbyss54** [FTBTeam/FTB-Ultimate-Reloaded#93]
* **Modpack Version**: 1.1.1

* **Issue**: Theres a few recipe issues with UU matter recipes. Off the top of my head there are 2 pulverized platinum recipes where the second one is just 8 pieces of uumatter instead of 7. The 7 piece one is a unidict recipe if that matters.

* **Is it Repeatable?**:  Yes, looking them up in jei

Do you guys care about issues like this?

**Comment by tfox83** [comment]
That is just due to having two types of UU matter.  It is not an issue at this time and either recipe works. Thanks for the issue post.
