### ISSUE TITLE
Nuclear Reactor power output

### ISSUE THREAD

**Issue by ThwartAbyss54** [FTBTeam/FTB-Ultimate-Reloaded#94]
* **Modpack Version**: 1.1.1

* **Issue**: Is the IC2 nuclear reactor suppose to be halved for eu production? Im pretty sure its set that way in default ic2 so players do steam but in this pack we cant do that, is this intended by you guys for balance reasons?

I dont see a config setting to turn that off so thats a little annoying, guess that answers my question

**Comment by tfox83** [comment]
No I believe that is a result of running the Classic Profile.
