### ISSUE TITLE
TR High end power uses overly high voltage tier

### ISSUE THREAD

**Issue by Justfines** [FTBTeam/FTB-Ultimate-Reloaded#95]
**Modpack version**: 1.1.1

**Issue**:
Tech Reborn's EU voltage for high end power generation and storage is currently to high to be handled with any cabling since IC2's wiring is limited to 2048 (EV) and the IV transformer is disabled. This makes it impossible to theoretically handle IDSU power (tooltip shows incorrect voltage and I/O rates), or in actuality the higher selected voltage in an AESU. This also makes actual use of TR fusion power impractical since it'd need an unreasonable amount of connections directly to AESUs to fully output or similar to downscale the voltage to EV at most.

**Mod Affected**: Tech Reborn

**Suggested Fix**:
All I can suggest to fix this would either limit max EU/t output rates to EV for TR, or enable the IV transformer and IV compatible cabling from IC2 or TR with it, as they are only thing capable of transferring this level of voltage without direct connection. IV level stuff already have the appropriate

On a side note, If this was also changed to enable IV transfer, IC2 machines with 4 transformers are able to handle direct IV power, if that much transfer is desired

**Comment by tfox83** [comment]
The IV consumer/producer is reenabled, as well as the quantum solar.  At this time only a hard connection is allowed.  I have requested being able to edit the amount of EU the cables can transfer.

**Comment by Justfines** [comment]
I will just mention this after some testing: even the power converters have issues handling the sheer power output of fusion reaction. it seems the internal "energy stored" of the energy bridges get instantly filled to the point it throttles use. This to be fair is the only device that outputs so much energy and only have two output faces. A way to get around this would be to increase the energyBridgeBuffer number inside the energy converters config.

To support the smallest fusion reactor's He3-D reaction would require it to be at around 131072 as EU is 4x the internal energy, and any larger ones would need even greater
