### ISSUE TITLE
Strange particle effect from Forestry

### ISSUE THREAD

**Issue by monkeybug34** [FTBTeam/FTB-Ultimate-Reloaded#96]
* **Modpack Version**: 1.1.1
* **Issue**: encountering the forestry habitat former (by placing it or walking into someone's base where it has been placed) will cause yellow and blue particles to appear near the player and then fade. the effect is permanent and persists after relogging.

* **Is it Repeatable?**: Myself and several players on a server have encountered the issue, so it should be repeatable.

* **Mod/s Affected**: Forestry 5.8.2.383

* **Known Fix**: no known fix

**Comment by tfox83** [comment]
Fix in latest forestry
