### ISSUE TITLE
mini map problem

### ISSUE THREAD

**Issue by wrightkj1** [FTBTeam/FTB-Ultimate-Reloaded#99]
* **Modpack Version**: <1.12.2>

* **Issue**: <Minecraft stated that it chrashed due to a problem with the mini map mod you have in here idk witch one off the top of my head >

* **Link to Log or Crash File Paste**: The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Xaero's World Map has crashed! Please contact the author at planetminecraft.com/member/xaero96 or minecraftforum.net/members/xaero96
[crash-2019-02-25_10.29.54-client.txt](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/files/2902084/crash-2019-02-25_10.29.54-client.txt)

* **Is it Repeatable?**: <it has happened three times>

* **Mod/s Affected**:Xaero's World Map

 <* **Known Fix**:

**Comment by tfox83** [comment]
not nearly enough info.

**Comment by wrightkj1** [comment]
dose that make it enough info .

**Comment by wrightkj1** [comment]
I could give more crash reports if needed
